# Generated by Django 5.2 on 2026-04-02 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_remove_searchmetric_analytics_sm_ci_date_idx_and_more"),
        ("content", "0014_fr014_near_duplicate_clustering"),
        ("suggestions", "0018_alter_weightadjustmenthistory_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ga4", "Google Analytics 4"),
                            ("matomo", "Matomo"),
                            ("gsc", "Google Search Console"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("lookback_days", models.IntegerField(default=7)),
                ("rows_read", models.IntegerField(default=0)),
                ("rows_written", models.IntegerField(default=0)),
                ("rows_updated", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Analytics Sync Run",
                "verbose_name_plural": "Analytics Sync Runs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "-started_at"],
                        name="analytics_a_source_7a98bd_idx",
                    ),
                    models.Index(
                        fields=["status", "-started_at"],
                        name="analytics_a_status_3c5956_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TelemetryCoverageDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("event_schema", models.CharField(default="fr016_v1", max_length=50)),
                ("source_label", models.CharField(blank=True, max_length=50)),
                (
                    "algorithm_version_slug",
                    models.CharField(blank=True, max_length=100),
                ),
                ("expected_instrumented_links", models.IntegerField(default=0)),
                ("observed_impression_links", models.IntegerField(default=0)),
                ("observed_click_links", models.IntegerField(default=0)),
                ("attributed_destination_sessions", models.IntegerField(default=0)),
                ("unattributed_destination_sessions", models.IntegerField(default=0)),
                ("duplicate_event_drops", models.IntegerField(default=0)),
                ("missing_metadata_events", models.IntegerField(default=0)),
                ("delayed_rows_rewritten", models.IntegerField(default=0)),
                (
                    "coverage_state",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("partial", "Partial"),
                            ("degraded", "Degraded"),
                        ],
                        default="partial",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telemetry Coverage Daily",
                "verbose_name_plural": "Telemetry Coverage Daily",
                "ordering": ["-date", "source_label", "algorithm_version_slug"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "date",
                            "event_schema",
                            "source_label",
                            "algorithm_version_slug",
                        ),
                        name="analytics_coverage_daily_unique_rollup",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SuggestionTelemetryDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "telemetry_source",
                    models.CharField(
                        choices=[("ga4", "Google Analytics 4"), ("matomo", "Matomo")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("algorithm_key", models.CharField(blank=True, max_length=100)),
                ("algorithm_version_date", models.DateField(blank=True, null=True)),
                (
                    "algorithm_version_slug",
                    models.CharField(blank=True, max_length=100),
                ),
                ("event_schema", models.CharField(default="fr016_v1", max_length=50)),
                ("device_category", models.CharField(blank=True, max_length=50)),
                ("default_channel_group", models.CharField(blank=True, max_length=120)),
                ("source_medium", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=120)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("source_label", models.CharField(blank=True, max_length=50)),
                ("same_silo", models.BooleanField(blank=True, null=True)),
                ("impressions", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("destination_views", models.IntegerField(default=0)),
                ("engaged_sessions", models.IntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                ("sessions", models.IntegerField(default=0)),
                ("bounce_sessions", models.IntegerField(default=0)),
                ("avg_engagement_time_seconds", models.FloatField(default=0.0)),
                ("total_engagement_time_seconds", models.FloatField(default=0.0)),
                ("event_count", models.IntegerField(default=0)),
                ("is_attributed", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_as_destination",
                        to="content.contentitem",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_as_host",
                        to="content.contentitem",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_rows",
                        to="suggestions.suggestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suggestion Telemetry Daily",
                "verbose_name_plural": "Suggestion Telemetry Daily",
                "ordering": ["-date", "telemetry_source", "-clicks"],
                "indexes": [
                    models.Index(
                        fields=["algorithm_version_slug", "date"],
                        name="analytics_s_algorit_64489e_idx",
                    ),
                    models.Index(
                        fields=["telemetry_source", "date"],
                        name="analytics_s_telemet_355e26_idx",
                    ),
                    models.Index(
                        fields=["suggestion", "-date"],
                        name="analytics_s_suggest_20339a_idx",
                    ),
                    models.Index(
                        fields=["destination", "-date"],
                        name="analytics_s_destina_fecec0_idx",
                    ),
                    models.Index(
                        fields=["device_category", "date"],
                        name="analytics_s_device__73a561_idx",
                    ),
                    models.Index(
                        fields=["default_channel_group", "date"],
                        name="analytics_s_default_eafc32_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "date",
                            "telemetry_source",
                            "suggestion",
                            "algorithm_version_slug",
                            "device_category",
                            "default_channel_group",
                            "source_medium",
                            "country",
                            "region",
                            "is_attributed",
                        ),
                        name="analytics_telemetry_daily_unique_rollup",
                    )
                ],
            },
        ),
    ]
