# Generated by Django 5.2 on 2026-04-03 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_gsckeywordimpact'),
        ('suggestions', '0018_alter_weightadjustmenthistory_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSCDailyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(db_index=True, max_length=2000)),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('avg_position', models.FloatField(default=0.0)),
                ('ctr', models.FloatField(default=0.0)),
                ('property_url', models.CharField(blank=True, help_text='The GSC property this belongs to.', max_length=500)),
            ],
            options={
                'verbose_name': 'GSC Daily Performance',
                'verbose_name_plural': 'GSC Daily Performance Rows',
                'indexes': [models.Index(fields=['date', 'page_url'], name='analytics_g_date_5559de_idx')],
                'unique_together': {('page_url', 'date', 'property_url')},
            },
        ),
        migrations.CreateModel(
            name='GSCImpactSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateTimeField(db_index=True)),
                ('window_type', models.CharField(choices=[('7d', '7 Days'), ('14d', '14 Days'), ('28d', '28 Days'), ('90d', '90 Days')], default='28d', max_length=10)),
                ('baseline_clicks', models.IntegerField(default=0)),
                ('post_clicks', models.IntegerField(default=0)),
                ('lift_clicks_pct', models.FloatField(default=0.0, help_text='Relative click lift: (post - baseline) / baseline.')),
                ('lift_clicks_absolute', models.IntegerField(default=0)),
                ('probability_of_uplift', models.FloatField(default=0.0, help_text='Bayesian probability of positive lift (0.0 to 1.0).')),
                ('reward_label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('inconclusive', 'Inconclusive')], default='inconclusive', max_length=20)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('suggestion', models.OneToOneField(help_text='The suggestion this attribution belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='gsc_impact', to='suggestions.suggestion')),
            ],
            options={
                'verbose_name': 'GSC Impact Snapshot',
                'verbose_name_plural': 'GSC Impact Snapshots',
                'ordering': ['-apply_date'],
            },
        ),
    ]
