# Generated by Django 5.2 on 2026-04-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_gscimpactsnapshot_suggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gscimpactsnapshot',
            name='baseline_impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gscimpactsnapshot',
            name='post_impressions',
            field=models.IntegerField(default=0),
        ),
    ]
