# Generated by Django 5.2 on 2026-04-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_gscimpactsnapshot_baseline_impressions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactreport',
            name='control_match_count',
            field=models.IntegerField(default=0, help_text='Number of controls selected after similarity matching.'),
        ),
        migrations.AddField(
            model_name='impactreport',
            name='control_match_quality',
            field=models.FloatField(blank=True, help_text='Average pre-period similarity score of selected controls (0-1).', null=True),
        ),
        migrations.AddField(
            model_name='impactreport',
            name='control_pool_size',
            field=models.IntegerField(default=0, help_text='Number of candidate control items before similarity matching.'),
        ),
        migrations.AddField(
            model_name='impactreport',
            name='is_conclusive',
            field=models.BooleanField(default=True, help_text='False when insufficient controls or data make the result unreliable.'),
        ),
    ]
