# Generated by Django 5.2 on 2026-04-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0008_add_impact_report_confidence_fields"),
        ("content", "0018_add_content_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchedPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="User notes about why they're watching this page.",
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="content.contentitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watched Page",
                "verbose_name_plural": "Watched Pages",
                "ordering": ["-added_at"],
                "unique_together": {("content_item",)},
            },
        ),
    ]
