# Generated by Django 5.2.13 on 2026-04-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0009_add_watched_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestiontelemetrydaily",
            name="dwell_30s_sessions",
            field=models.IntegerField(
                default=0,
                help_text="Count of sessions that stayed on the destination page for 30s+ (suggestion_destination_dwell_30s event). Intermediate positive signal.",
            ),
        ),
        migrations.AddField(
            model_name="suggestiontelemetrydaily",
            name="dwell_60s_sessions",
            field=models.IntegerField(
                default=0,
                help_text="Count of sessions that stayed on the destination page for 60s+ (suggestion_destination_dwell_60s event). Strong positive signal.",
            ),
        ),
        migrations.AddField(
            model_name="suggestiontelemetrydaily",
            name="quick_exit_sessions",
            field=models.IntegerField(
                default=0,
                help_text="Count of sessions where the user left the destination page within 5s of landing (suggestion_destination_quick_exit event). Strong negative signal — 'pogo-sticking' — a bad suggestion match.",
            ),
        ),
    ]
