# Generated by Django 5.2.13 on 2026-05-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_add_engagement_phase2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatomoDailyTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, help_text="Matomo site id (e.g. '2' for misc.goldmidi.com WP, '3' for goldmidi.com/community/ XF).", max_length=8)),
                ('date', models.DateField(db_index=True)),
                ('page_url', models.URLField(db_index=True, max_length=2000)),
                ('label', models.CharField(blank=True, help_text="Matomo's leaf-row label (path or title); kept verbatim for debugging.", max_length=500)),
                ('nb_visits', models.PositiveIntegerField(default=0)),
                ('nb_hits', models.PositiveIntegerField(default=0, help_text='Total page views — proxy for impressions.')),
                ('nb_uniq_visitors', models.PositiveIntegerField(default=0)),
                ('bounce_count', models.PositiveIntegerField(default=0)),
                ('sum_time_spent', models.PositiveIntegerField(default=0, help_text='Sum of time-on-page across all visits, in seconds.')),
            ],
            options={
                'verbose_name': 'Matomo Daily Traffic',
                'verbose_name_plural': 'Matomo Daily Traffic Rows',
                'indexes': [models.Index(fields=['date', 'site_id'], name='analytics_m_date_43d4b8_idx')],
                'unique_together': {('site_id', 'date', 'page_url')},
            },
        ),
    ]
