# Generated by Django 5.2 on 2026-04-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        db_index=True,
                        help_text="Celery task ID or unique job identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        help_text="Type of task: sync, pipeline, embeddings, broken_link_scan, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        help_text="Worker name or helper node name that owns this task.",
                        max_length=200,
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(help_text="When this lease was acquired."),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        help_text="Last time the owner confirmed it is still working on this task."
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="If no heartbeat arrives by this time, the lease is considered expired.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("resumable", "Resumable"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Lease",
                "verbose_name_plural": "Job Leases",
                "ordering": ["-acquired_at"],
            },
        ),
    ]
