# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0004_rename_pipeline_bakeoff_cr_idx_pipeline_em_created_9d3bc1_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddingbakeoffresult",
            name="compared_to",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="embeddingbakeoffresult",
            name="verdict",
            field=models.CharField(db_index=True, default="pending", max_length=32),
        ),
        migrations.AddField(
            model_name="embeddingbakeoffresult",
            name="p_value",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name="embeddingbakeoffresult",
            name="loss_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="embeddingbakeoffresult",
            name="is_banned",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="embeddingbakeoffresult",
            name="explanation",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
