#!/usr/bin/env python3
"""Pre-commit gate for Rule B (Strict Red-Green-Refactor TDD).

Tightened 2026-05-16: every touched production source file MUST have its
own `[TDD CYCLE: file=<src> ...]` marker in the staged AGENT-HANDOFF.md
entry. Previously the hook only needed one marker total, which meant an
agent could stage fifty files and pass with a single placeholder marker.

The new shape mirrors Rule G (check-code-review-lessons.py): N markers
must cover M production source files, where:

  - N = number of [TDD CYCLE: ...] markers whose `file=` value matches a
    staged source path
  - M = count of staged production source files AFTER exemptions

Exempt files (carry their own self-explanatory test path, no TDD needed):

  - test files themselves (the test path filter)
  - generated stubs (first non-shebang line starts with "# ruff: noqa",
    or first 5 lines contain "Generated by")
  - shell scripts (.sh) - no Python TDD framework applies
  - protobuf-generated *_pb2.py / *_pb2_grpc.py and *.pb.go / *_grpc.pb.go

Rule F-compliant: three-part FAIL with what / why / unblock.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Matches one TDD CYCLE marker and captures the file= field. The file path
# can be quoted or bare; we accept both forms.
_TDD_CYCLE_RE = re.compile(
    r"\[TDD CYCLE(?: STRICT)?:[^\]]*\bfile=(?:\"([^\"]+)\"|(\S+?))(?:\s|\])"
)

# 2026-05-17 — paper-trail #586 / test_case #704.
# Batch-grandfather form for rule-introduction commits. Collapses an
# N-file per-file grandfather wall to one marker per rule. Accepted ONLY
# when at least one docs/*-RULE.md is in the staged diff.
_BATCH_GRANDFATHER_RE = re.compile(
    r"\[RULE\s+INTRODUCTION\s+BATCH\s+GRANDFATHERED:\s*"
    r"paper_trail=#(?P<paper_trail>\d+)\s+"
    r"reason=\"(?P<reason>[^\"]+)\"\s+"
    r"files=(?P<glob>\S+?)\s*\]",
    re.IGNORECASE,
)
_BATCH_MIN_REASON_CHARS = 20

# Production source path filter (anything matching these prefixes + suffixes
# is a candidate for the TDD requirement, unless exempted below).
_SOURCE_PREFIXES = (
    "backend/apps/",
    "backend/extensions/",
    "frontend/src/",
    "scripts/",
    "services/",
    ".githooks/",
)
_SOURCE_SUFFIXES = (".py", ".cpp", ".h", ".ts", ".tsx", ".go")

# Generated-code exemptions. A file matches when:
#   - its name matches one of these glob suffixes, OR
#   - its first non-shebang line equals `# ruff: noqa`, OR
#   - its first 5 lines contain the string "Generated by"
_GENERATED_NAME_SUFFIXES = (
    "_pb2.py",
    "_pb2_grpc.py",
    ".pb.go",
    "_grpc.pb.go",
)
_GENERATED_HEADER_MARKERS = ("# ruff: noqa", "// Code generated by", "Generated by")


def _is_test_path(path: str) -> bool:
    """Tests are exempt - the test file is the Red, not the source under test."""
    name = Path(path).name.lower()
    normalized = path.replace("\\", "/")
    return (
        name.startswith("test_")
        or name.startswith("tests_")
        or name.endswith("_test.go")
        # 2026-05-17 — Angular convention: foo.spec.ts / foo.test.ts is a
        # test file, not production source. Matches check-tdd-strict's
        # shared _hook_helpers.TEST_FILE_PATTERNS recognition.
        or name.endswith(".spec.ts")
        or name.endswith(".test.ts")
        or "/test/" in normalized
        or "/tests/" in normalized
        or "/__tests__/" in normalized
    )


def _is_generated_path(path: str) -> bool:
    if any(path.endswith(suffix) for suffix in _GENERATED_NAME_SUFFIXES):
        return True
    full = REPO_ROOT / path
    if not full.is_file():
        return False
    try:
        with full.open("r", encoding="utf-8", errors="replace") as fh:
            head = [fh.readline() for _ in range(5)]
    except OSError:
        return False
    joined = "".join(head)
    return any(marker in joined for marker in _GENERATED_HEADER_MARKERS)


def _staged_source_files() -> list[str]:
    """Production source files that need a TDD CYCLE marker."""
    try:
        out = subprocess.run(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []
    files: list[str] = []
    for raw in (out.stdout or "").splitlines():
        line = raw.strip()
        if not line:
            continue
        if not line.startswith(_SOURCE_PREFIXES):
            continue
        if not line.endswith(_SOURCE_SUFFIXES):
            continue
        if _is_test_path(line):
            continue
        if _is_generated_path(line):
            continue
        files.append(line)
    return files


def _staged_handoff_diff() -> str:
    """Read the staged AGENT-HANDOFF.md diff as UTF-8 with replace fallback.

    Without an explicit encoding the subprocess uses the Windows locale
    codec (cp1252) and chokes on UTF-8 characters (em-dashes, arrows,
    curly quotes) that legitimately appear in handoff entries; the diff
    parses as a short truncated string and the markers go missing.
    """
    try:
        out = subprocess.run(
            ["git", "diff", "--cached", "--unified=0", "--", "AGENT-HANDOFF.md"],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=10,
            check=False,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return ""
    return "\n".join(
        line[1:]
        for line in (out.stdout or "").splitlines()
        if line.startswith("+") and not line.startswith("+++")
    )


def _marker_files(handoff_diff: str) -> set[str]:
    """Files that have a [TDD CYCLE: ... file=<src> ...] marker in the diff."""
    files: set[str] = set()
    for quoted, bare in _TDD_CYCLE_RE.findall(handoff_diff):
        value = quoted or bare
        if not value:
            continue
        # Normalise: strip any trailing punctuation and use forward slashes.
        normalised = value.replace("\\", "/").strip().rstrip(";")
        files.add(normalised)
    return files


def _batch_grandfather_covered(
    handoff_diff: str,
    staged_paths: list[str],
    source_files: list[str],
) -> tuple[set[str], int]:
    """Expand [RULE INTRODUCTION BATCH GRANDFATHERED:] markers.

    Returns (covered_files, exit_code). 0 on continue, 2 on fail with
    stderr already written. paper-trail #586 / test_case #704.
    """
    import fnmatch

    batch_markers = list(_BATCH_GRANDFATHER_RE.finditer(handoff_diff))
    if not batch_markers:
        return set(), 0

    rule_specs_staged = [
        p for p in staged_paths
        if p.startswith("docs/") and p.endswith("-RULE.md")
    ]
    if not rule_specs_staged:
        sys.stderr.write(
            "FAIL check-tdd-cycle: [RULE INTRODUCTION BATCH GRANDFATHERED:] "
            "markers are present but NO docs/*-RULE.md is in the staged "
            "diff.\n"
            "WHY: the batch-grandfather form is a one-time bypass for "
            "rule-introduction commits. The gate is having the matching "
            "spec staged in the same diff.\n"
            "UNBLOCK: stage the rule spec, OR add per-file [TDD CYCLE: "
            "file=<path> ...] markers for each production source file.\n"
        )
        return set(), 2

    covered: set[str] = set()
    for m in batch_markers:
        d = m.groupdict()
        if len(d["reason"].strip()) < _BATCH_MIN_REASON_CHARS:
            sys.stderr.write(
                f"FAIL check-tdd-cycle: batch-grandfather marker for "
                f"paper_trail=#{d['paper_trail']} has a reason under "
                f"{_BATCH_MIN_REASON_CHARS} chars.\n"
                f"UNBLOCK: rewrite the reason as a real plain-English "
                f"sentence.\n"
            )
            return set(), 2
        glob = d["glob"]
        for f in source_files:
            if fnmatch.fnmatch(f, glob):
                covered.add(f)
            elif "**" in glob:
                head, _, tail = glob.partition("**")
                head = head.rstrip("/")
                tail = tail.lstrip("/")
                if head and not (f.startswith(head + "/") or f.startswith(head)):
                    continue
                if tail and not fnmatch.fnmatch(f, "*" + tail):
                    continue
                covered.add(f)
    return covered, 0


def _staged_paths_all() -> list[str]:
    """Every staged file (ACM), not just production source ones."""
    try:
        out = subprocess.run(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=10,
            check=False,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []
    return [line.strip() for line in (out.stdout or "").splitlines() if line.strip()]


def main() -> int:
    source_files = _staged_source_files()
    if not source_files:
        return 0
    handoff = _staged_handoff_diff()
    covered = _marker_files(handoff)
    # 2026-05-17 — paper-trail #586 batch-grandfather form.
    batch_covered, batch_exit = _batch_grandfather_covered(
        handoff, _staged_paths_all(), source_files,
    )
    if batch_exit != 0:
        return batch_exit
    covered = covered | batch_covered
    missing = sorted(set(source_files) - covered)
    if missing:
        sys.stderr.write(
            "FAIL check-tdd-cycle: production source files are staged but "
            "AGENT-HANDOFF.md is missing one [TDD CYCLE: file=<src> ...] "
            "marker per source file.\n"
            "WHY: Rule B requires strict Red-Green-Refactor TDD for every "
            "code change. The marker proves a failing test was written "
            "first (Red), the minimum source change made it pass (Green), "
            "and the touched file was refactored ruff-clean. One marker per "
            "source file -- no batch markers, no skipping. Generated stubs, "
            "test files, and .sh scripts are exempt; everything else is in.\n"
            "UNBLOCK: For each file below run `docker compose exec -T "
            "backend python manage.py verify_tdd_cycle --source <path> "
            "--test <test_path> --ruff-clean` and paste the printed "
            "[TDD CYCLE: file=<src> ...] marker into the handoff entry. "
            "Do not use --no-verify; bypassing the gate breaks Rule F.\n"
        )
        for path in missing:
            sys.stderr.write(f"  missing TDD CYCLE marker for: {path}\n")
        sys.stderr.write(
            "\nIf the file is genuinely generated (protoc / openapi / etc.) "
            "add `# ruff: noqa` or `Generated by` to its first five lines so "
            "the hook's exemption rule recognises it.\n"
        )
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
