"""Tests for .githooks/check-go-service-contract.py (Rule K, full-tree mode).

Each services/<name>/ folder must satisfy ALL of:
  1. go.mod (Go module declaration)
  2. api.proto OR api.http.md (the public RPC contract)
  3. cmd/<name>/main.go (the binary entry point)
  4. Dockerfile (multi-stage)
  5. api/gen/*.pb.go (generated stubs, when api.proto exists)
  6. docker-compose.yml service block
  7. go.sum populated (when go.mod has require directives)
  8. Dockerfile is multi-stage (>=2 FROM directives)
  9. docker-compose.yml declares <name>_sock named volume (gRPC services only)
"""

from __future__ import annotations

import importlib.util
import sys
import tempfile
from pathlib import Path
from unittest import TestCase

HOOKS_DIR = Path(__file__).resolve().parent
if str(HOOKS_DIR) not in sys.path:
    sys.path.insert(0, str(HOOKS_DIR))


def _load_hook():
    module_name = "check_go_service_contract"
    hook_path = HOOKS_DIR / "check-go-service-contract.py"
    spec = importlib.util.spec_from_file_location(module_name, hook_path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise RuntimeError(f"could not load {hook_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


hook = _load_hook()


_MULTI_STAGE_DOCKERFILE = (
    "FROM golang:1.25-alpine AS build\n"
    "WORKDIR /src\n"
    "COPY . .\n"
    "RUN go build -o /out/app .\n"
    "FROM scratch\n"
    "COPY --from=build /out/app /app\n"
    "ENTRYPOINT [\"/app\"]\n"
)

_SINGLE_STAGE_DOCKERFILE = (
    "FROM scratch\n"
    "ENTRYPOINT [\"/app\"]\n"
)


def _make_service(
    base: Path,
    name: str,
    *,
    with_contract: bool = True,
    with_binary: bool = True,
    with_dockerfile: bool = True,
    with_stubs: bool = True,
    with_compose: bool = True,
    with_compose_volume: bool = True,
    with_go_sum: bool = True,
    multi_stage_dockerfile: bool = True,
    gomod_has_requires: bool = True,
) -> Path:
    folder = base / "services" / name
    folder.mkdir(parents=True, exist_ok=True)
    if gomod_has_requires:
        (folder / "go.mod").write_text(
            f"module xf-internal-linker-v2/services/{name}\n\n"
            "go 1.25\n\n"
            "require (\n"
            "    google.golang.org/grpc v1.66.0\n"
            ")\n",
            encoding="utf-8",
        )
    else:
        (folder / "go.mod").write_text(
            f"module xf-internal-linker-v2/services/{name}\n\ngo 1.25\n",
            encoding="utf-8",
        )
    if with_go_sum:
        (folder / "go.sum").write_text(
            "google.golang.org/grpc v1.66.0 h1:abc123/abcdef\n"
            "google.golang.org/grpc v1.66.0/go.mod h1:def456/fedcba\n",
            encoding="utf-8",
        )
    if with_contract:
        (folder / "api.proto").write_text(
            f"syntax = \"proto3\";\npackage xf.{name}.v1;\n",
            encoding="utf-8",
        )
    if with_binary:
        bin_path = folder / "cmd" / name / "main.go"
        bin_path.parent.mkdir(parents=True, exist_ok=True)
        bin_path.write_text("package main\nfunc main() {}\n", encoding="utf-8")
    if with_dockerfile:
        body = _MULTI_STAGE_DOCKERFILE if multi_stage_dockerfile else _SINGLE_STAGE_DOCKERFILE
        (folder / "Dockerfile").write_text(body, encoding="utf-8")
    if with_stubs and with_contract:
        gen = folder / "api" / "gen"
        gen.mkdir(parents=True, exist_ok=True)
        (gen / "api.pb.go").write_text(
            "// Code generated by protoc-gen-go. DO NOT EDIT.\n"
            f"package {name}v1\n",
            encoding="utf-8",
        )

    compose = base / "docker-compose.yml"
    existing = compose.read_text(encoding="utf-8") if compose.is_file() else "services:\n"
    if with_compose and f"\n  {name}:\n" not in existing:
        existing += f"  {name}:\n    image: x\n"
    if with_compose_volume and with_contract and f"\n  {name}_sock:\n" not in existing:
        if "volumes:\n" not in existing:
            existing += "volumes:\n"
        existing += f"  {name}_sock:\n"
    compose.write_text(existing, encoding="utf-8")
    return folder


class ContractPresenceHookTests(TestCase):

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.base = Path(self._tmp.name)
        self._original_root = hook.REPO_ROOT
        hook.REPO_ROOT = self.base

    def tearDown(self) -> None:
        hook.REPO_ROOT = self._original_root
        self._tmp.cleanup()

    def test_clean_service_has_no_violations(self) -> None:
        folder = _make_service(self.base, "streamd")
        violations = hook.scan_service_folder(folder)
        self.assertEqual(violations, [], f"unexpected: {[v.kind for v in violations]}")

    def test_missing_contract_is_flagged(self) -> None:
        folder = _make_service(self.base, "streamd", with_contract=False)
        kinds = {v.kind for v in hook.scan_service_folder(folder)}
        self.assertIn("contract", kinds)

    def test_missing_binary_is_library_only_loophole(self) -> None:
        folder = _make_service(self.base, "streamd", with_binary=False)
        violations = hook.scan_service_folder(folder)
        kinds = {v.kind for v in violations}
        self.assertIn("binary", kinds)
        msg = " | ".join(v.message for v in violations)
        self.assertIn("cmd/streamd/main.go", msg)
        self.assertIn("library-only", msg.lower())

    def test_missing_dockerfile_is_flagged(self) -> None:
        folder = _make_service(self.base, "streamd", with_dockerfile=False)
        kinds = {v.kind for v in hook.scan_service_folder(folder)}
        self.assertIn("dockerfile", kinds)

    def test_single_stage_dockerfile_is_flagged(self) -> None:
        folder = _make_service(self.base, "streamd", multi_stage_dockerfile=False)
        violations = hook.scan_service_folder(folder)
        kinds = {v.kind for v in violations}
        self.assertIn("dockerfile-shape", kinds)
        msg = " | ".join(v.message for v in violations)
        self.assertIn("single-stage", msg)

    def test_missing_generated_stubs_is_flagged(self) -> None:
        folder = _make_service(self.base, "streamd", with_stubs=False)
        kinds = {v.kind for v in hook.scan_service_folder(folder)}
        self.assertIn("stubs", kinds)

    def test_missing_compose_entry_is_flagged(self) -> None:
        folder = _make_service(self.base, "streamd", with_compose=False)
        kinds = {v.kind for v in hook.scan_service_folder(folder)}
        self.assertIn("compose", kinds)

    def test_missing_compose_volume_is_flagged_for_grpc(self) -> None:
        folder = _make_service(self.base, "streamd", with_compose_volume=False)
        violations = hook.scan_service_folder(folder)
        kinds = {v.kind for v in violations}
        self.assertIn("compose-volume", kinds)
        msg = " | ".join(v.message for v in violations)
        self.assertIn("streamd_sock", msg)

    def test_missing_compose_volume_is_exempt_for_http_only(self) -> None:
        """A service publishing api.http.md (HTTP+JSON) is exempt from the
        Unix-socket named-volume check."""
        folder = _make_service(
            self.base,
            "webhookd",
            with_contract=False,
            with_stubs=False,
            with_compose_volume=False,
        )
        (folder / "api.http.md").write_text("# webhookd HTTP contract\n", encoding="utf-8")
        kinds = {v.kind for v in hook.scan_service_folder(folder)}
        self.assertNotIn("compose-volume", kinds)

    def test_missing_go_sum_is_flagged_when_requires_exist(self) -> None:
        folder = _make_service(self.base, "streamd", with_go_sum=False)
        violations = hook.scan_service_folder(folder)
        kinds = {v.kind for v in violations}
        self.assertIn("go-sum", kinds)
        msg = " | ".join(v.message for v in violations)
        self.assertIn("go mod tidy", msg)

    def test_missing_go_sum_is_exempt_when_no_requires(self) -> None:
        folder = _make_service(
            self.base,
            "streamd",
            with_go_sum=False,
            gomod_has_requires=False,
        )
        kinds = {v.kind for v in hook.scan_service_folder(folder)}
        self.assertNotIn("go-sum", kinds)

    def test_http_contract_does_not_require_pb_go_stubs(self) -> None:
        folder = _make_service(
            self.base, "webhookd", with_contract=False, with_stubs=False,
        )
        (folder / "api.http.md").write_text("# webhookd HTTP contract\n", encoding="utf-8")
        kinds = {v.kind for v in hook.scan_service_folder(folder)}
        self.assertNotIn("stubs", kinds)
        self.assertNotIn("contract", kinds)

    def test_both_missing_is_two_violations_naming_both(self) -> None:
        folder = _make_service(
            self.base, "streamd", with_contract=False, with_binary=False
        )
        violations = hook.scan_service_folder(folder)
        kinds = {v.kind for v in violations}
        self.assertIn("contract", kinds)
        self.assertIn("binary", kinds)
        joined = " | ".join(v.message for v in violations)
        self.assertIn("api.proto", joined)
        self.assertIn("cmd/streamd/main.go", joined)

    def test_empty_services_dir_is_clean(self) -> None:
        (self.base / "services").mkdir()
        self.assertEqual(hook.scan_base_dir(self.base), [])

    def test_missing_services_dir_is_clean(self) -> None:
        self.assertEqual(hook.scan_base_dir(self.base), [])

    def test_scan_base_dir_aggregates_violations_across_services(self) -> None:
        _make_service(self.base, "streamd")
        _make_service(self.base, "webhookd", with_contract=False, with_stubs=False)
        _make_service(
            self.base, "crawld", with_contract=False, with_binary=False, with_stubs=False
        )
        violations = hook.scan_base_dir(self.base)
        self.assertGreaterEqual(len(violations), 3)

    def test_format_failure_includes_three_part_message(self) -> None:
        v = hook.Violation(
            service="streamd",
            kind="contract",
            message="services/streamd/ is missing both api.proto and api.http.md",
        )
        text = hook._format_failure([v])
        self.assertIn("FAIL check-go-service-contract", text)
        self.assertIn("WHY:", text)
        self.assertIn("UNBLOCK:", text)
        self.assertIn("ADR 0006", text)
        self.assertIn("library-only", text.lower())

    def test_main_returns_zero_when_no_services_folder(self) -> None:
        original = hook.SERVICES_DIR
        try:
            with tempfile.TemporaryDirectory() as tmp:
                hook.SERVICES_DIR = Path(tmp) / "no-such-services"  # type: ignore[assignment]
                self.assertEqual(hook.main(), 0)
        finally:
            hook.SERVICES_DIR = original  # type: ignore[assignment]

    def test_main_returns_two_on_violations(self) -> None:
        original = hook.SERVICES_DIR
        try:
            with tempfile.TemporaryDirectory() as tmp:
                base = Path(tmp)
                _make_service(base, "broken", with_contract=False, with_binary=False)
                hook.SERVICES_DIR = base / "services"  # type: ignore[assignment]
                hook.REPO_ROOT = base
                self.assertEqual(hook.main(), 2)
        finally:
            hook.SERVICES_DIR = original  # type: ignore[assignment]


class MultiServiceFolderTests(TestCase):
    """Slice 1.6 — Rule K accepts a multi-service folder (services.manifest.yaml
    + api/*.proto) as a substitute for the single top-level api.proto."""

    def _make_multi_service(
        self,
        base: Path,
        name: str = "sidecars",
        *,
        with_manifest: bool = True,
        with_api_dir: bool = True,
        with_proto_files: bool = True,
        with_stubs: bool = True,
        with_binary: bool = True,
        with_dockerfile: bool = True,
        with_compose: bool = True,
        with_compose_volume: bool = True,
        with_go_sum: bool = True,
    ) -> Path:
        folder = base / "services" / name
        folder.mkdir(parents=True, exist_ok=True)
        # go.mod with deps
        (folder / "go.mod").write_text(
            f"module xf-internal-linker-v2/services/{name}\n\n"
            "go 1.25\n\n"
            "require (\n"
            "    google.golang.org/grpc v1.66.0\n"
            ")\n"
        )
        if with_go_sum:
            (folder / "go.sum").write_text("google.golang.org/grpc v1.66.0 h1:abcd\n")
        if with_manifest:
            (folder / "services.manifest.yaml").write_text(
                "host:\n  total_memory_mb: 512\n  total_storage_mb: 1024\n  retention_hours: 168\n"
                "  socket_path: /var/run/x/x.sock\n  storage_path: /var/lib/x\n"
                "services:\n"
                "  - name: foo\n    apache: Test\n    owning_module: platform\n    priority: high\n"
                "    rpcs:\n      - {name: Ping, in: Empty, out: Ack, streaming: none}\n"
            )
        if with_api_dir:
            api_dir = folder / "api"
            api_dir.mkdir(exist_ok=True)
            if with_proto_files:
                (api_dir / "foo.proto").write_text('syntax = "proto3";\npackage x;\n')
                (api_dir / "shared.proto").write_text('syntax = "proto3";\npackage x;\n')
            if with_stubs:
                gen = api_dir / "gen"
                gen.mkdir(exist_ok=True)
                (gen / "foo.pb.go").write_text("package gen\n")
                (gen / "shared.pb.go").write_text("package gen\n")
        if with_binary:
            cmd = folder / "cmd" / name
            cmd.mkdir(parents=True, exist_ok=True)
            (cmd / "main.go").write_text("package main\nfunc main() {}\n")
        if with_dockerfile:
            (folder / "Dockerfile").write_text(_MULTI_STAGE_DOCKERFILE)
        # docker-compose snippet
        compose_blocks: list[str] = []
        if with_compose:
            compose_blocks.append(f"  {name}:\n    image: {name}:latest\n")
        if with_compose_volume:
            compose_blocks.append(f"  {name}_sock:\n    driver: local\n")
        (base / "docker-compose.yml").write_text("services:\n" + "".join(compose_blocks) + "\nvolumes:\n")
        return folder

    def test_multi_service_folder_with_everything_passes(self) -> None:
        original_root = hook.REPO_ROOT
        try:
            with tempfile.TemporaryDirectory() as tmp:
                base = Path(tmp)
                self._make_multi_service(base)
                hook.REPO_ROOT = base  # type: ignore[assignment]
                violations = hook.scan_base_dir(base)
                self.assertEqual(violations, [], f"expected zero violations, got {violations}")
        finally:
            hook.REPO_ROOT = original_root  # type: ignore[assignment]

    def test_multi_service_missing_stub_files_fails(self) -> None:
        original_root = hook.REPO_ROOT
        try:
            with tempfile.TemporaryDirectory() as tmp:
                base = Path(tmp)
                self._make_multi_service(base, with_stubs=False)
                hook.REPO_ROOT = base  # type: ignore[assignment]
                violations = hook.scan_base_dir(base)
                kinds = [v.kind for v in violations]
                self.assertIn("multi-service-stubs", kinds)
        finally:
            hook.REPO_ROOT = original_root  # type: ignore[assignment]

    def test_multi_service_missing_binary_fails(self) -> None:
        original_root = hook.REPO_ROOT
        try:
            with tempfile.TemporaryDirectory() as tmp:
                base = Path(tmp)
                self._make_multi_service(base, with_binary=False)
                hook.REPO_ROOT = base  # type: ignore[assignment]
                violations = hook.scan_base_dir(base)
                kinds = [v.kind for v in violations]
                self.assertIn("binary", kinds)
        finally:
            hook.REPO_ROOT = original_root  # type: ignore[assignment]

    def test_multi_service_still_requires_compose_named_volume(self) -> None:
        original_root = hook.REPO_ROOT
        try:
            with tempfile.TemporaryDirectory() as tmp:
                base = Path(tmp)
                self._make_multi_service(base, with_compose_volume=False)
                hook.REPO_ROOT = base  # type: ignore[assignment]
                violations = hook.scan_base_dir(base)
                kinds = [v.kind for v in violations]
                self.assertIn("compose-volume", kinds)
        finally:
            hook.REPO_ROOT = original_root  # type: ignore[assignment]

    def test_is_multi_service_detector(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            ms = self._make_multi_service(base)
            self.assertTrue(hook._is_multi_service_folder(ms))
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp)
            ms = self._make_multi_service(base, with_manifest=False)
            self.assertFalse(hook._is_multi_service_folder(ms))


if __name__ == "__main__":
    import unittest

    unittest.main()
