# Generated by Django 5.2 on 2026-04-09 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0016_alter_contentitem_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('site_domain', models.CharField(help_text="Domain being crawled (e.g. 'goldmidi.com').", max_length=255)),
                ('config', models.JSONField(default=dict, help_text='Crawl settings frozen at start: rate_limit, max_depth, max_pages, excluded_paths, timeout_hours.')),
                ('pages_crawled', models.IntegerField(default=0)),
                ('pages_changed', models.IntegerField(default=0, help_text='Pages whose content differed from last crawl.')),
                ('pages_skipped_304', models.IntegerField(default=0, help_text='Pages that returned 304 Not Modified.')),
                ('new_pages_discovered', models.IntegerField(default=0, help_text='Pages found that had no prior crawl record.')),
                ('broken_links_found', models.IntegerField(default=0)),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('elapsed_seconds', models.FloatField(default=0.0)),
                ('progress', models.FloatField(default=0.0, help_text='Overall crawl progress 0.0-1.0.')),
                ('message', models.CharField(blank=True, max_length=500)),
                ('checkpoint_frontier_key', models.CharField(blank=True, help_text='Redis key holding the serialised URL frontier for resume.', max_length=200)),
                ('is_resumable', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Crawl Session',
                'verbose_name_plural': 'Crawl Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SitemapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('domain', models.CharField(db_index=True, help_text="Domain this sitemap belongs to (e.g. 'goldmidi.com').", max_length=255)),
                ('sitemap_url', models.URLField(help_text="Full URL of the sitemap (e.g. 'https://goldmidi.com/community/sitemap.php').", max_length=2000)),
                ('normalized_url', models.CharField(help_text='Normalised URL for dedup (lowercase, no trailing slash).', max_length=2000, unique=True)),
                ('discovery_method', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto-discovered')], default='manual', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Disabled sitemaps are skipped during crawl.')),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('last_url_count', models.IntegerField(default=0, help_text='Number of URLs found in last fetch.')),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sitemap Configuration',
                'verbose_name_plural': 'Sitemap Configurations',
                'ordering': ['domain', 'sitemap_url'],
            },
        ),
        migrations.CreateModel(
            name='CrawledPageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('url', models.URLField(db_index=True, help_text='Canonical URL of the page.', max_length=2000)),
                ('normalized_url', models.CharField(db_index=True, help_text='URL after normalisation (lowercase host, strip fragment/trailing slash).', max_length=2000)),
                ('http_status', models.SmallIntegerField(default=200, help_text='HTTP response status code.')),
                ('response_time_ms', models.IntegerField(default=0, help_text='Time to first byte in milliseconds.')),
                ('redirect_chain', models.JSONField(default=list, help_text='List of (url, status) tuples if page redirected.')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('content_length', models.IntegerField(default=0, help_text='Response body size in bytes.')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True, max_length=2000)),
                ('robots_meta', models.CharField(blank=True, help_text="Content of <meta name='robots'> tag.", max_length=200)),
                ('has_viewport', models.BooleanField(default=False, help_text="True if <meta name='viewport'> is present.")),
                ('h1_text', models.CharField(blank=True, help_text='Text of the first <h1> tag.', max_length=500)),
                ('h1_count', models.SmallIntegerField(default=0, help_text='Number of <h1> tags on the page.')),
                ('heading_structure', models.JSONField(default=list, help_text="Ordered list of {'level': 1-6, 'text': '...'} for H1-H6.")),
                ('og_title', models.CharField(blank=True, max_length=500)),
                ('og_description', models.TextField(blank=True)),
                ('structured_data_types', models.JSONField(default=list, help_text='List of Schema.org @type values found in JSON-LD blocks.')),
                ('word_count', models.IntegerField(default=0, help_text='Word count of extracted main content.')),
                ('extracted_text', models.TextField(blank=True, help_text='Clean text extracted from main content area (no HTML).')),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 of extracted_text for change detection.', max_length=64)),
                ('content_to_html_ratio', models.FloatField(default=0.0, help_text='len(extracted_text) / len(raw_html). Low = boilerplate-heavy.')),
                ('img_total', models.IntegerField(default=0)),
                ('img_missing_alt', models.IntegerField(default=0, help_text='Images without alt attribute.')),
                ('internal_link_count', models.IntegerField(default=0)),
                ('external_link_count', models.IntegerField(default=0)),
                ('nofollow_link_count', models.IntegerField(default=0)),
                ('crawl_depth', models.SmallIntegerField(default=0, help_text='Minimum click distance from homepage.')),
                ('etag', models.CharField(blank=True, help_text='ETag header from last crawl (for conditional re-crawl).', max_length=200)),
                ('last_modified', models.CharField(blank=True, help_text='Last-Modified header from last crawl.', max_length=200)),
                ('consecutive_404_count', models.SmallIntegerField(default=0, help_text='Times this URL returned 404 in consecutive crawls. Auto-prune at 3.')),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawled_meta', to='content.contentitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='crawler.crawlsession')),
            ],
            options={
                'verbose_name': 'Crawled Page Metadata',
                'verbose_name_plural': 'Crawled Page Metadata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawledLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('destination_url', models.URLField(max_length=2000)),
                ('anchor_text', models.TextField(blank=True)),
                ('context_class', models.CharField(choices=[('content', 'Main Content'), ('nav', 'Navigation'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('breadcrumb', 'Breadcrumb'), ('unknown', 'Unknown')], default='content', help_text='Where on the page this link was found.', max_length=20)),
                ('is_nofollow', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='crawler.crawledpagemeta')),
            ],
            options={
                'verbose_name': 'Crawled Link',
                'verbose_name_plural': 'Crawled Links',
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=10)),
                ('source', models.CharField(choices=[('heartbeat', 'Heartbeat'), ('sync', 'Sync'), ('crawler', 'Crawler'), ('pipeline', 'Pipeline'), ('health', 'Health Check'), ('webhook', 'Webhook'), ('prune', 'Auto-Prune'), ('model', 'ML Model'), ('system', 'System')], db_index=True, default='system', max_length=20)),
                ('title', models.CharField(help_text='One-line plain-English description of what happened.', max_length=200)),
                ('detail', models.TextField(blank=True, help_text='Optional extra context (item counts, duration, etc.).')),
                ('metadata', models.JSONField(default=dict, help_text='Structured data for the event (e.g. items_count, duration_ms).')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'System Event',
                'verbose_name_plural': 'System Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'severity'], name='crawler_sys_timesta_3651cb_idx'), models.Index(fields=['source', '-timestamp'], name='crawler_sys_source_f27751_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='crawledpagemeta',
            index=models.Index(fields=['session', 'http_status'], name='crawler_cra_session_48cb30_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledpagemeta',
            index=models.Index(fields=['word_count'], name='crawler_cra_word_co_df9a85_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledpagemeta',
            index=models.Index(fields=['consecutive_404_count'], name='crawler_cra_consecu_7066fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='crawledpagemeta',
            constraint=models.UniqueConstraint(fields=('session', 'normalized_url'), name='unique_page_per_session'),
        ),
    ]
