# Generated by Django 5.2.13 on 2026-04-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlsession",
            name="frontier_snapshot",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Durable snapshot of the URL queue at the last safe pause. Each entry is {url, depth}. Persisted to the DB so we can resume even if Redis has been flushed.",
            ),
        ),
        migrations.AddField(
            model_name="crawlsession",
            name="scan_version",
            field=models.IntegerField(
                default=1,
                help_text="Monotonic counter incremented each time the crawl definition changes. Resume uses this to refuse mixing snapshots across versions.",
            ),
        ),
        migrations.AddField(
            model_name="crawlsession",
            name="visited_hashes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Stable hashes of URLs already crawled in this session. Prevents re-visiting on resume.",
            ),
        ),
    ]
