# Generated by Django 5.2 on 2026-03-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='description',
            field=models.TextField(blank=True, help_text='What this plugin does and what it adds to the app.'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Whether this plugin is currently active. Toggle without restart.'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='is_installed',
            field=models.BooleanField(default=False, help_text="Whether the plugin's files are present and loadable."),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra plugin metadata (author, homepage, requirements, etc.).'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='module_path',
            field=models.CharField(blank=True, help_text="Python module import path to the plugin entry point, e.g. 'plugins.wordpress_crosslinker.plugin'.", max_length=300),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(help_text="Human-readable plugin name, e.g. 'WordPress Cross-Linker'.", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='slug',
            field=models.SlugField(help_text="URL-safe identifier, e.g. 'wordpress-crosslinker'. Auto-generated from name.", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='version',
            field=models.CharField(default='1.0.0', help_text='Semantic version of this plugin.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pluginsetting',
            name='is_secret',
            field=models.BooleanField(default=False, help_text='If True, the value is masked in the admin UI.'),
        ),
        migrations.AlterField(
            model_name='pluginsetting',
            name='value_type',
            field=models.CharField(choices=[('str', 'Text'), ('int', 'Integer'), ('float', 'Decimal'), ('bool', 'True / False'), ('json', 'JSON')], default='str', help_text='Data type used to cast the value when reading.', max_length=20),
        ),
    ]
