# Generated by Django 5.2 on 2026-04-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_servicehealthrecord_issue_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehealthrecord',
            name='service_description',
            field=models.TextField(blank=True, help_text='Short description of what this service does.'),
        ),
        migrations.AddField(
            model_name='servicehealthrecord',
            name='service_name',
            field=models.CharField(blank=True, help_text="Human-readable name for the service (e.g. 'Google Analytics 4').", max_length=100),
        ),
    ]
