# Generated by Django 5.2 on 2026-04-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatoralert",
            name="suppressed_until",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, this alert is muted until this timestamp. Used by the dedup UI.",
                null=True,
            ),
        ),
    ]
