# Generated by Codex on 2026-05-21.

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentRepairAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_kind", models.CharField(db_index=True, max_length=24)),
                ("item_id", models.PositiveIntegerField(db_index=True)),
                ("item_key", models.CharField(db_index=True, max_length=64)),
                ("agent", models.CharField(db_index=True, max_length=80)),
                ("attempt_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("result", models.CharField(choices=[("started", "Started"), ("failed", "Failed"), ("blocked", "Blocked"), ("passed", "Passed")], db_index=True, max_length=16)),
                ("command", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("blocker", models.TextField(blank=True, default="")),
                ("next_action", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentWorkClaim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_kind", models.CharField(db_index=True, max_length=24)),
                ("item_id", models.PositiveIntegerField(db_index=True)),
                ("item_key", models.CharField(db_index=True, max_length=64)),
                ("agent", models.CharField(db_index=True, max_length=80)),
                ("status", models.CharField(choices=[("claimed", "Claimed"), ("conflicted", "Conflicted"), ("released", "Released"), ("completed", "Completed")], db_index=True, max_length=16)),
                ("affected_files", models.JSONField(blank=True, default=list)),
                ("conflict_reason", models.TextField(blank=True, default="")),
                ("claimed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("next_action", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="SelfHealingDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("latest_commit_sha", models.CharField(blank=True, default="", max_length=64)),
                ("latest_commit_author", models.CharField(blank=True, default="", max_length=160)),
                ("agent_authored", models.BooleanField(default=False)),
                ("backend_health", models.CharField(default="unknown", max_length=24)),
                ("frontend_health", models.CharField(default="unknown", max_length=24)),
                ("dirty_worktree", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("watching", "Watching"), ("blocked", "Blocked"), ("revert_recommended", "Revert recommended"), ("reverted", "Reverted"), ("manual_review", "Manual review")], db_index=True, max_length=32)),
                ("reason", models.TextField(blank=True, default="")),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SourceConfidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(max_length=64, unique=True)),
                ("trust_score", models.FloatField(default=0.5)),
                ("reason", models.TextField(blank=True, default="")),
                ("evidence_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["source"]},
        ),
        migrations.AddIndex(
            model_name="agentrepairattempt",
            index=models.Index(fields=["item_key", "agent", "attempt_fingerprint"], name="work_queue_item_ke_519e64_idx"),
        ),
        migrations.AddIndex(
            model_name="agentrepairattempt",
            index=models.Index(fields=["result", "created_at"], name="work_queue_result_8bc261_idx"),
        ),
        migrations.AddIndex(
            model_name="agentworkclaim",
            index=models.Index(fields=["item_kind", "item_id", "status"], name="work_queue_item_ki_11a19d_idx"),
        ),
        migrations.AddIndex(
            model_name="agentworkclaim",
            index=models.Index(fields=["agent", "status", "claimed_at"], name="work_queue_agent_381abc_idx"),
        ),
    ]

