# Generated by Django 5.2.14 on 2026-05-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_queue', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentrepairattempt',
            new_name='work_queue__item_ke_c93af9_idx',
            old_name='work_queue_item_ke_519e64_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrepairattempt',
            new_name='work_queue__result_70e9db_idx',
            old_name='work_queue_result_8bc261_idx',
        ),
        migrations.RenameIndex(
            model_name='agentworkclaim',
            new_name='work_queue__item_ki_ed98a2_idx',
            old_name='work_queue_item_ki_11a19d_idx',
        ),
        migrations.RenameIndex(
            model_name='agentworkclaim',
            new_name='work_queue__agent_efc037_idx',
            old_name='work_queue_agent_381abc_idx',
        ),
    ]
