# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import coordd_pb2 as coordd__pb2
from . import shared_pb2 as shared__pb2


class CoorddStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEphemeral = channel.unary_unary(
                '/xf.sidecars.v1.Coordd/CreateEphemeral',
                request_serializer=coordd__pb2.EphemeralRequest.SerializeToString,
                response_deserializer=coordd__pb2.NodeID.FromString,
                )
        self.Watch = channel.unary_stream(
                '/xf.sidecars.v1.Coordd/Watch',
                request_serializer=coordd__pb2.WatchRequest.SerializeToString,
                response_deserializer=coordd__pb2.WatchEvent.FromString,
                )
        self.Lock = channel.unary_unary(
                '/xf.sidecars.v1.Coordd/Lock',
                request_serializer=coordd__pb2.LockRequest.SerializeToString,
                response_deserializer=coordd__pb2.LockToken.FromString,
                )
        self.Unlock = channel.unary_unary(
                '/xf.sidecars.v1.Coordd/Unlock',
                request_serializer=coordd__pb2.UnlockRequest.SerializeToString,
                response_deserializer=shared__pb2.Ack.FromString,
                )
        self.Elect = channel.unary_stream(
                '/xf.sidecars.v1.Coordd/Elect',
                request_serializer=coordd__pb2.ElectRequest.SerializeToString,
                response_deserializer=coordd__pb2.LeaderEvent.FromString,
                )
        self.Discover = channel.unary_unary(
                '/xf.sidecars.v1.Coordd/Discover',
                request_serializer=coordd__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=coordd__pb2.ServiceList.FromString,
                )
        self.Health = channel.unary_unary(
                '/xf.sidecars.v1.Coordd/Health',
                request_serializer=shared__pb2.Empty.SerializeToString,
                response_deserializer=shared__pb2.HealthReply.FromString,
                )


class CoorddServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEphemeral(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Elect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoorddServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEphemeral': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEphemeral,
                    request_deserializer=coordd__pb2.EphemeralRequest.FromString,
                    response_serializer=coordd__pb2.NodeID.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=coordd__pb2.WatchRequest.FromString,
                    response_serializer=coordd__pb2.WatchEvent.SerializeToString,
            ),
            'Lock': grpc.unary_unary_rpc_method_handler(
                    servicer.Lock,
                    request_deserializer=coordd__pb2.LockRequest.FromString,
                    response_serializer=coordd__pb2.LockToken.SerializeToString,
            ),
            'Unlock': grpc.unary_unary_rpc_method_handler(
                    servicer.Unlock,
                    request_deserializer=coordd__pb2.UnlockRequest.FromString,
                    response_serializer=shared__pb2.Ack.SerializeToString,
            ),
            'Elect': grpc.unary_stream_rpc_method_handler(
                    servicer.Elect,
                    request_deserializer=coordd__pb2.ElectRequest.FromString,
                    response_serializer=coordd__pb2.LeaderEvent.SerializeToString,
            ),
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=coordd__pb2.DiscoverRequest.FromString,
                    response_serializer=coordd__pb2.ServiceList.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=shared__pb2.Empty.FromString,
                    response_serializer=shared__pb2.HealthReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xf.sidecars.v1.Coordd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Coordd(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEphemeral(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Coordd/CreateEphemeral',
            coordd__pb2.EphemeralRequest.SerializeToString,
            coordd__pb2.NodeID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/xf.sidecars.v1.Coordd/Watch',
            coordd__pb2.WatchRequest.SerializeToString,
            coordd__pb2.WatchEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Lock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Coordd/Lock',
            coordd__pb2.LockRequest.SerializeToString,
            coordd__pb2.LockToken.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Unlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Coordd/Unlock',
            coordd__pb2.UnlockRequest.SerializeToString,
            shared__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Elect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/xf.sidecars.v1.Coordd/Elect',
            coordd__pb2.ElectRequest.SerializeToString,
            coordd__pb2.LeaderEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Coordd/Discover',
            coordd__pb2.DiscoverRequest.SerializeToString,
            coordd__pb2.ServiceList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Coordd/Health',
            shared__pb2.Empty.SerializeToString,
            shared__pb2.HealthReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
