# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import errord_pb2 as errord__pb2
from . import shared_pb2 as shared__pb2


class ErrordStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPolicy = channel.unary_unary(
                '/xf.sidecars.v1.Errord/RegisterPolicy',
                request_serializer=errord__pb2.ErrorPolicy.SerializeToString,
                response_deserializer=errord__pb2.ErrorPolicy.FromString,
                )
        self.Handle = channel.unary_unary(
                '/xf.sidecars.v1.Errord/Handle',
                request_serializer=errord__pb2.HandleExceptionRequest.SerializeToString,
                response_deserializer=errord__pb2.HandleResult.FromString,
                )
        self.ListPolicies = channel.unary_unary(
                '/xf.sidecars.v1.Errord/ListPolicies',
                request_serializer=shared__pb2.Empty.SerializeToString,
                response_deserializer=errord__pb2.ErrorPolicyList.FromString,
                )
        self.Stats = channel.unary_unary(
                '/xf.sidecars.v1.Errord/Stats',
                request_serializer=shared__pb2.Empty.SerializeToString,
                response_deserializer=errord__pb2.ErrorStats.FromString,
                )
        self.Health = channel.unary_unary(
                '/xf.sidecars.v1.Errord/Health',
                request_serializer=shared__pb2.Empty.SerializeToString,
                response_deserializer=shared__pb2.HealthReply.FromString,
                )


class ErrordServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Handle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ErrordServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPolicy,
                    request_deserializer=errord__pb2.ErrorPolicy.FromString,
                    response_serializer=errord__pb2.ErrorPolicy.SerializeToString,
            ),
            'Handle': grpc.unary_unary_rpc_method_handler(
                    servicer.Handle,
                    request_deserializer=errord__pb2.HandleExceptionRequest.FromString,
                    response_serializer=errord__pb2.HandleResult.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=shared__pb2.Empty.FromString,
                    response_serializer=errord__pb2.ErrorPolicyList.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=shared__pb2.Empty.FromString,
                    response_serializer=errord__pb2.ErrorStats.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=shared__pb2.Empty.FromString,
                    response_serializer=shared__pb2.HealthReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xf.sidecars.v1.Errord', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Errord(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Errord/RegisterPolicy',
            errord__pb2.ErrorPolicy.SerializeToString,
            errord__pb2.ErrorPolicy.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Handle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Errord/Handle',
            errord__pb2.HandleExceptionRequest.SerializeToString,
            errord__pb2.HandleResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Errord/ListPolicies',
            shared__pb2.Empty.SerializeToString,
            errord__pb2.ErrorPolicyList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Errord/Stats',
            shared__pb2.Empty.SerializeToString,
            errord__pb2.ErrorStats.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Errord/Health',
            shared__pb2.Empty.SerializeToString,
            shared__pb2.HealthReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
