# Generated by Django 5.2 on 2026-04-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_lower_max_links_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelperNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the registration token. Never store the raw token.",
                        max_length=128,
                    ),
                ),
                ("role", models.CharField(default="worker", max_length=50)),
                (
                    "capabilities",
                    models.JSONField(
                        default=dict,
                        help_text='{"cpu_cores": 8, "ram_gb": 16, "gpu_vram_gb": 6, "network_quality": "good"}',
                    ),
                ),
                (
                    "allowed_queues",
                    models.JSONField(
                        default=list, help_text='["pipeline", "embeddings"]'
                    ),
                ),
                (
                    "allowed_job_types",
                    models.JSONField(
                        default=list, help_text='["sync", "pipeline", "embeddings"]'
                    ),
                ),
                (
                    "time_policy",
                    models.CharField(
                        choices=[
                            ("anytime", "Available anytime"),
                            ("nighttime", "Nighttime only (21:00–06:00 UTC)"),
                            ("maintenance", "Maintenance windows only"),
                        ],
                        default="anytime",
                        max_length=20,
                    ),
                ),
                ("max_concurrency", models.IntegerField(default=2)),
                (
                    "cpu_cap_pct",
                    models.IntegerField(
                        default=60,
                        help_text="Maximum CPU usage percentage (safety default: 60%).",
                    ),
                ),
                (
                    "ram_cap_pct",
                    models.IntegerField(
                        default=60,
                        help_text="Maximum RAM usage percentage (safety default: 60%).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        default="offline",
                        help_text="Current state: online, busy, unhealthy, offline.",
                        max_length=20,
                    ),
                ),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Helper Node",
                "verbose_name_plural": "Helper Nodes",
                "ordering": ["name"],
            },
        ),
    ]
