# Generated by Django 5.2.13 on 2026-04-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_helper_node"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuarantineRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. 'pipeline_run', 'sync_job', 'suggestion', 'crawl_session'.",
                        max_length=64,
                    ),
                ),
                (
                    "related_object_id",
                    models.CharField(
                        db_index=True,
                        help_text="Primary key or UUID of the quarantined object as a string.",
                        max_length=128,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("repeated_failure", "Repeated failures"),
                            ("bad_credentials", "Bad credentials"),
                            ("malformed_import", "Malformed import"),
                            ("stalled_crawl", "Stalled crawl"),
                            ("broken_warmup", "Broken warmup"),
                            ("duplicate_conflict", "Duplicate conflicting job"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="repeated_failure",
                        max_length=48,
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(
                        blank=True,
                        help_text="Plain-English extended explanation shown to the user.",
                    ),
                ),
                (
                    "affected_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["content_item:123", "sync_job:abc"] — items impacted beyond the primary.',
                    ),
                ),
                (
                    "fix_available",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Runbook id, e.g. 'reset-quarantined-job' or 'restart-stuck-pipeline'.",
                        max_length=128,
                    ),
                ),
                ("resume_from_checkpoint", models.BooleanField(default=False)),
                (
                    "checkpoint_id",
                    models.CharField(
                        blank=True,
                        help_text="Opaque checkpoint handle the worker can pick up at resume.",
                        max_length=128,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "resolved_by",
                    models.CharField(
                        blank=True,
                        help_text="'user', 'auto', or 'runbook:<id>' — who/what closed this.",
                        max_length=64,
                    ),
                ),
                ("resolved_note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Quarantine Record",
                "verbose_name_plural": "Quarantine Records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["related_object_type", "related_object_id"],
                        name="qrec_related_idx",
                    ),
                    models.Index(fields=["resolved_at"], name="qrec_resolved_idx"),
                ],
            },
        ),
    ]
