# Generated by Django 5.2.13 on 2026-04-17 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_featureflag_and_exposure'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('subject_type', models.CharField(db_index=True, max_length=64)),
                ('subject_id', models.CharField(blank=True, max_length=128)),
                ('actor', models.CharField(blank=True, max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Runtime Audit Log',
                'verbose_name_plural': 'Runtime Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='helpernode',
            name='accepting_work',
            field=models.BooleanField(default=True, help_text='Operator toggle that lets the helper stay healthy but stop taking work.'),
        ),
        migrations.AddField(
            model_name='helpernode',
            name='active_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='helpernode',
            name='cpu_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='helpernode',
            name='gpu_util_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpernode',
            name='gpu_vram_total_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpernode',
            name='gpu_vram_used_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpernode',
            name='last_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpernode',
            name='native_kernels_healthy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpernode',
            name='network_rtt_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpernode',
            name='queued_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='helpernode',
            name='ram_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='helpernode',
            name='warmed_model_keys',
            field=models.JSONField(default=list, help_text='["embedding:BAAI/bge-m3:fr020-v1"]'),
        ),
        migrations.CreateModel(
            name='HardwareCapabilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('node_kind', models.CharField(choices=[('primary', 'Primary'), ('helper', 'Helper')], db_index=True, default='primary', max_length=20)),
                ('cpu_cores', models.IntegerField(default=0)),
                ('ram_gb', models.FloatField(default=0.0)),
                ('gpu_name', models.CharField(blank=True, max_length=200)),
                ('gpu_vram_gb', models.FloatField(default=0.0)),
                ('disk_free_gb', models.FloatField(default=0.0)),
                ('native_kernels_healthy', models.BooleanField(default=False)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('detected_upgrade', models.BooleanField(default=False)),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hardware_snapshots', to='core.helpernode')),
            ],
            options={
                'verbose_name': 'Hardware Capability Snapshot',
                'verbose_name_plural': 'Hardware Capability Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('task_type', models.CharField(choices=[('embedding', 'Embedding'), ('spacy', 'spaCy'), ('helper', 'Helper')], db_index=True, default='embedding', max_length=32)),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('model_family', models.CharField(blank=True, max_length=100)),
                ('dimension', models.IntegerField(blank=True, null=True)),
                ('device_target', models.CharField(default='cpu', max_length=32)),
                ('batch_size', models.IntegerField(default=32)),
                ('memory_profile', models.JSONField(blank=True, default=dict)),
                ('role', models.CharField(choices=[('champion', 'Champion'), ('candidate', 'Candidate'), ('retired', 'Retired')], db_index=True, default='candidate', max_length=20)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('downloading', 'Downloading'), ('warming', 'Warming'), ('ready', 'Ready'), ('draining', 'Draining'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='registered', max_length=20)),
                ('health_result', models.JSONField(blank=True, default=dict)),
                ('algorithm_version', models.CharField(default='fr020-v1', max_length=64)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('draining_since', models.DateTimeField(blank=True, null=True)),
                ('last_warmup_result', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Runtime Model Registry',
                'verbose_name_plural': 'Runtime Model Registry',
                'ordering': ['task_type', '-promoted_at', 'model_name'],
                'constraints': [models.UniqueConstraint(fields=('task_type', 'model_name', 'algorithm_version'), name='runtime_model_unique_version')],
            },
        ),
        migrations.CreateModel(
            name='RuntimeModelPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('executor_type', models.CharField(choices=[('primary', 'Primary'), ('helper', 'Helper')], db_index=True, default='primary', max_length=20)),
                ('artifact_path', models.CharField(blank=True, max_length=500)),
                ('artifact_checksum', models.CharField(blank=True, max_length=128)),
                ('disk_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('downloading', 'Downloading'), ('warming', 'Warming'), ('ready', 'Ready'), ('draining', 'Draining'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='registered', max_length=20)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('warmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_placements', to='core.helpernode')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='core.runtimemodelregistry')),
            ],
            options={
                'verbose_name': 'Runtime Model Placement',
                'verbose_name_plural': 'Runtime Model Placements',
                'ordering': ['registry__task_type', 'executor_type', 'helper__name'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeModelBackfillPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('compatibility_status', models.CharField(default='compatible', max_length=32)),
                ('progress_pct', models.FloatField(default=0.0)),
                ('checkpoint', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('from_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfills_from', to='core.runtimemodelregistry')),
                ('to_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfills_to', to='core.runtimemodelregistry')),
            ],
            options={
                'verbose_name': 'Runtime Model Backfill Plan',
                'verbose_name_plural': 'Runtime Model Backfill Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
