# Generated by Django 5.2.13 on 2026-04-22 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_seed_default_embedding_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Most recent authenticated request from this user.",
                    ),
                ),
                (
                    "last_route",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL path of the most recent request (best-effort).",
                        max_length=200,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User this heartbeat belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User activity heartbeat",
                "verbose_name_plural": "User activity heartbeats",
            },
        ),
        migrations.CreateModel(
            name="PasskeyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("register", "Register"), ("login", "Login")],
                        max_length=20,
                    ),
                ),
                (
                    "challenge",
                    models.BinaryField(
                        help_text="Raw server-generated challenge bytes."
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Challenge expiry timestamp (typically 5 minutes from now).",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User the challenge was issued to. Null for anonymous login-begin (the user is identified by the credential they return).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["operation_type", "expires_at"],
                        name="pkch_op_expires_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PasskeyCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "credential_id",
                    models.BinaryField(
                        help_text="Raw credential-id bytes (opaque, unique per credential).",
                        unique=True,
                    ),
                ),
                (
                    "public_key",
                    models.BinaryField(
                        help_text="COSE-encoded public key used to verify login assertions."
                    ),
                ),
                (
                    "sign_count",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Monotonic counter — increments on each successful login.",
                    ),
                ),
                (
                    "transports",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated transport hints (usb,nfc,ble,internal,hybrid).",
                        max_length=200,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human label the user gave this credential at register time.",
                        max_length=100,
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "last_used_at"], name="pkc_user_used_idx"
                    )
                ],
            },
        ),
    ]
