# Generated by Django 5.2 on 2026-04-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20260429_0348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureFlag',
        ),
        migrations.DeleteModel(
            name='FeatureFlagExposure',
        ),
    ]
