# Generated by Django 5.2.13 on 2026-04-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_featureflag_delete_featureflagexposure'),
    ]

    def seed_weights(apps, schema_editor):
        AppSetting = apps.get_model("core", "AppSetting")
        weights = {
            "phrase_matching.fuzzy_match_weight": ("0.08", "Ranking"),
            "phrase_matching.jsd_boost_weight": ("0.10", "Ranking"),
            "phrase_matching.lexical_richness_weight": ("0.05", "Ranking"),
            "phrase_matching.phonetic_boost_weight": ("0.04", "Ranking"),
        }
        for key, (value, category) in weights.items():
            AppSetting.objects.get_or_create(
                key=key,
                defaults={"value": value, "category": category}
            )

    operations = [
        migrations.RunPython(seed_weights),
    ]
