# Generated by Django 5.2.14 on 2026-06-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_data_protection_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpernode',
            name='warmed_model_keys',
            field=models.JSONField(default=list, help_text='["embedding:text-embedding-3-small:fr020-v1"]'),
        ),
    ]
