# Generated by Django 5.2 on 2026-03-25 00:40

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_wordpress_scope_and_page_types"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contentmetricsnapshot",
            name="content_cms_ci_date_idx",
        ),
        migrations.RenameIndex(
            model_name="contentitem",
            new_name="content_con_content_6ed5ae_idx",
            old_name="content_ci_type_pagerank_idx",
        ),
        migrations.RenameIndex(
            model_name="contentitem",
            new_name="content_con_content_c1ae70_idx",
            old_name="content_ci_type_velocity_idx",
        ),
        migrations.RenameIndex(
            model_name="contentitem",
            new_name="content_con_is_dele_d37b4c_idx",
            old_name="content_ci_deleted_idx",
        ),
        migrations.RenameIndex(
            model_name="scopeitem",
            new_name="content_sco_scope_t_e5e6d9_idx",
            old_name="content_scopeitem_type_enabled_idx",
        ),
        migrations.RenameIndex(
            model_name="scopeitem",
            new_name="content_sco_silo_gr_4ca050_idx",
            old_name="content_scope_silo_0f7380_idx",
        ),
        migrations.RenameIndex(
            model_name="sentence",
            new_name="content_sen_content_47b688_idx",
            old_name="content_sentence_ci_pos_idx",
        ),
        migrations.RenameIndex(
            model_name="sentence",
            new_name="content_sen_word_po_7fb40d_idx",
            old_name="content_sentence_word_pos_idx",
        ),
        migrations.RenameIndex(
            model_name="silogroup",
            new_name="content_sil_display_f91c99_idx",
            old_name="content_silo_display_5ef460_idx",
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="content_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of the raw post body, used to detect edits.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="content_id",
            field=models.IntegerField(
                help_text="The original ID in XenForo or WordPress (not the local DB primary key)."
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="distill_method",
            field=models.CharField(
                choices=[
                    ("title_plus_body", "Title + Body"),
                    ("title_only", "Title Only"),
                ],
                default="title_plus_body",
                help_text="How the distilled_text was generated.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="distilled_text",
            field=models.TextField(
                blank=True,
                help_text="Compact topical summary: title + most information-dense sentences. Used for embedding.",
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="download_count",
            field=models.IntegerField(
                default=0, help_text="Download count for resources (0 for threads)."
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=384,
                help_text="384-dimension sentence embedding for semantic similarity search via pgvector.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="fetched_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last time this record was synced from the XenForo API.",
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="True if this content was deleted on the live forum (suggestions become stale).",
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="last_post_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the most recent reply was posted.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="pagerank_score",
            field=models.FloatField(
                db_index=True,
                default=0.0,
                help_text="PageRank authority score (higher = more linked-to). Recalculated after each sync.",
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="weighted_pagerank_score",
            field=models.FloatField(
                db_index=True,
                default=0.0,
                help_text="Weighted authority score based on edge prominence and context. Separate from standard PageRank.",
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="post_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the thread/resource was originally posted.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="reply_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of replies (threads) or reviews (resources).",
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Canonical URL of this content on the live forum.",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="velocity_score",
            field=models.FloatField(
                db_index=True,
                default=0.0,
                help_text="Recency/engagement velocity score. Higher = trending recently.",
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="xf_post_id",
            field=models.IntegerField(
                blank=True,
                help_text="XenForo post ID of the first post (for edit detection).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="xf_update_id",
            field=models.IntegerField(
                blank=True,
                help_text="XenForo update/version ID (used to detect edits without re-fetching body).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentmetricsnapshot",
            name="download_count",
            field=models.IntegerField(
                default=0, help_text="Download count at snapshot time (resources only)."
            ),
        ),
        migrations.AlterField(
            model_name="contentmetricsnapshot",
            name="import_job_id",
            field=models.CharField(
                help_text="Celery task ID of the import job that created this snapshot.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="clean_text",
            field=models.TextField(
                blank=True,
                help_text="Plain text after stripping BBCode tags and URLs. Used for sentence splitting.",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="last_edit_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When this post was last edited on the forum.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="word_count",
            field=models.IntegerField(
                default=0,
                help_text="Word count of clean_text. Pipeline scans first 600 words only.",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="xf_post_id",
            field=models.IntegerField(
                blank=True,
                help_text="XenForo post ID (for direct API lookups).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="xf_update_id",
            field=models.IntegerField(
                blank=True,
                help_text="XenForo update ID (used to check if post was edited).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scopeitem",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extra data from the XenForo API response (stored for reference).",
            ),
        ),
        migrations.AlterField(
            model_name="scopeitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent scope item (e.g. a sub-forum's parent forum).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="content.scopeitem",
            ),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=384,
                help_text="384-dimension sentence embedding. Used in stage-2 similarity ranking.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="end_char",
            field=models.IntegerField(
                help_text="Character offset where this sentence ends in clean_text."
            ),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="start_char",
            field=models.IntegerField(
                help_text="Character offset where this sentence starts in clean_text."
            ),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="word_position",
            field=models.IntegerField(
                default=0,
                help_text="Word offset of the sentence start in the post. Sentences with word_position > 600 are excluded from host scanning.",
            ),
        ),
        migrations.AddIndex(
            model_name="contentmetricsnapshot",
            index=models.Index(
                fields=["content_item", "-captured_at"],
                name="content_con_content_adc2df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["content_type", "weighted_pagerank_score"],
                name="content_con_content_c6fee7_idx",
            ),
        ),
    ]
