# Generated by Django 5.2 on 2026-03-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_remove_contentmetricsnapshot_content_cms_ci_date_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentitem",
            old_name="weighted_pagerank_score",
            new_name="march_2026_pagerank_score",
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="march_2026_pagerank_score",
            field=models.FloatField(
                db_index=True,
                default=0.0,
                help_text="March 2026 PageRank score based on edge prominence and context. Recalculated after each sync.",
                verbose_name="March 2026 PageRank",
            ),
        ),
        migrations.RemoveIndex(
            model_name="contentitem",
            name="content_con_content_c6fee7_idx",
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["content_type", "march_2026_pagerank_score"],
                name="content_con_content_b349d4_idx",
            ),
        ),
    ]
