# Generated by Django 5.2 on 2026-03-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_rename_weighted_pagerank_score_to_march_2026_pagerank_score"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contentitem",
            name="content_con_content_6ed5ae_idx",
        ),
        migrations.RemoveField(
            model_name="contentitem",
            name="pagerank_score",
        ),
    ]
