# Generated by Django 5.2 on 2026-04-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0014_fr014_near_duplicate_clustering"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="fact_density_score",
            field=models.FloatField(
                db_index=True,
                default=0.5,
                help_text="Fact density: ratio of fact-like sentences minus filler penalty. Min 120 words required; below that = neutral 0.5.",
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="multimedia_coverage_score",
            field=models.FloatField(
                db_index=True,
                default=0.5,
                help_text="Multimedia richness: 0.4*video + 0.35*image_density + 0.25*alt_text_ratio. 1.0 = optimal (video + images with alt text). 0.5 = neutral (text-only).",
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="search_intensity_score",
            field=models.FloatField(
                db_index=True,
                default=0.5,
                help_text="Recent (3-day) site-search impressions vs. 28-day baseline. Sigmoid: ratio 0.5x→0.2, 1.0x→0.5, 2.0x→0.8, 10x→1.0.",
            ),
        ),
    ]
