# Generated by Django 5.2 on 2026-04-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0015_add_multimedia_factdensity_searchintensity_scores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentitem",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("thread", "Forum Thread"),
                    ("resource", "Resource"),
                    ("wp_post", "WordPress Post"),
                    ("wp_page", "WordPress Page"),
                    ("crawled_page", "Crawled Page"),
                ],
                help_text="Whether this is a forum thread, resource, or WordPress content item.",
                max_length=30,
            ),
        ),
    ]
