# Generated by Django 5.2 on 2026-04-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0017_contentitem_engagement_quality_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="canonical_url_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="History of URL/slug changes: [{url, changed_at}]. Never creates a new record on URL change.",
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="content_version",
            field=models.IntegerField(
                default=1,
                help_text="Monotonically increasing version number. Bumped when content_hash changes.",
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="source_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stable compound key: source:object_type:remote_id (e.g. xenforo:thread:123).",
                max_length=200,
            ),
        ),
    ]
