# Generated by Django 5.2.13 on 2026-04-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0018_add_content_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="last_checked_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp of the most recent re-import/recrawl touch, regardless of whether the content actually changed. Updated on every 'mark as checked' short-circuit (plan item 21) so operators can see that the item was verified without re-embedding.",
                null=True,
            ),
        ),
    ]
