# Generated by Django 5.2.13 on 2026-04-14 22:51

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0019_contentitem_last_checked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="embedding_model_version",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Model + preprocessing version that produced the current embedding. Used by the superseded-embedding retention policy (plan item 20) to keep rollback copies when the model changes.",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="SupersededEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1024,
                        help_text="The old 1024-dim vector that was replaced.",
                        null=True,
                    ),
                ),
                (
                    "embedding_model_version",
                    models.CharField(
                        blank=True,
                        help_text="Model + preprocessing version that produced this archived vector.",
                        max_length=64,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        help_text="Content hash at the time this embedding was produced.",
                        max_length=64,
                    ),
                ),
                (
                    "content_version",
                    models.IntegerField(
                        default=1,
                        help_text="ContentItem.content_version at the time of archival.",
                    ),
                ),
                (
                    "superseded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this embedding was replaced.",
                    ),
                ),
                (
                    "replacement_verified_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the replacement was verified as correct. The retention pruner only deletes archived rows whose replacement has been verified.",
                        null=True,
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        help_text="The content item whose embedding was replaced.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="superseded_embeddings",
                        to="content.contentitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Superseded Embedding",
                "verbose_name_plural": "Superseded Embeddings",
                "ordering": ["-superseded_at"],
                "indexes": [
                    models.Index(
                        fields=["content_item", "-superseded_at"],
                        name="content_sup_content_4c6214_idx",
                    ),
                    models.Index(
                        fields=["superseded_at", "replacement_verified_at"],
                        name="content_sup_superse_6de9a2_idx",
                    ),
                ],
            },
        ),
    ]
