# Generated by Django 5.2.13 on 2026-04-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0020_contentitem_embedding_model_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentitem",
            name="content_value_score",
            field=models.FloatField(
                db_index=True,
                default=0.5,
                help_text="GA4 + Matomo + GSC composite score for linking value. 0.5 = neutral (no activity in the lookback window). Written by analytics.sync._refresh_content_value_scores via the pure formula compute_content_value_raw. Phase 3a extension credits dwell-60s reach and penalises quick-exit rate per Kim et al. WSDM 2014 — both new terms are zero when Phase 2 telemetry is unavailable, so pre-Phase 3a sites see no behaviour change.",
            ),
        ),
    ]
