# Generated by Django 5.2.13 on 2026-04-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0021_content_value_score_help_text_phase3a"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentitem",
            name="engagement_quality_score",
            field=models.FloatField(
                db_index=True,
                default=0.5,
                help_text="GA4 engagement quality: 0.50*engaged_session_rate + 0.30*normalized_avg_engagement_time + 0.20*inverse_bounce_rate. Phase 3b extension adds a bounded +0.05*dwell_60s_rate credit and a -0.05*quick_exit_rate penalty (Kim et al. WSDM 2014). Final result clamped to [0.0, 1.0]. 0.5 = neutral (no data). Phase 2 terms are zero when their source columns are zero, so pre-Phase-2 sites see no behaviour change. Written by analytics sync layer.",
            ),
        ),
    ]
