# Generated by Django 5.2.13 on 2026-04-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0022_engagement_quality_help_text_phase3b"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentitem",
            name="content_value_score",
            field=models.FloatField(
                db_index=True,
                default=0.5,
                help_text="GA4 + Matomo + GSC composite score for linking value. 0.5 = neutral (no activity in the lookback window). Written by analytics.sync._refresh_content_value_scores via the pure formula compute_content_value_raw. Phase 3a/3c extension credits the dwell gradient (half-weight dwell-30s + full-weight dwell-60s) and penalises quick-exit rate per Kim et al. WSDM 2014 — all three terms are zero when Phase 2 telemetry is unavailable, so pre-Phase 3a sites see no behaviour change.",
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="engagement_quality_score",
            field=models.FloatField(
                db_index=True,
                default=0.5,
                help_text="GA4 engagement quality: 0.50*engaged_session_rate + 0.30*normalized_avg_engagement_time + 0.20*inverse_bounce_rate. Phase 3b/3c extension adds bounded +0.025*dwell_30s_rate and +0.05*dwell_60s_rate credits and a -0.05*quick_exit_rate penalty (Kim et al. WSDM 2014). Final result clamped to [0.0, 1.0]. 0.5 = neutral (no data). Phase 2 terms are zero when their source columns are zero, so pre-Phase-2 sites see no behaviour change. Written by analytics sync layer.",
            ),
        ),
    ]
