# Generated by Django 5.2.13 on 2026-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0023_phase3c_dwell_30s_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="content_value_diagnostics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tier 2 slice 5 — per-term breakdown of compute_content_value_raw captured during _refresh_content_value_scores so the suggestion-detail dialog can show operators exactly which signal drove the composite. Kim et al. WSDM 2014 formula, not a new signal.",
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="engagement_quality_diagnostics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tier 2 slice 5 — per-term breakdown of _compute_engagement_raw_score captured during _refresh_engagement_quality_scores. Same shape as content_value_diagnostics.",
            ),
        ),
    ]
