# Generated by Django 5.2.13 on 2026-04-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_contentitem_salient_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='passages',
            field=models.JSONField(blank=True, default=list, help_text='Sentence-aligned passages (Callan 1994 fixed-window with overlap, ~150 tokens). Each entry: {index, text, token_count, token_start, token_end}. Populated at import from the same Sentence rows used for retrieval — no duplicate splitting work.'),
        ),
    ]
