# Generated by Django 5.2 on 2026-04-28 22:11

from django.db import migrations


def mark_for_rechunk(apps, schema_editor):
    ContentItem = apps.get_model('content', 'ContentItem')
    # Clearing passage_embeddings forces the pipeline to re-segment the text
    # with the new 25% overlap window on its next pass.
    ContentItem.objects.exclude(passage_embeddings__isnull=True).update(passage_embeddings=None)

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_opq_codebook_and_fields'),
    ]

    operations = [
        migrations.RunPython(mark_for_rechunk, migrations.RunPython.noop),
    ]
