# Generated by Django 5.2 on 2026-04-28 22:11

from django.db import migrations


def mark_for_rechunk(apps, schema_editor):
    PassageEmbedding = apps.get_model("content", "PassageEmbedding")
    # Deleting PassageEmbedding rows forces the pipeline to re-segment the text
    # with the new 25% overlap window on its next pass.
    PassageEmbedding.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0037_opq_codebook_and_fields"),
    ]

    operations = [
        migrations.RunPython(mark_for_rechunk, migrations.RunPython.noop),
    ]
