# Generated by Django 5.2.13 on 2026-04-30 17:29

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0039_contentitem_nlp_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="char_ngram_vector",
            field=pgvector.django.VectorField(
                blank=True,
                dimensions=256,
                help_text="Pick #58: 256-dim hashed character n-gram (3-5) vector. Null until first NLP enrichment pass.",
                null=True,
            ),
        ),
    ]
