"""Registry of all 23 scoring and value signals for the Algorithm Weights Diagnostic Tab.

This registry maps signal IDs to their human-readable names, describing their
purpose, and identifying their data persistence (database tables) and
acceleration status (C++ kernels).
"""

from dataclasses import dataclass
from typing import Literal

SignalType = Literal["ranking", "value"]


@dataclass(frozen=True)
class SignalDefinition:
    id: str
    name: str
    type: SignalType
    description: str
    table_name: str
    cpp_kernel: str | None = None
    weight_key: str | None = None


SIGNALS: list[SignalDefinition] = [
    # --- RANKING SIGNALS (16) ---
    SignalDefinition(
        id="semantic_similarity",
        name="Semantic Similarity",
        type="ranking",
        description="Cosine similarity between sentence and destination embeddings (BGE-M3).",
        table_name="content_sentence (embedding), content_contentitem (embedding)",
        cpp_kernel="simsearch.score_and_topk",
        weight_key="w_semantic",
    ),
    SignalDefinition(
        id="keyword_jaccard",
        name="Keyword Jaccard",
        type="ranking",
        description="Overlapping token similarity ratio after stopword removal.",
        table_name="content_sentence (tokens), content_contentitem (tokens)",
        cpp_kernel="texttok.tokenize_text_batch",
        weight_key="w_keyword",
    ),
    SignalDefinition(
        id="node_proximity",
        name="Node Proximity (Affinity)",
        type="ranking",
        description="Scope tree distance (same category, parent, or grandparent).",
        table_name="content_scope",
        weight_key="w_node",
    ),
    SignalDefinition(
        id="post_quality",
        name="Post Quality (Host Auth)",
        type="ranking",
        description="Weighted PageRank of the host page providing the link.",
        table_name="content_contentitem (march_2026_pagerank_score)",
        cpp_kernel="pagerank.pagerank_step",
        weight_key="w_quality",
    ),
    SignalDefinition(
        id="weighted_authority",
        name="Weighted Authority (Dest Auth)",
        type="ranking",
        description="Weighted PageRank of the destination page receiving the link.",
        table_name="content_contentitem (march_2026_pagerank_score)",
        cpp_kernel="pagerank.pagerank_step",
        weight_key="weighted_authority.ranking_weight",
    ),
    SignalDefinition(
        id="link_freshness",
        name="Link Freshness (Velocity)",
        type="ranking",
        description="Decay-adjusted score based on time since last update or reply.",
        table_name="content_contentitem (link_freshness_score)",
        weight_key="link_freshness.ranking_weight",
    ),
    SignalDefinition(
        id="phrase_match",
        name="Phrase Match",
        type="ranking",
        description="Detection of destination title fragments within host sentences.",
        table_name="content_contentitem (title)",
        cpp_kernel="phrasematch.longest_contiguous_overlap",
        weight_key="phrase_matching.ranking_weight",
    ),
    SignalDefinition(
        id="learned_anchor",
        name="Learned Anchor",
        type="ranking",
        description="Corroboration against existing human-created anchor text.",
        table_name="graph_existinglink (anchor_text)",
        weight_key="learned_anchor.ranking_weight",
    ),
    SignalDefinition(
        id="rare_term_propagation",
        name="Rare-Term Propagation",
        type="ranking",
        description="Keyword boost for low-frequency relevant terms across silos.",
        table_name="content_contentitem (tokens)",
        cpp_kernel="rareterm.evaluate_rare_terms",
        weight_key="rare_term_propagation.ranking_weight",
    ),
    SignalDefinition(
        id="field_aware_relevance",
        name="Field-Aware Relevance",
        type="ranking",
        description="Separate weights for title, body, and scope-field matches.",
        table_name="content_contentitem, content_scope",
        cpp_kernel="fieldrel.score_field_tokens",
        weight_key="field_aware_relevance.ranking_weight",
    ),
    SignalDefinition(
        id="search_demand",
        name="GA4/GSC Search Demand",
        type="ranking",
        description="Search impression and click signals from Google Search Console.",
        table_name="analytics_searchmetric",
        weight_key="ga4_gsc.ranking_weight",
    ),
    SignalDefinition(
        id="click_distance",
        name="Click Distance",
        type="ranking",
        description="Graph-crawl shortest path distance between host and destination.",
        table_name="graph_clickdistance",
        weight_key="click_distance.ranking_weight",
    ),
    SignalDefinition(
        id="silo_affinity",
        name="Silo Affinity",
        type="ranking",
        description="Additive boost for same-silo pairs or penalty for cross-silo.",
        table_name="content_scope (silo_group_id)",
        weight_key="silo.mode",
    ),
    SignalDefinition(
        id="cluster_suppression",
        name="Cluster Suppression",
        type="ranking",
        description="Penalty for near-duplicate pages within the same semantic cluster.",
        table_name="content_contentitem (cluster_id)",
        weight_key="clustering.enabled",
    ),
    SignalDefinition(
        id="slate_diversity",
        name="Slate Diversity (MMR)",
        type="ranking",
        description="Maximal Marginal Relevance to prevent repetitive suggestion slates.",
        table_name="None (Runtime Rerank)",
        cpp_kernel="feedrerank.calculate_mmr_scores_batch",
        weight_key="slate_diversity.enabled",
    ),
    SignalDefinition(
        id="feedback_rerank",
        name="Feedback (Explore/Exploit)",
        type="ranking",
        description="Thompson Sampling based on operator acceptance/rejection history.",
        table_name="suggestions_suggestion (status)",
        weight_key="feedback_rerank.enabled",
    ),
    # --- VALUE MODEL SIGNALS (7) ---
    SignalDefinition(
        id="value_relevance",
        name="Value: Relevance",
        type="value",
        description="Destination topical alignment with the global corpus average.",
        table_name="content_contentitem (embedding)",
        weight_key="value_model.w_relevance",
    ),
    SignalDefinition(
        id="value_traffic",
        name="Value: Traffic",
        type="value",
        description="Historical view counts and session volume from GA4.",
        table_name="analytics_suggestiontelemetrydaily (destination_views)",
        weight_key="value_model.w_traffic",
    ),
    SignalDefinition(
        id="value_freshness",
        name="Value: Freshness",
        type="value",
        description="Link freshness score used as a value-model component.",
        table_name="content_contentitem (link_freshness_score)",
        weight_key="value_model.w_freshness",
    ),
    SignalDefinition(
        id="value_authority",
        name="Value: Authority",
        type="value",
        description="PageRank authority used as a value-model component.",
        table_name="content_contentitem (march_2026_pagerank_score)",
        weight_key="value_model.w_authority",
    ),
    SignalDefinition(
        id="value_engagement",
        name="Value: Engagement",
        type="value",
        description="Average engagement time and interaction rates from GA4.",
        table_name="analytics_suggestiontelemetrydaily (total_engagement_time_seconds)",
        weight_key="value_model.w_engagement",
    ),
    SignalDefinition(
        id="value_cooccurrence",
        name="Value: Co-occurrence",
        type="value",
        description="Session-level page co-viewing patterns (collaborative filtering).",
        table_name="cooccurrence_sessioncooccurrencepair",
        weight_key="value_model.w_cooccurrence",
    ),
    SignalDefinition(
        id="value_penalty",
        name="Value: Penalty",
        type="value",
        description="Blocklist and content-type suppression penalties.",
        table_name="None (Dynamic)",
        weight_key="value_model.w_penalty",
    ),
    # --- FUTURE SIGNALS (BACKLOG) ---
    # These placeholders are documented in FEATURE-REQUESTS.md.
    # Uncomment and adjust metadata as each signal's backend is implemented.
    # SignalDefinition(
    #     id="information_gain",
    #     name="Information Gain (Novelty)",
    #     type="ranking",
    #     description="FR-038: Measure of topical novelty compared to source page.",
    #     table_name="suggestions_suggestion (score_information_gain)",
    #     weight_key="information_gain.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="entity_salience",
    #     name="Entity Salience Match",
    #     type="ranking",
    #     description="FR-039: Alignment with source page salient terms.",
    #     table_name="suggestions_suggestion (score_entity_salience_match)",
    #     weight_key="entity_salience.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="multimedia_boost",
    #     name="Multimedia Richness",
    #     type="value",
    #     description="FR-040: Visual richness (video, image coverage, alt text).",
    #     table_name="content_contentitem (multimedia_metadata)",
    #     weight_key="value_model.w_multimedia",
    # ),
    # SignalDefinition(
    #     id="originality_provenance",
    #     name="Originality Provenance",
    #     type="ranking",
    #     description="FR-041: Bias toward earliest version in lexical clusters.",
    #     table_name="content_contentitem (source_published_at)",
    #     weight_key="originality_provenance.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="fact_density",
    #     name="Fact Density Scoring",
    #     type="ranking",
    #     description="FR-042: Concrete information density per word count.",
    #     table_name="suggestions_suggestion (score_fact_density)",
    #     weight_key="fact_density.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="semantic_drift",
    #     name="Semantic Drift Penalty",
    #     type="ranking",
    #     description="FR-043: Penalty for documents that lose focus over time.",
    #     table_name="suggestions_suggestion (score_semantic_drift_penalty)",
    #     weight_key="semantic_drift.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="search_intensity",
    #     name="Search Intensity Signal",
    #     type="ranking",
    #     description="FR-044: Real-time internal site-search demand.",
    #     table_name="analytics_searchmetric (internal_search_demand)",
    #     weight_key="internal_search.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="anchor_diversity",
    #     name="Anchor Diversity Guard",
    #     type="ranking",
    #     description="FR-045: Exact-match phrase repetition guard.",
    #     table_name="suggestions_suggestion (score_anchor_diversity)",
    #     weight_key="anchor_diversity.ranking_weight",
    # ),
    # --- PATENT-BACKED RANKING SIGNALS (FR-051 to FR-059) ---
    # SignalDefinition(
    #     id="reference_context",
    #     name="Reference Context Scoring",
    #     type="ranking",
    #     description="FR-051: IDF-weighted ±5-token window overlap at insertion point.",
    #     table_name="None (Runtime)",
    #     cpp_kernel="refcontext.ref_context_score",
    #     weight_key="reference_context.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="readability_match",
    #     name="Readability Level Match",
    #     type="ranking",
    #     description="FR-052: Flesch-Kincaid grade level penalty for source/dest mismatch.",
    #     table_name="content_contentitem (readability_grade)",
    #     weight_key="readability_match.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="passage_relevance",
    #     name="Passage-Level Relevance",
    #     type="ranking",
    #     description="FR-053: Best-passage cosine similarity across 5 chunks per page.",
    #     table_name="passage_embeddings",
    #     cpp_kernel="passagesim.passage_max_sim",
    #     weight_key="passage_relevance.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="boilerplate_ratio",
    #     name="Boilerplate-to-Content Ratio",
    #     type="ranking",
    #     description="FR-054: Penalises destinations with >80% template chrome.",
    #     table_name="content_contentitem (content_ratio)",
    #     weight_key="boilerplate_ratio.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="reasonable_surfer",
    #     name="Reasonable Surfer Click Probability",
    #     type="ranking",
    #     description="FR-055: Zone/position/emphasis-weighted link placement scoring.",
    #     table_name="None (Runtime)",
    #     weight_key="reasonable_surfer.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="long_click_ratio",
    #     name="Long-Click Satisfaction",
    #     type="ranking",
    #     description="FR-056: Ratio of 30s+ sessions to <10s bounces on destination.",
    #     table_name="analytics_suggestiontelemetrydaily",
    #     weight_key="long_click_ratio.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="content_update",
    #     name="Content-Update Magnitude",
    #     type="ranking",
    #     description="FR-057: Token symmetric-difference ratio between crawls.",
    #     table_name="content_contentitem (content_update_magnitude)",
    #     weight_key="content_update.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="ngram_quality",
    #     name="N-gram Writing Quality",
    #     type="ranking",
    #     description="FR-058: Inverse perplexity from Kneser-Ney n-gram LM.",
    #     table_name="content_contentitem (ngram_quality_score)",
    #     cpp_kernel="ngramqual.ngram_score",
    #     weight_key="ngram_quality.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="topic_purity",
    #     name="Topic Purity Score",
    #     type="ranking",
    #     description="FR-059: Fraction of on-topic sentences per section.",
    #     table_name="content_contentitem (topic_purity_score)",
    #     weight_key="topic_purity.ranking_weight",
    # ),
    # --- STATISTICAL MODELS (FR-060 to FR-065) ---
    # SignalDefinition(
    #     id="listnet",
    #     name="ListNet Listwise Ranker",
    #     type="ranking",
    #     description="FR-060: LightGBM rank:ndcg model replacing composite scorer.",
    #     table_name="None (Model File)",
    #     weight_key="listnet.enabled",
    # ),
    # SignalDefinition(
    #     id="rankboost",
    #     name="RankBoost Weight Tuner",
    #     type="ranking",
    #     description="FR-061: AdaBoost pairwise weight optimiser (weights-only mode).",
    #     table_name="None (Model File)",
    #     weight_key="rankboost.enabled",
    # ),
    # SignalDefinition(
    #     id="pts_mf",
    #     name="PTS-MF Collaborative Filter",
    #     type="ranking",
    #     description="FR-062: Particle Thompson Sampling + Matrix Factorisation.",
    #     table_name="None (Model File)",
    #     weight_key="pts_mf.enabled",
    # ),
    # SignalDefinition(
    #     id="mhr",
    #     name="Multi-Hyperplane Ranker",
    #     type="ranking",
    #     description="FR-063: 6-pair SVM ensemble with BordaCount aggregation.",
    #     table_name="None (Model File)",
    #     weight_key="mhr.enabled",
    # ),
    # SignalDefinition(
    #     id="spectral_rc",
    #     name="Spectral Relational Clustering",
    #     type="ranking",
    #     description="FR-064: Joint Laplacian eigen decomposition for topic clusters.",
    #     table_name="content_contentitem (spectral_cluster_id)",
    #     weight_key="spectral_rc.enabled",
    # ),
    # SignalDefinition(
    #     id="isotonic_calibration",
    #     name="Isotonic Score Calibration",
    #     type="ranking",
    #     description="FR-065: PAV monotonic calibration layer on composite scores.",
    #     table_name="None (Model File)",
    #     weight_key="isotonic_calibration.enabled",
    # ),
    # --- C++ META-ALGORITHMS (FR-066 to FR-068) ---
    # SignalDefinition(
    #     id="smoothrank",
    #     name="SmoothRank Direct NDCG",
    #     type="ranking",
    #     description="FR-066: Differentiable NDCG via sigmoid position smoothing.",
    #     table_name="None (Model File)",
    #     cpp_kernel="smoothrank.smoothrank_step",
    #     weight_key="smoothrank.enabled",
    # ),
    # SignalDefinition(
    #     id="rank_aggregation",
    #     name="Markov Chain Rank Aggregation",
    #     type="ranking",
    #     description="FR-067: SDP-optimised Markov chain stationary rank combiner.",
    #     table_name="None (Runtime)",
    #     cpp_kernel="rankagg.power_iter",
    #     weight_key="rank_aggregation.enabled",
    # ),
    # SignalDefinition(
    #     id="cascade_rerank",
    #     name="Cascade Telescoping Re-Ranker",
    #     type="ranking",
    #     description="FR-068: 3-stage cascade narrowing all→200→50→10 candidates.",
    #     table_name="None (Runtime)",
    #     cpp_kernel="cascade.stage_score",
    #     weight_key="cascade_rerank.enabled",
    # ),
    # --- SOCIAL MEDIA & TECH PATENT SIGNALS (FR-069 to FR-090) ---
    # SignalDefinition(
    #     id="viral_depth",
    #     name="Viral Propagation Depth",
    #     type="ranking",
    #     description="FR-069: Max sharing-hop depth from Meta patent US10152544B1.",
    #     table_name="content_contentitem (viral_depth_score)",
    #     weight_key="viral_depth.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="viral_recipient",
    #     name="Viral Recipient Authority",
    #     type="ranking",
    #     description="FR-070: Recipient influence scoring from YouTube patent.",
    #     table_name="content_contentitem (viral_recipient_score)",
    #     weight_key="viral_recipient.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="sentiment_score",
    #     name="Document Sentiment Score",
    #     type="ranking",
    #     description="FR-071: VADER compound polarity mapped to [0,1].",
    #     table_name="content_contentitem (sentiment_score)",
    #     weight_key="sentiment_score.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="trending_velocity",
    #     name="Trending Content Velocity",
    #     type="ranking",
    #     description="FR-072: 6-hour engagement acceleration from CrowdTangle patent.",
    #     table_name="content_contentitem (trending_velocity_score)",
    #     weight_key="trending_velocity.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="professional_proximity",
    #     name="Professional Graph Proximity",
    #     type="ranking",
    #     description="FR-073: Jaccard of GA4 user-ID sets from LinkedIn patent.",
    #     table_name="content_contentitem (professional_proximity_score)",
    #     weight_key="professional_proximity.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="influence_score",
    #     name="Social Influence Score",
    #     type="ranking",
    #     description="FR-074: Social reshare-graph PageRank (not link-graph).",
    #     table_name="content_contentitem (influence_score)",
    #     weight_key="influence_score.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="watch_completion",
    #     name="Watch-Time Completion Rate",
    #     type="ranking",
    #     description="FR-075: Video completion ratio from YouTube patent.",
    #     table_name="content_contentitem (watch_completion_score)",
    #     weight_key="watch_completion.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="dwell_profile_match",
    #     name="Dwell-Time Profile Match",
    #     type="ranking",
    #     description="FR-076: Audience attention-span matching.",
    #     table_name="content_contentitem (dwell_profile_match_score)",
    #     weight_key="dwell_profile_match.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="geo_concentration",
    #     name="Geographic Engagement Concentration",
    #     type="ranking",
    #     description="FR-077: Herfindahl index of country engagement shares.",
    #     table_name="content_contentitem (geo_concentration_score)",
    #     weight_key="geo_concentration.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="upvote_velocity",
    #     name="Community Upvote Velocity",
    #     type="ranking",
    #     description="FR-078: First-hour upvote rate from Reddit patent.",
    #     table_name="content_contentitem (upvote_velocity_score)",
    #     weight_key="upvote_velocity.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="spam_filter",
    #     name="Spam Interaction Filter",
    #     type="ranking",
    #     description="FR-079: Bot/spam engagement ratio penalty.",
    #     table_name="content_contentitem (spam_filter_score)",
    #     weight_key="spam_filter.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="freshness_decay_rate",
    #     name="Freshness Decay Rate",
    #     type="ranking",
    #     description="FR-080: Exponential engagement decay rate (evergreen scoring).",
    #     table_name="content_contentitem (freshness_decay_rate_score)",
    #     weight_key="freshness_decay_rate.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="sentiment_alignment",
    #     name="Contextual Sentiment Alignment",
    #     type="ranking",
    #     description="FR-081: Source/dest tonal consistency scoring.",
    #     table_name="None (Runtime)",
    #     weight_key="sentiment_alignment.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="structural_dup",
    #     name="Structural Duplicate Detection",
    #     type="ranking",
    #     description="FR-082: SimHash template-farm detection penalty.",
    #     table_name="content_contentitem (structural_dup_score)",
    #     weight_key="structural_dup.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="anomaly_filter",
    #     name="Anomalous Interaction Filter",
    #     type="ranking",
    #     description="FR-083: Engagement burst z-score anomaly detection.",
    #     table_name="content_contentitem (anomaly_filter_score)",
    #     weight_key="anomaly_filter.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="hashtag_cooccurrence",
    #     name="Hashtag Co-occurrence Strength",
    #     type="ranking",
    #     description="FR-084: PMI between topic tags from Snap patent.",
    #     table_name="content_contentitem (hashtag_cooccurrence_score)",
    #     weight_key="hashtag_cooccurrence.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="format_preference",
    #     name="Content Format Preference",
    #     type="ranking",
    #     description="FR-085: Format affinity scoring (text/image/video) from Snap patent.",
    #     table_name="content_contentitem (format_preference_score)",
    #     weight_key="format_preference.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="retweet_authority",
    #     name="Retweet Graph Authority",
    #     type="ranking",
    #     description="FR-086: Reshare-graph PageRank from Twitter patent.",
    #     table_name="content_contentitem (retweet_authority_score)",
    #     weight_key="retweet_authority.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="reply_depth",
    #     name="Reply Thread Depth",
    #     type="ranking",
    #     description="FR-087: Average comment thread depth from Twitter patent.",
    #     table_name="content_contentitem (reply_depth_score)",
    #     weight_key="reply_depth.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="bookmark_rate",
    #     name="Save/Bookmark Rate",
    #     type="ranking",
    #     description="FR-088: Intent-to-return scoring from Pinterest patent.",
    #     table_name="content_contentitem (bookmark_rate_score)",
    #     weight_key="bookmark_rate.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="visual_consistency",
    #     name="Visual-Topic Consistency",
    #     type="ranking",
    #     description="FR-089: Image-text coherence via CLIP-lite from Pinterest patent.",
    #     table_name="content_contentitem (visual_consistency_score)",
    #     weight_key="visual_consistency.ranking_weight",
    # ),
    # SignalDefinition(
    #     id="cross_platform_engagement",
    #     name="Cross-Platform Engagement",
    #     type="ranking",
    #     description="FR-090: Multi-platform simultaneous spike detection.",
    #     table_name="content_contentitem (cross_platform_score)",
    #     weight_key="cross_platform_engagement.ranking_weight",
    # ),
    # --- OPERATIONAL FEATURES (FR-091 to FR-096) ---
    # SignalDefinition(
    #     id="cpp_retrofit",
    #     name="C++ Extension Retrofit",
    #     type="ranking",
    #     description="FR-091: CPP-RULES.md compliance for all 12 existing extensions.",
    #     table_name="None (Build System)",
    #     weight_key="cpp_retrofit.enabled",
    # ),
    # SignalDefinition(
    #     id="graph_walk_refresh",
    #     name="Twice-Monthly Graph Walk Refresh",
    #     type="ranking",
    #     description="FR-092: Graph walks on 1st/15th instead of nightly.",
    #     table_name="suggestions_suggestion (graph_walk_diagnostics)",
    #     weight_key="graph_walk_refresh.enabled",
    # ),
    # SignalDefinition(
    #     id="retention_tier1",
    #     name="Extended Nightly Retention",
    #     type="ranking",
    #     description="FR-093: Prune Celery results, alerts, sync jobs nightly.",
    #     table_name="django_celery_results_taskresult, notifications_operatoralert",
    #     weight_key="retention_tier1.enabled",
    # ),
    # SignalDefinition(
    #     id="retention_tier2",
    #     name="Weekly Analytics Pruning",
    #     type="ranking",
    #     description="FR-094: Prune GSC/telemetry/keyword impact weekly.",
    #     table_name="analytics_gscdailyperformance, analytics_suggestiontelemetrydaily",
    #     weight_key="retention_tier2.enabled",
    # ),
    # SignalDefinition(
    #     id="quarterly_maintenance",
    #     name="Quarterly Database Maintenance",
    #     type="ranking",
    #     description="FR-095: VACUUM FULL, REINDEX, entity rebuild quarterly.",
    #     table_name="suggestions_suggestion, content_contentitem",
    #     weight_key="quarterly_maintenance.enabled",
    # ),
    # SignalDefinition(
    #     id="monthly_safe_prune",
    #     name="Monthly Safe Prune",
    #     type="ranking",
    #     description="FR-096: Prune BrokenLink, ImpactReport, old diagnostics JSON.",
    #     table_name="graph_brokenlink, analytics_impactreport",
    #     weight_key="monthly_safe_prune.enabled",
    # ),
]
