# Generated by Django 5.2 on 2026-04-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('job_key', models.CharField(db_index=True, max_length=128)),
                ('alert_type', models.CharField(choices=[('missed', 'Missed'), ('failed', 'Failed'), ('stalled', 'Stalled')], db_index=True, max_length=16)),
                ('calendar_date', models.DateField(db_index=True, help_text='The local-time date the alert refers to (missed window, failure day, etc.).')),
                ('first_raised_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='Set when an operator clicks the ✕ in the UI. Hides from active list.', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text="Set automatically when the job's next successful run completes. Resolved alerts drop out of the active list and are pruned after 30 days by jobalert_dedup_cleanup.", null=True)),
                ('message', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'verbose_name': 'Job alert',
                'verbose_name_plural': 'Job alerts',
                'indexes': [models.Index(fields=['acknowledged_at', 'resolved_at'], name='scheduled_u_acknowl_f5dd12_idx'), models.Index(fields=['job_key', 'alert_type'], name='scheduled_u_job_key_679d16_idx')],
                'constraints': [models.UniqueConstraint(fields=('job_key', 'alert_type', 'calendar_date'), name='unique_job_alert_per_day')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('key', models.CharField(help_text="Stable identifier for this job, e.g. 'pagerank_refresh' or 'lda_topic_refresh'. Code looks the job up by this key.", max_length=128, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable label shown in the Scheduled Updates tab.', max_length=160)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Runner orders pending jobs by this.', max_length=16)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('missed', 'Missed')], db_index=True, default='pending', max_length=16)),
                ('progress_pct', models.FloatField(default=0.0, help_text='0-100. Set by job code via report_progress().')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_estimate_sec', models.IntegerField(default=60)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When the job last *started*, regardless of outcome.', null=True)),
                ('last_success_at', models.DateTimeField(blank=True, help_text='When the job last *completed successfully*. Null until first success.', null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text="When the job's next run is planned. The runner uses this plus the priority to decide what to start next. Null = on-demand only.", null=True)),
                ('cadence_seconds', models.IntegerField(default=86400, help_text='Expected gap between successful runs. The catch-up detector flags the job as missed when now - last_success_at exceeds this.')),
                ('pause_token', models.BooleanField(default=False)),
                ('log_tail', models.TextField(blank=True, default='', help_text='Last ~4 KB of output. Truncated in save().')),
                ('current_message', models.CharField(blank=True, default='', help_text='Short status string the UI shows next to the progress bar.', max_length=240)),
            ],
            options={
                'verbose_name': 'Scheduled job',
                'verbose_name_plural': 'Scheduled jobs',
                'indexes': [models.Index(fields=['state', 'priority'], name='scheduled_u_state_9f7d3f_idx'), models.Index(fields=['scheduled_for'], name='scheduled_u_schedul_85fee0_idx'), models.Index(fields=['last_success_at'], name='scheduled_u_last_su_3a66f9_idx')],
            },
        ),
    ]
