# Generated by Django 5.2 on 2026-04-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0003_syncjob_embedding_items_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjob",
            name="checkpoint_items_processed",
            field=models.IntegerField(
                default=0,
                help_text="Total items processed before interruption. Used to calculate remaining work on resume.",
            ),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="checkpoint_last_item_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID of the last content item successfully processed before interruption.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="checkpoint_stage",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pipeline stage when checkpoint was saved (e.g. 'ingest', 'spacy', 'embed', 'pipeline').",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="is_resumable",
            field=models.BooleanField(
                default=False,
                help_text="True if this job was interrupted and can be resumed from its checkpoint.",
            ),
        ),
    ]
