# Generated by Django 5.2 on 2026-04-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0004_syncjob_checkpoint_items_processed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
