# Generated by Django 5.2.13 on 2026-04-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0005_add_cancelled_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
