# Generated by Django 5.2 on 2026-03-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditentry',
            name='audit_action_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='errorlog',
            name='errorlog_ack_date_idx',
        ),
        migrations.RenameIndex(
            model_name='auditentry',
            new_name='audit_audit_target__e2abcf_idx',
            old_name='audit_target_idx',
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='detail',
            field=models.JSONField(default=dict, help_text='Extra context: previous value, new value, reason, etc.'),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='target_type',
            field=models.CharField(help_text="The model/entity type affected, e.g. 'suggestion', 'setting', 'plugin'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='acknowledged',
            field=models.BooleanField(db_index=True, default=False, help_text='True once the user has reviewed and dismissed this error.'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='job_type',
            field=models.CharField(db_index=True, help_text="Type of job that failed, e.g. 'import', 'embed', 'pipeline', 'sync'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='raw_exception',
            field=models.TextField(blank=True, help_text='Full Python traceback (for debugging).'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='step',
            field=models.CharField(help_text='The specific step or function where the error occurred.', max_length=100),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='why',
            field=models.TextField(blank=True, help_text='Plain-English explanation of what likely caused this error.'),
        ),
        migrations.AlterField(
            model_name='reviewerscorecard',
            name='approval_rate',
            field=models.FloatField(default=0.0, help_text='Percentage of reviewed suggestions that were approved.'),
        ),
        migrations.AlterField(
            model_name='reviewerscorecard',
            name='approved_count',
            field=models.IntegerField(default=0, help_text='Number of suggestions approved.'),
        ),
        migrations.AlterField(
            model_name='reviewerscorecard',
            name='avg_review_time_seconds',
            field=models.FloatField(blank=True, help_text='Average seconds per suggestion review decision.', null=True),
        ),
        migrations.AlterField(
            model_name='reviewerscorecard',
            name='rejected_count',
            field=models.IntegerField(default=0, help_text='Number of suggestions rejected.'),
        ),
        migrations.AlterField(
            model_name='reviewerscorecard',
            name='stale_rate',
            field=models.FloatField(default=0.0, help_text='Percentage of approved suggestions that went stale.'),
        ),
        migrations.AlterField(
            model_name='reviewerscorecard',
            name='top_rejection_reasons',
            field=models.JSONField(default=list, help_text='Top rejection reason codes and their counts for this period.'),
        ),
        migrations.AlterField(
            model_name='reviewerscorecard',
            name='total_reviewed',
            field=models.IntegerField(default=0, help_text='Total suggestions reviewed in this period.'),
        ),
        migrations.AlterField(
            model_name='reviewerscorecard',
            name='verified_rate',
            field=models.FloatField(default=0.0, help_text='Percentage of approved suggestions later verified as live.'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['action', '-created_at'], name='audit_audit_action_d97ede_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['acknowledged', '-created_at'], name='audit_error_acknowl_686e89_idx'),
        ),
    ]
