# Generated by Django 5.2.13 on 2026-04-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_remove_auditentry_audit_action_date_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorlog",
            name="fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalised hash used to dedupe repeat occurrences. Internal: sha1(job|step|normalize(message)). GlitchTip: their fingerprint.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="glitchtip_issue_id",
            field=models.CharField(
                blank=True,
                help_text="Issue id from GlitchTip when source='glitchtip'.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="glitchtip_url",
            field=models.URLField(
                blank=True,
                help_text="Deep link to the GlitchTip issue detail page.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="how_to_fix",
            field=models.TextField(
                blank=True,
                help_text="Plain-English fix suggestion surfaced to the operator.",
            ),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="node_hostname",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="node_id",
            field=models.CharField(
                db_index=True,
                default="primary",
                help_text="Identifier of the node that produced this error.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="node_role",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("worker", "Worker"),
                    ("celery", "Celery"),
                    ("lightsail", "Lightsail"),
                    ("k8s", "K8s Pod"),
                    ("slave", "Slave"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="primary",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="occurrence_count",
            field=models.IntegerField(
                default=1,
                help_text="Number of times this fingerprint has been seen on this node.",
            ),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="runtime_context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot produced by apps.audit.runtime_context.snapshot() — GPU/CUDA/embedding/spaCy/python/node at the moment of failure.",
            ),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="severity",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                db_index=True,
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="source",
            field=models.CharField(
                choices=[("internal", "Internal"), ("glitchtip", "GlitchTip")],
                db_index=True,
                default="internal",
                help_text="Origin of this entry: internal (Celery tasks) or glitchtip (sync task).",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["source", "glitchtip_issue_id"],
                name="audit_error_source_c83250_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["fingerprint", "acknowledged"],
                name="audit_error_fingerp_d3b51a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["node_id", "-created_at"], name="audit_error_node_id_be6a25_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="errorlog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fingerprint__isnull", False)),
                fields=("fingerprint", "node_id"),
                name="uniq_errorlog_fingerprint_per_node",
            ),
        ),
    ]
