# Generated by Django 5.2.13 on 2026-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_errorlog_triage_and_node_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "message",
                    models.TextField(help_text="Error message as seen by the browser."),
                ),
                (
                    "stack",
                    models.TextField(
                        blank=True,
                        help_text="Stack trace, if the browser provided one.",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        help_text="The Angular router URL at time of error.",
                        max_length=500,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Full document.location.href at time of error.",
                        max_length=1000,
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("app_version", models.CharField(blank=True, max_length=50)),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Authenticated user id, if known. Not a FK — decoupled from the User table.",
                        null=True,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured context captured with the error (feature flags, scope, etc.).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Error Log Entry",
                "verbose_name_plural": "Client Error Log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="audit_clien_created_405aab_idx"
                    ),
                    models.Index(
                        fields=["route", "-created_at"],
                        name="audit_clien_route_3c9a93_idx",
                    ),
                ],
            },
        ),
    ]
