# Generated by Django 5.2.13 on 2026-04-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0008_feature_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Approved suggestion"),
                    ("reject", "Rejected suggestion"),
                    ("apply", "Marked as applied"),
                    ("verify", "Verified live link"),
                    ("edit_anchor", "Edited anchor text"),
                    ("mark_stale", "Marked as stale"),
                    ("supersede", "Superseded"),
                    ("note", "Note added"),
                    ("setting_change", "Setting changed"),
                    ("plugin_toggle", "Plugin enabled/disabled"),
                    ("pipeline_start", "Pipeline run started"),
                    ("pipeline_complete", "Pipeline run completed"),
                    ("sync_start", "Sync started"),
                    ("sync_complete", "Sync completed"),
                    ("clear_suppression", "Cleared rejected-pair suppression"),
                ],
                db_index=True,
                help_text="What type of action was taken.",
                max_length=30,
            ),
        ),
    ]
