# Generated by Django 5.2 on 2026-04-29 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_add_clear_suppression_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('rollout_percent', models.PositiveSmallIntegerField(default=100, help_text='Percentage of eligible users who see this flag (0-100).')),
                ('variants', models.JSONField(blank=True, default=list, help_text='[{"name": "control", "weight": 50}, {"name": "variant-a", "weight": 50}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('key', models.SlugField(max_length=80)),
                ('variant', models.CharField(blank=True, max_length=60)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flag_exposures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Flag Exposure',
                'verbose_name_plural': 'Feature Flag Exposures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key', '-created_at'], name='audit_ffexp_key_created_idx')],
            },
        ),
    ]
