# Generated by Django 5.2.14 on 2026-06-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_auditevent_featureflag_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='runtime_context',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot produced by apps.audit.runtime_context.snapshot() — embedding/spaCy/python/node state at the moment of failure.'),
        ),
    ]
