# ruff: noqa
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import api_pb2 as api__pb2


class StreamdStub(object):
    """Service is the only published gRPC service. Internal packages stay under
    services/streamd/internal/ and are unreachable through this contract.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/xf.streamd.v1.Streamd/Publish',
                request_serializer=api__pb2.PublishRequest.SerializeToString,
                response_deserializer=api__pb2.PublishResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/xf.streamd.v1.Streamd/Subscribe',
                request_serializer=api__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=api__pb2.Event.FromString,
                )
        self.Manage = channel.stream_stream(
                '/xf.streamd.v1.Streamd/Manage',
                request_serializer=api__pb2.ManageRequest.SerializeToString,
                response_deserializer=api__pb2.ManageResponse.FromString,
                )
        self.Health = channel.unary_unary(
                '/xf.streamd.v1.Streamd/Health',
                request_serializer=api__pb2.HealthRequest.SerializeToString,
                response_deserializer=api__pb2.HealthResponse.FromString,
                )


class StreamdServicer(object):
    """Service is the only published gRPC service. Internal packages stay under
    services/streamd/internal/ and are unreachable through this contract.
    """

    def Publish(self, request, context):
        """Publish appends one event to the topic. Returns the assigned offset.
        INVALID_ARGUMENT on empty topic, RESOURCE_EXHAUSTED on topic full /
        topic-limit reached.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe streams events for the topic. When `from_offset > 0`, replays
        any buffered events from that offset (up to the server's replay limit)
        and then streams every live event published thereafter. The stream ends
        when the client cancels the context or the connection closes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Manage(self, request_iterator, context):
        """Manage is a bidi-streaming admin channel. The client sends one request
        per command (ack, get_consumer_offset, topic_stats), the server returns
        one response per command. Kept bidi so a long-lived admin session can
        pipeline multiple commands without re-establishing the connection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health is the standard liveness probe. The streamd-healthcheck binary
        dials this RPC over the Unix socket and exits 0 on SERVING.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamdServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=api__pb2.PublishRequest.FromString,
                    response_serializer=api__pb2.PublishResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=api__pb2.SubscribeRequest.FromString,
                    response_serializer=api__pb2.Event.SerializeToString,
            ),
            'Manage': grpc.stream_stream_rpc_method_handler(
                    servicer.Manage,
                    request_deserializer=api__pb2.ManageRequest.FromString,
                    response_serializer=api__pb2.ManageResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=api__pb2.HealthRequest.FromString,
                    response_serializer=api__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xf.streamd.v1.Streamd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Streamd(object):
    """Service is the only published gRPC service. Internal packages stay under
    services/streamd/internal/ and are unreachable through this contract.
    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.streamd.v1.Streamd/Publish',
            api__pb2.PublishRequest.SerializeToString,
            api__pb2.PublishResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/xf.streamd.v1.Streamd/Subscribe',
            api__pb2.SubscribeRequest.SerializeToString,
            api__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Manage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/xf.streamd.v1.Streamd/Manage',
            api__pb2.ManageRequest.SerializeToString,
            api__pb2.ManageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.streamd.v1.Streamd/Health',
            api__pb2.HealthRequest.SerializeToString,
            api__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
