# Generated by Codex on 2026-05-21.

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetricCardinalityBudget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_name", models.CharField(max_length=160, unique=True)),
                ("max_series", models.PositiveIntegerField(default=1000)),
                ("current_series_estimated", models.PositiveIntegerField(default=0)),
                ("exceeded_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["metric_name"]},
        ),
    ]

