# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schemard.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import shared_pb2 as shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eschemard.proto\x12\x0exf.sidecars.v1\x1a\x0cshared.proto\"e\n\rSchemaVersion\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x13\n\x0bschema_json\x18\x03 \x01(\t\x12\x1d\n\x15\x63reated_at_unix_nanos\x18\x04 \x01(\x03\"A\n\x11SchemaVersionList\x12,\n\x05items\x18\x01 \x03(\x0b\x32\x1d.xf.sidecars.v1.SchemaVersion\"^\n\x15RegisterSchemaRequest\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x13\n\x0bschema_json\x18\x02 \x01(\t\x12\x1f\n\x17require_backward_compat\x18\x03 \x01(\x08\"4\n\x10GetSchemaRequest\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\"&\n\x13ListVersionsRequest\x12\x0f\n\x07subject\x18\x01 \x01(\t\" \n\rLatestRequest\x12\x0f\n\x07subject\x18\x01 \x01(\t\"p\n\x12\x43heckCompatRequest\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x1d\n\x15\x63\x61ndidate_schema_json\x18\x02 \x01(\t\x12*\n\x05level\x18\x03 \x01(\x0e\x32\x1b.xf.sidecars.v1.CompatLevel\"f\n\x0c\x43ompatReport\x12\x12\n\ncompatible\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\x12\x32\n\rchecked_level\x18\x03 \x01(\x0e\x32\x1b.xf.sidecars.v1.CompatLevel*S\n\x0b\x43ompatLevel\x12\x10\n\x0c\x43OMP_UNKNOWN\x10\x00\x12\x11\n\rCOMP_BACKWARD\x10\x01\x12\x10\n\x0c\x43OMP_FORWARD\x10\x02\x12\r\n\tCOMP_FULL\x10\x03\x32\xd3\x03\n\x08Schemard\x12P\n\x08Register\x12%.xf.sidecars.v1.RegisterSchemaRequest\x1a\x1d.xf.sidecars.v1.SchemaVersion\x12\x46\n\x03Get\x12 .xf.sidecars.v1.GetSchemaRequest\x1a\x1d.xf.sidecars.v1.SchemaVersion\x12V\n\x0cListVersions\x12#.xf.sidecars.v1.ListVersionsRequest\x1a!.xf.sidecars.v1.SchemaVersionList\x12O\n\x0b\x43heckCompat\x12\".xf.sidecars.v1.CheckCompatRequest\x1a\x1c.xf.sidecars.v1.CompatReport\x12\x46\n\x06Latest\x12\x1d.xf.sidecars.v1.LatestRequest\x1a\x1d.xf.sidecars.v1.SchemaVersion\x12<\n\x06Health\x12\x15.xf.sidecars.v1.Empty\x1a\x1b.xf.sidecars.v1.HealthReplyB<Z:xf-internal-linker-v2/services/sidecars/api/gen;sidecarsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schemard_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:xf-internal-linker-v2/services/sidecars/api/gen;sidecarsv1'
  _globals['_COMPATLEVEL']._serialized_start=660
  _globals['_COMPATLEVEL']._serialized_end=743
  _globals['_SCHEMAVERSION']._serialized_start=48
  _globals['_SCHEMAVERSION']._serialized_end=149
  _globals['_SCHEMAVERSIONLIST']._serialized_start=151
  _globals['_SCHEMAVERSIONLIST']._serialized_end=216
  _globals['_REGISTERSCHEMAREQUEST']._serialized_start=218
  _globals['_REGISTERSCHEMAREQUEST']._serialized_end=312
  _globals['_GETSCHEMAREQUEST']._serialized_start=314
  _globals['_GETSCHEMAREQUEST']._serialized_end=366
  _globals['_LISTVERSIONSREQUEST']._serialized_start=368
  _globals['_LISTVERSIONSREQUEST']._serialized_end=406
  _globals['_LATESTREQUEST']._serialized_start=408
  _globals['_LATESTREQUEST']._serialized_end=440
  _globals['_CHECKCOMPATREQUEST']._serialized_start=442
  _globals['_CHECKCOMPATREQUEST']._serialized_end=554
  _globals['_COMPATREPORT']._serialized_start=556
  _globals['_COMPATREPORT']._serialized_end=658
  _globals['_SCHEMARD']._serialized_start=746
  _globals['_SCHEMARD']._serialized_end=1213
# @@protoc_insertion_point(module_scope)
