# Generated by Django 5.2.14 on 2026-06-10 23:03

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_supersededembedding_unique_archive'),
        ('graph', '0004_linkfreshnessedge'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphSignalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('graph_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the sorted active edges used to build the graph.', max_length=64)),
                ('signal_version', models.CharField(help_text='Version identifier of the signal-computation logic.', max_length=50)),
                ('node_count', models.IntegerField(help_text='Number of nodes (content items) in this graph.')),
                ('edge_count', models.IntegerField(help_text='Number of edges (links) in this graph.')),
                ('status', models.CharField(choices=[('computing', 'Computing'), ('current', 'Current'), ('superseded', 'Superseded'), ('failed', 'Failed')], db_index=True, default='computing', help_text='Lifecycle state of this run.', max_length=20)),
                ('computed_at', models.DateTimeField(blank=True, help_text='When this run finished computing and became current.', null=True)),
                ('params_json', models.JSONField(blank=True, default=dict, help_text='Configuration and hyperparameter snapshot used for this run.')),
            ],
            options={
                'verbose_name': 'Graph Signal Run',
                'verbose_name_plural': 'Graph Signal Runs',
                'indexes': [models.Index(fields=['graph_hash', 'signal_version', 'status'], name='graph_graph_graph_h_53eed7_idx')],
            },
        ),
        migrations.CreateModel(
            name='LinkPredictionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adamic_adar', models.FloatField(blank=True, help_text='Adamic-Adar index score.', null=True)),
                ('common_neighbors', models.FloatField(blank=True, help_text='Common neighbors count.', null=True)),
                ('jaccard', models.FloatField(blank=True, help_text='Jaccard similarity of neighborhoods.', null=True)),
                ('same_community', models.BooleanField(default=False, help_text='True if both nodes are in the same Louvain community.')),
                ('is_bridge', models.BooleanField(default=False, help_text='True if this candidate connects different communities.')),
                ('embed_cosine', models.FloatField(blank=True, help_text='Cosine similarity of their node2vec embeddings.', null=True)),
                ('from_item', models.ForeignKey(help_text='Proposed source content item.', on_delete=django.db.models.deletion.CASCADE, related_name='link_predictions_out', to='content.contentitem')),
                ('run', models.ForeignKey(help_text='The snapshot run that produced this candidate.', on_delete=django.db.models.deletion.CASCADE, related_name='link_candidates', to='graph.graphsignalrun')),
                ('to_item', models.ForeignKey(help_text='Proposed destination content item.', on_delete=django.db.models.deletion.CASCADE, related_name='link_predictions_in', to='content.contentitem')),
            ],
            options={
                'verbose_name': 'Link Prediction Candidate',
                'verbose_name_plural': 'Link Prediction Candidates',
                'constraints': [models.UniqueConstraint(fields=('run', 'from_item', 'to_item'), name='graph_unique_link_prediction_candidate_per_run')],
            },
        ),
        migrations.CreateModel(
            name='NodeGraphSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.IntegerField(blank=True, help_text='Louvain community partition ID.', null=True)),
                ('betweenness', models.FloatField(blank=True, help_text='Betweenness centrality score.', null=True)),
                ('click_depth', models.IntegerField(blank=True, help_text='Shortest path distance from hub seeds.', null=True)),
                ('inbound_reachable', models.BooleanField(default=True, help_text='Whether this node can be reached from hubs.')),
                ('is_orphan', models.BooleanField(default=False, help_text='True if in-degree is 0.')),
                ('eigenvector', models.FloatField(blank=True, help_text='Eigenvector centrality score.', null=True)),
                ('katz', models.FloatField(blank=True, help_text='Katz centrality score.', null=True)),
                ('closeness', models.FloatField(blank=True, help_text='Closeness centrality score.', null=True)),
                ('core_number', models.IntegerField(blank=True, help_text='k-core decomposition shell number.', null=True)),
                ('component_id', models.IntegerField(blank=True, help_text='Weakly connected component ID.', null=True)),
                ('is_main_component', models.BooleanField(default=False, help_text='True if part of the largest connected component.')),
                ('local_clustering', models.FloatField(blank=True, help_text='Local clustering coefficient.', null=True)),
                ('group_seed_rank', models.IntegerField(blank=True, help_text='Rank order as a group-closeness seed.', null=True)),
                ('node2vec_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Structural embedding vector from node2vec.', null=True)),
                ('content_item', models.ForeignKey(help_text='The content item these signals describe.', on_delete=django.db.models.deletion.CASCADE, related_name='graph_signals', to='content.contentitem')),
                ('run', models.ForeignKey(help_text='The snapshot run that produced this signal.', on_delete=django.db.models.deletion.CASCADE, related_name='node_signals', to='graph.graphsignalrun')),
            ],
            options={
                'verbose_name': 'Node Graph Signal',
                'verbose_name_plural': 'Node Graph Signals',
                'constraints': [models.UniqueConstraint(fields=('run', 'content_item'), name='graph_unique_node_signal_per_run')],
            },
        ),
    ]
