# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import bullboard_pb2 as bullboard__pb2
from . import shared_pb2 as shared__pb2


class BullboardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Post = channel.unary_unary(
                '/xf.sidecars.v1.Bullboard/Post',
                request_serializer=bullboard__pb2.PostBulletinRequest.SerializeToString,
                response_deserializer=bullboard__pb2.Bulletin.FromString,
                )
        self.Recent = channel.unary_unary(
                '/xf.sidecars.v1.Bullboard/Recent',
                request_serializer=bullboard__pb2.RecentRequest.SerializeToString,
                response_deserializer=bullboard__pb2.BulletinList.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/xf.sidecars.v1.Bullboard/Subscribe',
                request_serializer=bullboard__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=bullboard__pb2.Bulletin.FromString,
                )
        self.RegisterThreshold = channel.unary_unary(
                '/xf.sidecars.v1.Bullboard/RegisterThreshold',
                request_serializer=bullboard__pb2.ThresholdRule.SerializeToString,
                response_deserializer=bullboard__pb2.ThresholdRule.FromString,
                )
        self.ListThresholds = channel.unary_unary(
                '/xf.sidecars.v1.Bullboard/ListThresholds',
                request_serializer=shared__pb2.Empty.SerializeToString,
                response_deserializer=bullboard__pb2.ThresholdRuleList.FromString,
                )
        self.RemoveThreshold = channel.unary_unary(
                '/xf.sidecars.v1.Bullboard/RemoveThreshold',
                request_serializer=bullboard__pb2.RemoveThresholdRequest.SerializeToString,
                response_deserializer=shared__pb2.Ack.FromString,
                )
        self.EvaluateNow = channel.unary_unary(
                '/xf.sidecars.v1.Bullboard/EvaluateNow',
                request_serializer=bullboard__pb2.EvaluateNowRequest.SerializeToString,
                response_deserializer=bullboard__pb2.EvaluationReport.FromString,
                )
        self.PromoteToAutoIssue = channel.unary_unary(
                '/xf.sidecars.v1.Bullboard/PromoteToAutoIssue',
                request_serializer=bullboard__pb2.PromoteRequest.SerializeToString,
                response_deserializer=shared__pb2.Ack.FromString,
                )
        self.Health = channel.unary_unary(
                '/xf.sidecars.v1.Bullboard/Health',
                request_serializer=shared__pb2.Empty.SerializeToString,
                response_deserializer=shared__pb2.HealthReply.FromString,
                )


class BullboardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Post(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterThreshold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListThresholds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveThreshold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateNow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteToAutoIssue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BullboardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Post': grpc.unary_unary_rpc_method_handler(
                    servicer.Post,
                    request_deserializer=bullboard__pb2.PostBulletinRequest.FromString,
                    response_serializer=bullboard__pb2.Bulletin.SerializeToString,
            ),
            'Recent': grpc.unary_unary_rpc_method_handler(
                    servicer.Recent,
                    request_deserializer=bullboard__pb2.RecentRequest.FromString,
                    response_serializer=bullboard__pb2.BulletinList.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=bullboard__pb2.SubscribeRequest.FromString,
                    response_serializer=bullboard__pb2.Bulletin.SerializeToString,
            ),
            'RegisterThreshold': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterThreshold,
                    request_deserializer=bullboard__pb2.ThresholdRule.FromString,
                    response_serializer=bullboard__pb2.ThresholdRule.SerializeToString,
            ),
            'ListThresholds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListThresholds,
                    request_deserializer=shared__pb2.Empty.FromString,
                    response_serializer=bullboard__pb2.ThresholdRuleList.SerializeToString,
            ),
            'RemoveThreshold': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveThreshold,
                    request_deserializer=bullboard__pb2.RemoveThresholdRequest.FromString,
                    response_serializer=shared__pb2.Ack.SerializeToString,
            ),
            'EvaluateNow': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateNow,
                    request_deserializer=bullboard__pb2.EvaluateNowRequest.FromString,
                    response_serializer=bullboard__pb2.EvaluationReport.SerializeToString,
            ),
            'PromoteToAutoIssue': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteToAutoIssue,
                    request_deserializer=bullboard__pb2.PromoteRequest.FromString,
                    response_serializer=shared__pb2.Ack.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=shared__pb2.Empty.FromString,
                    response_serializer=shared__pb2.HealthReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xf.sidecars.v1.Bullboard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bullboard(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Post(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Bullboard/Post',
            bullboard__pb2.PostBulletinRequest.SerializeToString,
            bullboard__pb2.Bulletin.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Recent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Bullboard/Recent',
            bullboard__pb2.RecentRequest.SerializeToString,
            bullboard__pb2.BulletinList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/xf.sidecars.v1.Bullboard/Subscribe',
            bullboard__pb2.SubscribeRequest.SerializeToString,
            bullboard__pb2.Bulletin.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterThreshold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Bullboard/RegisterThreshold',
            bullboard__pb2.ThresholdRule.SerializeToString,
            bullboard__pb2.ThresholdRule.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListThresholds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Bullboard/ListThresholds',
            shared__pb2.Empty.SerializeToString,
            bullboard__pb2.ThresholdRuleList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveThreshold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Bullboard/RemoveThreshold',
            bullboard__pb2.RemoveThresholdRequest.SerializeToString,
            shared__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EvaluateNow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Bullboard/EvaluateNow',
            bullboard__pb2.EvaluateNowRequest.SerializeToString,
            bullboard__pb2.EvaluationReport.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PromoteToAutoIssue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Bullboard/PromoteToAutoIssue',
            bullboard__pb2.PromoteRequest.SerializeToString,
            shared__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Bullboard/Health',
            shared__pb2.Empty.SerializeToString,
            shared__pb2.HealthReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
