import { SETTING_TOOLTIPS_EXTENDED } from './setting-tooltips-extended';

export interface SettingTooltip {
  definition: string;
  impact: string;
  default: string;
  example: string;
  range: string;
}

export const SETTING_TOOLTIPS_CORE: Record<string, SettingTooltip> = {
  // March 2026 PageRank
  'weightedAuthority.ranking_weight': {
    definition: 'How much the PageRank authority score contributes to the final link ranking.',
    impact: 'Higher values make authority the dominant factor. Links will strongly prefer high-authority destinations.',
    default: '0.10',
    example: 'Raising to 0.18 makes authority much stronger. Setting to 0 turns this off entirely.',
    range: '0 to 0.25',
  },
  'weightedAuthority.position_bias': {
    definition: 'Favours link placements that appear earlier on a page.',
    impact: 'Higher values prefer destinations already linked near the top of content. Lower values treat all positions equally.',
    default: '0.5',
    example: 'Raising to 0.9 makes early-position links dominant. Lowering to 0.1 almost ignores position.',
    range: '0 to 1',
  },
  'weightedAuthority.empty_anchor_factor': {
    definition: 'A penalty multiplier for links that have no anchor text at all.',
    impact: 'Lower values penalise empty anchors more. Higher values treat them almost like normal links.',
    default: '0.6',
    example: 'Raising to 0.9 nearly ignores missing anchors. Lowering to 0.1 strongly demotes them.',
    range: '0.1 to 1',
  },
  'weightedAuthority.bare_url_factor': {
    definition: 'A penalty multiplier for links that are raw URLs with no surrounding text.',
    impact: 'Lower values demote bare URLs more heavily in the ranking.',
    default: '0.35',
    example: 'Raising to 0.8 treats bare URLs close to normal links. Lowering to 0.1 nearly hides them.',
    range: '0.1 to 1',
  },
  'weightedAuthority.weak_context_factor': {
    definition: 'A penalty multiplier for links found in low-quality zones such as sidebars or footers.',
    impact: 'Lower values discount weak-context links more. Higher values give them nearly full credit.',
    default: '0.75',
    example: 'Raising to 0.95 treats sidebar links equally. Lowering to 0.2 strongly discounts them.',
    range: '0.1 to 1',
  },
  'weightedAuthority.isolated_context_factor': {
    definition: 'A penalty multiplier for links on pages with very few other links, which may indicate thin content.',
    impact: 'Lower values discount links from isolated, thin pages. Higher values give them full credit.',
    default: '0.45',
    example: 'Raising to 0.9 gives isolated pages full credit. Lowering to 0.1 nearly ignores them.',
    range: '0.1 to 1',
  },
  'tabs.diagnostics': {
    definition: 'Diagnostic view of all 23 algorithm signals and scoring components.',
    impact: 'Provides transparency into why certain links are suggested and allows monitoring of C++ acceleration and storage health.',
    default: 'N/A',
    example: 'Check this tab if you suspect a specific signal (e.g. Semantic Similarity) is misconfigured or underperforming.',
    range: 'N/A',
  },
  // Link Freshness
  'linkFreshness.ranking_weight': {
    definition: 'How much the freshness score influences the final ranking.',
    impact: 'Higher values reward destinations that are actively gaining new inbound links.',
    default: '0.05',
    example: '0.05 gives a gentle freshness boost. Raising to 0.15 makes freshness a strong signal.',
    range: '0 to 0.15',
  },
  'linkFreshness.recent_window_days': {
    definition: 'The number of days that counts as "recent" when measuring inbound link growth.',
    impact: 'A wider window smooths out short-term spikes. A narrower window reacts faster to recent changes.',
    default: '30',
    example: 'Raising to 60 gives a calmer, longer view of trends. Lowering to 7 focuses on very recent activity only.',
    range: '7 to 90',
  },
  'linkFreshness.newest_peer_percent': {
    definition: 'The top fraction of newest links used to define the "fresh" peer group for comparison.',
    impact: 'A higher value compares against a larger group. A lower value focuses on only the very newest peers.',
    default: '0.25',
    example: 'Raising to 0.5 broadens the comparison group. Lowering to 0.1 uses only the freshest links.',
    range: '0.1 to 0.5',
  },
  'linkFreshness.min_peer_count': {
    definition: 'Minimum number of inbound links a destination needs before its freshness score is calculated.',
    impact: 'Pages below this threshold receive a neutral score. Higher values keep uncertain pages neutral for longer.',
    default: '3',
    example: 'Raising to 10 requires more data before scoring. Lowering to 1 scores nearly everything.',
    range: '1 to 20',
  },
  'linkFreshness.w_recent': {
    definition: 'Weight given to whether the destination recently gained new inbound links.',
    impact: 'Higher values make recent link acquisition the biggest freshness driver.',
    default: '0.35',
    example: 'Raising to 0.7 makes recent gains dominate. Lowering to 0.1 reduces their influence.',
    range: '0 to 1',
  },
  'linkFreshness.w_growth': {
    definition: 'Weight given to the rate at which inbound links are growing over time.',
    impact: 'Higher values favour destinations with accelerating link acquisition.',
    default: '0.35',
    example: 'Raising to 0.6 rewards fast-growing destinations more. Lowering to 0.1 de-emphasises growth rate.',
    range: '0 to 1',
  },
  'linkFreshness.w_cohort': {
    definition: 'Weight given to how a destination compares against similar pages that gained links at the same time.',
    impact: 'Higher values reward destinations outperforming their cohort peers.',
    default: '0.2',
    example: 'Raising to 0.5 makes cohort comparison a major factor. Lowering reduces its influence.',
    range: '0 to 1',
  },
  'linkFreshness.w_loss': {
    definition: 'Weight given to whether the destination is losing inbound links.',
    impact: 'Higher values penalise destinations that are shedding links.',
    default: '0.1',
    example: 'Raising to 0.4 strongly penalises link loss. Lowering to 0 ignores link loss entirely.',
    range: '0 to 1',
  },
  // Phrase Matching
  'phraseMatching.ranking_weight': {
    definition: 'How much the phrase match score influences the final ranking.',
    impact: 'Higher values reward destinations whose title or text closely matches the linking phrase.',
    default: '0.08',
    example: '0.08 gives phrase matching a clear voice. Raising to 0.1 makes it even stronger.',
    range: '0 to 0.1',
  },
  'phraseMatching.enable_anchor_expansion': {
    definition: 'Generates candidate anchor phrases from the destination title and distilled text.',
    impact: 'Enabled broadens what can trigger a match. Disabled limits matching to the original anchor only.',
    default: 'Enabled',
    example: 'Disabling is useful if expansion is producing too many false-positive link suggestions.',
    range: 'Enabled / Disabled',
  },
  'phraseMatching.enable_partial_matching': {
    definition: 'Allows a link to match even if only part of the phrase is found in the destination.',
    impact: 'Enabled finds more links but may include weaker matches. Disabled requires exact phrase alignment.',
    default: 'Enabled',
    example: 'Disabling tightens phrase matching, reducing suggestions but improving precision.',
    range: 'Enabled / Disabled',
  },
  'phraseMatching.context_window_tokens': {
    definition: 'The number of words around a potential link considered when scoring a phrase match.',
    impact: 'Larger windows capture more surrounding context. Smaller windows focus on immediate words only.',
    default: '8',
    example: 'Raising to 12 captures more context. Lowering to 4 focuses only on the nearby words.',
    range: '4 to 12',
  },
  // Learned Anchors
  'learnedAnchor.ranking_weight': {
    definition: 'How much the learned anchor score influences the final ranking.',
    impact: 'Higher values reward destinations that already have real-world anchor text pointing to them.',
    default: '0.05',
    example: '0.05 gives a gentle boost. Raising above 0.08 may over-fit to past link patterns.',
    range: '0 to 0.1',
  },
  'learnedAnchor.minimum_anchor_sources': {
    definition: 'The minimum number of different source pages that must use the same anchor before it is trusted.',
    impact: 'Higher values require more evidence before a pattern is learned, reducing noise.',
    default: '2',
    example: 'Raising to 5 demands strong multi-page consensus. Lowering to 1 learns from a single page.',
    range: '1 to 10',
  },
  'learnedAnchor.minimum_family_support_share': {
    definition: 'The fraction of a destination\'s related pages that must also use the anchor before it counts.',
    impact: 'Higher values require more evidence before a pattern is learned, reducing noise.',
    default: '0.15',
    example: 'Raising to 0.3 requires wider agreement. Lowering to 0.05 accepts very narrow support.',
    range: '0.05 to 0.5',
  },
  'learnedAnchor.enable_noise_filter': {
    definition: 'Removes anchors that appear too frequently across the site and carry little meaning (e.g. "click here").',
    impact: 'Enabled keeps learned patterns meaningful. Disabled may introduce noisy, low-quality anchors.',
    default: 'Enabled',
    example: 'Disabling is rarely useful - only consider it if you need to debug which anchors are being filtered.',
    range: 'Enabled / Disabled',
  },
  // Rare-Term Propagation
  'rareTermPropagation.enabled': {
    definition: 'Turns on the ability to borrow rare keywords from nearby related pages to help thin-content destinations.',
    impact: 'Enabled helps pages with little text become discoverable via shared rare terms. Disabled turns this off entirely.',
    default: 'Enabled',
    example: 'Disabling is useful if propagated terms are causing unrelated pages to surface for the same query.',
    range: 'Enabled / Disabled',
  },
  'rareTermPropagation.ranking_weight': {
    definition: 'How much the rare-term propagation signal influences the final ranking.',
    impact: 'Higher values give more credit to thin pages that borrowed rare terms from neighbours.',
    default: '0.05',
    example: '0.05 gently helps thin pages. Raising above 0.08 may over-reward borrowed terms.',
    range: '0 to 0.1',
  },
  'rareTermPropagation.max_document_frequency': {
    definition: 'A word must appear in no more than this many documents to be considered rare and worth propagating.',
    impact: 'Higher values allow more common words to be shared. Lower values restrict sharing to very rare terms only.',
    default: '3',
    example: 'Raising to 8 lets moderately common words propagate. Lowering to 1 shares only extremely rare terms.',
    range: '1 to 10',
  },
  'rareTermPropagation.minimum_supporting_related_pages': {
    definition: 'At least this many related pages must all contain the rare term before it is borrowed.',
    impact: 'Higher values require stronger consensus, reducing the chance of borrowing irrelevant terms.',
    default: '2',
    example: 'Raising to 4 demands broader agreement. Lowering to 1 borrows from any single related page.',
    range: '1 to 5',
  },
  // Field-Aware Relevance
  'fieldAwareRelevance.ranking_weight': {
    definition: 'How much the field-aware relevance score influences the final ranking.',
    impact: 'Higher values reward destinations whose title, body, or anchor text aligns with the source sentence.',
    default: '0.10',
    example: '0.10 gives a meaningful relevance boost. Raising above 0.12 may dominate other signals.',
    range: '0 to 0.15',
  },
  'fieldAwareRelevance.title_field_weight': {
    definition: 'How much the destination title contributes to the relevance score relative to other fields.',
    impact: 'Higher values make title matching the most important relevance signal.',
    default: '0.30',
    example: 'Raising to 0.5 prioritises title matching heavily. Lowering to 0.1 makes titles less important.',
    range: '0 to 1',
  },
  'fieldAwareRelevance.heading_field_weight': {
    definition: 'How much destination headings contribute to the relevance score.',
    impact: 'Higher values reward matches in section headings.',
    default: '0.15',
    example: 'Raising to 0.3 makes heading matches more influential. Lowering to 0 ignores headings.',
    range: '0 to 1',
  },
  'fieldAwareRelevance.intro_field_weight': {
    definition: 'How much the first part of the main content contributes to the relevance score.',
    impact: 'Higher values reward matches near the top of the main content.',
    default: '0.20',
    example: 'Raising to 0.4 makes intro matches more influential. Lowering to 0 ignores intro position.',
    range: '0 to 1',
  },
  'fieldAwareRelevance.body_field_weight': {
    definition: 'How much the destination body text contributes to the relevance score.',
    impact: 'Higher values reward destinations whose body text closely matches the source sentence.',
    default: '0.15',
    example: 'Raising to 0.4 makes later body text more influential. Lowering to 0.05 reduces its importance.',
    range: '0 to 1',
  },
  'fieldAwareRelevance.scope_field_weight': {
    definition: 'How much the destination scope or category label contributes to the relevance score.',
    impact: 'Higher values reward destinations in the same topical scope as the source.',
    default: '0.10',
    example: 'Raising to 0.3 makes scope alignment a strong signal. Lowering to 0 ignores scope entirely.',
    range: '0 to 1',
  },
  'fieldAwareRelevance.learned_anchor_field_weight': {
    definition: 'How much learned anchor text contributes to the relevance score.',
    impact: 'Higher values reward destinations that have anchor patterns matching the source sentence.',
    default: '0.10',
    example: 'Raising to 0.3 gives strong weight to existing anchor patterns. Lowering reduces this influence.',
    range: '0 to 1',
  },
  // FR-021 — Graph Candidate Generation (Pixie Walk)
  'graphCandidate.enabled': {
    definition: 'Turns on graph-based candidate generation using bipartite random walks (Pixie).',
    impact: 'Enabled finds structural link candidates that semantic embedding searches might miss. Disabled relies purely on vector and keyword search.',
    default: 'Enabled',
    example: 'Keep enabled if you want to discover "people also linked" and structural relationship candidates.',
    range: 'Enabled / Disabled',
  },
  'graphCandidate.walk_steps_per_entity': {
    definition: 'Number of random walk steps to perform for each entity extracted from the source page.',
    impact: 'Higher values explore the graph more deeply but take longer. Lower values are faster but may miss distant relatives.',
    default: '2000',
    example: '2000 steps provides a good balance of depth and speed. Raise to 5000 for extremely thorough discovery.',
    range: '500 to 10000',
  },
  'graphCandidate.min_stable_candidates': {
    definition: 'Minimum number of candidates that must reach the visit threshold before stopping the walk early.',
    impact: 'Higher values ensure a more diverse set of candidates. Lower values stop faster once a few strong ones are found.',
    default: '50',
    example: '50 ensures we find enough high-confidence candidates before giving up.',
    range: '10 to 500',
  },
  'graphCandidate.min_visit_threshold': {
    definition: 'Number of visits required for a node to be considered stable during the walk.',
    impact: 'Higher values improve precision but may miss candidates in sparse graph areas. Lower values are more inclusive.',
    default: '4',
    example: 'Keep at 4 for a good mix. Raise to 8 if you find the candidates are too noisy.',
    range: '1 to 20',
  },
  'graphCandidate.top_k_candidates': {
    definition: 'Max number of top-visited candidates to return for full ranking.',
    impact: 'Higher values give the ranker more options but increase pipeline latency.',
    default: '100',
    example: '100 is usually plenty. Lower to 50 if the pipeline feels slow.',
    range: '10 to 1000',
  },
  'graphCandidate.top_n_entities_per_article': {
    definition: 'Max number of entities to extract from an article to use as seeds for the graph walk.',
    impact: 'Higher values capture more topics but increase walk time per page.',
    default: '15',
    example: '15 extracts the most salient entities. Raise to 30 for long-form content.',
    range: '5 to 100',
  },
  // FR-021 — Value Model (Instagram-style pre-scoring)
  'valueModel.enabled': {
    definition: 'Turns on the value model, which predicts the long-term engagement value of a potential link before full ranking.',
    impact: 'Enabled uses traffic, freshness, and authority signals to prune weak candidates early. Disabled skips pre-scoring.',
    default: 'Enabled',
    example: 'Keep enabled to ensure high-value destination content is prioritised in the final suggestions.',
    range: 'Enabled / Disabled',
  },
  'valueModel.w_relevance': {
    definition: 'Weight given to semantic relevance in the value prediction.',
    impact: 'Higher values prioritise candidates that look topically correct even if they have low traffic.',
    default: '0.35',
    example: '0.35 keeps relevance as the strongest single value signal.',
    range: '0 to 1.0',
  },
  'valueModel.w_traffic': {
    definition: 'Weight given to historical traffic in the value prediction.',
    impact: 'Higher values prioritise destinations that are already proven to be popular with users.',
    default: '0.25',
    example: '0.25 makes traffic the second strongest value driver.',
    range: '0 to 1.0',
  },
  'valueModel.w_freshness': {
    definition: 'Weight given to content freshness in the value prediction.',
    impact: 'Higher values prioritise newly updated content.',
    default: '0.1',
    example: '0.1 gives a light boost to fresh content in the early prune stage.',
    range: '0 to 1.0',
  },
  'valueModel.w_authority': {
    definition: 'Weight given to PageRank authority in the value prediction.',
    impact: 'Higher values prioritise established, high-authority pages.',
    default: '0.1',
    example: '0.1 ensures authority contributes without dominating the value filter.',
    range: '0 to 1.0',
  },
  'valueModel.w_penalty': {
    definition: 'Weight given to blocklist/penalty signals in the value prediction.',
    impact: 'Higher values more aggressively suppress penalised content early.',
    default: '0.5',
    example: 'Internal blocklists use this weight to sink undesirable suggestions.',
    range: '0 to 1.0',
  },
  'valueModel.traffic_lookback_days': {
    definition: 'Number of days of traffic history to consider for the value model.',
    impact: 'Longer windows are more stable. Shorter windows react faster to viral content.',
    default: '90',
    example: '90 days provides a solid statistical baseline.',
    range: '7 to 365',
  },
  'valueModel.traffic_fallback_value': {
    definition: 'Default traffic score for pages with no historical traffic data.',
    impact: 'Higher values give new content a "benefit of the doubt" during pruning.',
    default: '0.5',
    example: '0.5 is neutral — neither boosts nor penalises untracked pages.',
    range: '0 to 1',
  },
  // FR-024 engagement signal
  'valueModel.engagement_signal_enabled': {
    definition: 'Whether read-through rate is used to score link destinations.',
    impact: 'Pages that hold reader attention rank higher as link destinations.',
    default: 'true',
    example: 'Disable if you have no GA4 engagement data yet.',
    range: 'on / off',
  },
  'valueModel.w_engagement': {
    definition: 'How much read-through rate contributes to the value model score.',
    impact: 'Higher values favour pages with long average session times.',
    default: '0.08',
    example: 'Raise to 0.15 after you have 90 days of GA4 data.',
    range: '0 to 0.5',
  },
  'valueModel.engagement_lookback_days': {
    definition: 'How many days of GA4 data to average for engagement metrics.',
    impact: 'Longer windows are more stable; shorter windows react faster to changes.',
    default: '30',
    example: '7 for fast-moving content, 90 for evergreen articles.',
    range: '1 to 365',
  },
  'valueModel.engagement_words_per_minute': {
    definition: 'Reading speed used to estimate how long each article takes to read.',
    impact: 'Affects estimated read time, which divides into GA4 average engagement time.',
    default: '200',
    example: 'Lower for dense technical content, keep 200 for general posts.',
    range: '50 to 600',
  },
  'valueModel.engagement_cap_ratio': {
    definition: 'Raw read-through rates above this are capped before normalization.',
    impact: 'Prevents a handful of extreme outliers from collapsing all other scores to near-zero.',
    default: '1.5',
    example: 'Pages with very long dwell times (tabbed, re-reading) are capped here.',
    range: '1.0 to 5.0',
  },
  'valueModel.engagement_fallback_value': {
    definition: 'Score assigned to pages with no GA4 engagement data.',
    impact: 'New pages without analytics history receive this neutral value.',
    default: '0.5',
    example: '0.5 is neutral — it neither boosts nor penalises untracked pages.',
    range: '0 to 1',
  },
  // FR-023 hot decay signal
  'valueModel.hot_decay_enabled': {
    definition: 'Whether Reddit Hot decay replaces flat traffic averaging in the value model.',
    impact: 'When enabled, recent traffic momentum counts for more and old traffic fades over time.',
    default: 'true',
    example: 'Disable to fall back to original flat 90-day average.',
    range: 'on / off',
  },
  'valueModel.hot_gravity': {
    definition: 'Time-decay gravity factor in the Reddit Hot formula. Higher values penalise older traffic more.',
    impact: 'At 0.05, a page loses about one log-unit of hot score every 20 days.',
    default: '0.05',
    example: 'Raise to 0.08 for fast-moving sites where yesterday matters far more than last month.',
    range: '0.001 to 0.5',
  },
  'valueModel.hot_clicks_weight': {
    definition: 'Multiplier applied to click volume before feeding into the hot score formula.',
    impact: 'Higher values make clicks count more than impressions in the momentum calculation.',
    default: '1.0',
    example: 'Keep at 1.0 unless you want to deliberately downweight clicks vs impressions.',
    range: '0 to 5.0',
  },
  'valueModel.hot_impressions_weight': {
    definition: 'Multiplier applied to impression volume before feeding into the hot score formula.',
    impact: 'Impressions are much noisier than clicks, so the default is deliberately low.',
    default: '0.05',
    example: 'Raise to 0.2 if your pages have low CTR but high visibility matters.',
    range: '0 to 5.0',
  },
  'valueModel.hot_lookback_days': {
    definition: 'Number of days of daily SearchMetric rows to feed into the hot score calculation.',
    impact: 'Longer windows capture slow-burn trends; shorter windows react faster to momentum shifts.',
    default: '90',
    example: '30 for a news-heavy site, 90 for evergreen content.',
    range: '7 to 365',
  },
  // FR-025 co-occurrence signal
  'valueModel.co_occurrence_signal_enabled': {
    definition: 'Whether session co-occurrence data is used to boost link candidates.',
    impact: 'Pages frequently read together in the same GA4 session are ranked higher as link pairs.',
    default: 'true',
    example: 'Disable if you have no GA4 session data yet.',
    range: 'on / off',
  },
  'valueModel.w_cooccurrence': {
    definition: 'How much session co-occurrence contributes to the value model score.',
    impact: 'Higher values give more weight to reader-navigation patterns over text similarity.',
    default: '0.12',
    example: 'Raise to 0.20 once you have 90+ days of session data.',
    range: '0 to 1.0',
  },
  'valueModel.co_occurrence_fallback_value': {
    definition: 'Score assigned to pairs with no co-occurrence data.',
    impact: 'New or unpopular article pairs with no session history receive this neutral value.',
    default: '0.5',
    example: '0.5 is neutral — use lower to actively penalise unknown pairs.',
    range: '0 to 1',
  },
  'valueModel.co_occurrence_min_co_sessions': {
    definition: 'Minimum number of shared sessions for a co-occurrence pair to count.',
    impact: 'Lower values include noisier pairs; higher values require stronger evidence.',
    default: '5',
    example: 'Raise to 10 on high-traffic sites to filter coincidental co-reads.',
    range: '1 to 100',
  },
  // Click Distance
  'ga4Gsc.ranking_weight': {
    definition: 'How much first-party search and behavior data influences the final ranking.',
    impact: 'Higher values reward destinations that already earn stronger search clicks and better on-site engagement.',
    default: '0.05',
    example: 'Start at 0.05 so analytics acts like a light tie-breaker instead of overruling relevance.',
    range: '0 to 0.3',
  },
  'ga4Gsc.property_url': {
    definition: 'The Google Search Console property URL for your site.',
    impact: 'Required to fetch search performance data for your pages.',
    default: 'https://example.com/ or sc-domain:example.com',
    example: 'Use the exact property URL from the GSC dashboard.',
    range: 'Full URL or sc-domain: prefix',
  },
  'ga4Gsc.client_email': {
    definition: 'The client email from your Google Cloud service account JSON.',
    impact: 'Used to authenticate the app with the Google Search Console API.',
    default: 'service-account@project.iam.gserviceaccount.com',
    example: 'Copy from the "client_email" field of your JSON key.',
    range: 'A valid email address',
  },
  'ga4Gsc.private_key': {
    definition: 'The private key from your Google Cloud service account JSON.',
    impact: 'Used to securely sign API requests to Google.',
    default: '-----BEGIN PRIVATE KEY----- ...',
    example: 'Paste the entire key including the BEGIN and END markers.',
    range: 'A valid RSA private key string',
  },
  'ga4Gsc.sync_enabled': {
    definition: 'Turns the automatic GSC search performance sync on or off.',
    impact: 'When on, the app pulls daily clicks and impressions for your content.',
    default: 'Off',
    example: 'Recommended to keep this on for accurate search attribution.',
    range: 'Enabled / Disabled',
  },
  'ga4Gsc.sync_lookback_days': {
    definition: 'How many days of history to reread during each GSC sync.',
    impact: 'Helps pick up late-arriving data. Search Console data usually lags by 48 hours.',
    default: '14',
    example: 'Set to 14 or 28 to ensure all data is eventually captured.',
    range: '1 to 90 days',
  },
  'ga4Gsc.manual_backfill_days': {
    definition: 'A one-time window for rewriting older Search Console rows with the current filters and setup.',
    impact: 'Useful after changing country exclusions, reconnecting the property, or cleaning up older imported data.',
    default: 'Use the suggested value once',
    example: 'If you changed the blocked-country list, run a 180-day backfill once so historical rows match the new rules.',
    range: '1 to the max shown in the field',
  },
  'clickDistance.ranking_weight': {
    definition: 'How much the click-distance score influences the final ranking.',
    impact: 'Higher values prefer destinations structurally closer to the homepage or entry points.',
    default: '0.07',
    example: '0.07 gently favours shallower pages. Raising above 0.15 may over-penalise deep content.',
    range: '0 to 0.2',
  },
  'clickDistance.k_cd': {
    definition: 'Depth sensitivity - controls how steeply the score drops off as click-distance from the homepage increases.',
    impact: 'Higher values aggressively penalise pages many clicks from the homepage. Lower values are more lenient.',
    default: '4.0',
    example: 'Raising to 4.0 strongly penalises deep pages. Lowering to 0.5 makes depth almost irrelevant.',
    range: '0.5 to 5.0',
  },
  'clickDistance.b_cd': {
    definition: 'Click-distance bias - blends raw click-distance with a smoothed version to avoid extreme scores.',
    impact: 'Higher values smooth out very deep or very shallow pages. Lower values use the raw depth score.',
    default: '0.75',
    example: '0.75 keeps depth useful without letting one very deep URL dominate the score.',
    range: '0 to 1',
  },
  'clickDistance.b_ud': {
    definition: 'URL-depth bias - blends the URL depth (number of slashes in the path) into the score.',
    impact: 'Higher values prefer pages with shorter URL paths. Lower values ignore URL depth.',
    default: '0.25',
    example: '0.25 uses URL depth as light supporting evidence. Lowering to 0 ignores URL path depth.',
    range: '0 to 1',
  },
  // Spam Guards
  'spamGuards.max_existing_links_per_host': {
    definition: 'The maximum number of existing outgoing internal links a host page may already have before the pipeline skips it entirely.',
    impact: 'Lower values keep pages cleaner — the tool will not add any suggestions to heavily-linked pages. Higher values allow more suggestions on already-linked pages.',
    default: '3',
    example: 'At 3, a page with 3 existing body links receives no new suggestions. Raise to 5 for larger, content-rich pages.',
    range: '1 to 20',
  },
  'spamGuards.max_anchor_words': {
    definition: 'The maximum number of words the tool will use in a suggested anchor phrase.',
    impact: 'Lower values force shorter, more natural-looking anchors. Higher values allow longer, more descriptive (but potentially spammy) phrases.',
    default: '4',
    example: 'At 4 words, "carbon fibre bicycle frame" is accepted but "best carbon fibre bicycle frame" is rejected. Google recommends 2–5 words.',
    range: '1 to 10',
  },
  'spamGuards.paragraph_window': {
    definition: 'How many sentences apart two suggestions must be on the same page before they are allowed to coexist. Suggestions closer than this are treated as being in the same paragraph — only the better one is kept.',
    impact: 'Lower values are stricter — links must be further apart. Higher values are more lenient and allow links to appear closer together.',
    default: '3',
    example: 'At 3, if suggestion A is at sentence 2 and suggestion B is at sentence 4, only one survives. Set to 1 to allow links in consecutive sentences.',
    range: '1 to 10',
  },
  'keywordStuffing.enabled': {
    definition: 'Turns on FR-198, which penalises destination pages whose term distribution diverges sharply from the site baseline.',
    impact: 'Enabled demotes stuffed pages. Disabled removes this content-level anti-spam signal.',
    default: 'Enabled',
    example: 'Keep enabled so stuffing risk complements anchor and graph anti-spam signals.',
    range: 'Enabled / Disabled',
  },
  'keywordStuffing.ranking_weight': {
    definition: 'How strongly FR-198 penalises keyword stuffing anomalies.',
    impact: 'Higher values demote stuffed pages more. Lower values keep the penalty gentle.',
    default: '0.04',
    example: '0.04 is the strongest anti-spam default because stuffing is a direct content-quality issue.',
    range: '0 to 0.25',
  },
  'keywordStuffing.alpha': {
    definition: 'Steepness of the sigmoid that converts KL divergence into the final stuffing penalty.',
    impact: 'Higher values make the penalty rise faster once the threshold is crossed.',
    default: '6.0',
    example: 'Raise this if you want suspicious pages to move from neutral to penalised more abruptly.',
    range: '0.1 to 20',
  },
  'keywordStuffing.tau': {
    definition: 'KL-divergence threshold where FR-198 starts shifting from neutral toward penalised.',
    impact: 'Lower values make the detector more sensitive. Higher values make it more tolerant.',
    default: '0.30',
    example: 'Lowering to 0.2 catches more anomalies, but can increase false positives.',
    range: '0 to 2',
  },
  'keywordStuffing.dirichlet_mu': {
    definition: 'Dirichlet smoothing mass for the site-wide baseline language model.',
    impact: 'Higher values smooth harder toward the corpus baseline. Lower values trust each page distribution more.',
    default: '2000',
    example: 'Keep this reasonably high so small pages do not look stuffed too easily.',
    range: '100 to 20000',
  },
  'keywordStuffing.top_k_stuff_terms': {
    definition: 'How many suspicious repeated terms FR-198 should surface in diagnostics.',
    impact: 'Higher values show more evidence. Lower values keep diagnostics shorter.',
    default: '5',
    example: 'Five terms is usually enough to explain why a page looked stuffed.',
    range: '1 to 20',
  },
  'linkFarm.enabled': {
    definition: 'Turns on FR-197, which penalises destinations inside dense reciprocal link rings.',
    impact: 'Enabled adds graph-topology anti-spam protection. Disabled removes ring penalties.',
    default: 'Enabled',
    example: 'Keep enabled so the graph layer complements anchor and content anti-spam signals.',
    range: 'Enabled / Disabled',
  },
  'linkFarm.ranking_weight': {
    definition: 'How strongly FR-197 penalises reciprocal link-ring structures.',
    impact: 'Higher values demote suspicious rings more. Lower values make the graph penalty gentler.',
    default: '0.03',
    example: '0.03 is conservative because topology can be noisier on smaller sites.',
    range: '0 to 0.25',
  },
  'linkFarm.min_scc_size': {
    definition: 'Minimum strongly connected component size before FR-197 treats a reciprocal ring as suspicious.',
    impact: 'Higher values ignore smaller clusters. Lower values let the detector react earlier.',
    default: '3',
    example: 'Three avoids overreacting to simple two-page reciprocity.',
    range: '2 to 100',
  },
  'linkFarm.density_threshold': {
    definition: 'Density floor required before FR-197 treats a reciprocal ring as suspicious.',
    impact: 'Higher values focus on tighter rings. Lower values catch looser reciprocal structures.',
    default: '0.6',
    example: 'Raise this if you only want the tightest rings to be penalised.',
    range: '0.1 to 1.0',
  },
  'linkFarm.lambda': {
    definition: 'Penalty-curve slope used when FR-197 converts ring score into the final penalty.',
    impact: 'Higher values make the penalty rise faster as the ring score increases.',
    default: '0.8',
    example: '0.8 gives a moderate curve that complements the other anti-spam signals without dominating them.',
    range: '0.01 to 5.0',
  },
  // Silo Ranking
  'silo.mode': {
    definition: 'Sets how strictly the system enforces topic silo boundaries when ranking links.',
    impact: '"Disabled" ignores silos entirely. "Prefer same silo" boosts same-silo matches. "Strict same silo" blocks cross-silo links when both pages have silo assignments.',
    default: 'Prefer same silo',
    example: 'Start with "Prefer same silo" to keep link suggestions on-topic without hard blocking.',
    range: 'Disabled / Prefer same silo / Strict same silo',
  },
  'silo.same_silo_boost': {
    definition: 'A score bonus added to destinations that belong to the same topic silo as the source page.',
    impact: 'Higher values make the system strongly prefer linking within the same silo group.',
    default: '0.05',
    example: 'Raising to 0.2 noticeably prioritises same-silo links. Raising to 0.5 may nearly eliminate cross-silo suggestions.',
    range: '0 and above (no hard maximum)',
  },
  'silo.cross_silo_penalty': {
    definition: 'A score deduction applied to destinations that belong to a different silo from the source page.',
    impact: 'Higher values suppress cross-silo suggestions more aggressively.',
    default: '0.05',
    example: 'Raising to 0.2 significantly reduces cross-silo suggestions. Raising to 0.5 makes them rare.',
    range: '0 and above (no hard maximum)',
  },
  // Feedback Rerank
  'feedbackRerank.enabled': {
    definition: 'Turns on the explore/exploit reranking system, which uses historical reviewer feedback to improve suggestions over time.',
    impact: 'Enabled gradually learns from accept/reject decisions. Disabled keeps ranking purely algorithmic.',
    default: 'On',
    example: 'Keep this on at a light weight so feedback acts like a helper, not the boss.',
    range: 'On / Off',
  },
  'feedbackRerank.ranking_weight': {
    definition: 'How strongly historical reviewer feedback adjusts the final link ranking.',
    impact: 'Higher values make the feedback signal dominant. Lower values keep it as a subtle nudge.',
    default: '0.08',
    example: '0.08 keeps feedback as a light nudge. Raising too far can let old reviewer habits overpower relevance.',
    range: '0 to 1',
  },
  'feedbackRerank.exploration_rate': {
    definition: 'Controls how much the system explores links with little historical data versus exploiting known-good ones.',
    impact: 'Higher values aggressively test uncertain link pairs. Lower values rely more on established patterns.',
    default: '1.41421356237',
    example: 'About 1.41 is a balanced starting point. Raising too high pushes many untested links to the top for review.',
    range: '0 to 10',
  },
  // Clustering
  'clustering.enabled': {
    definition: 'Turns on near-duplicate destination clustering based on semantic embedding similarity.',
    impact: 'Enabled prevents suggesting multiple redundant links to effectively the same content. Disabled treats every URL as unique.',
    default: 'On',
    example: 'Enable to clean up the Review dashboard if you see many similar thread/resource pairs.',
    range: 'On / Off',
  },
  'clustering.similarity_threshold': {
    definition: 'How similar two pages must be (cosine distance) to be grouped into the same cluster.',
    impact: 'Lower values are stricter (only clones are grouped). Higher values are more inclusive (related topics might be grouped).',
    default: '0.04',
    example: 'Lower to 0.02 to only group exact duplicates. Raise to 0.08 to group broadly related content.',
    range: '0 to 0.15',
  },
  'clustering.suppression_penalty': {
    definition: 'The score penalty applied to non-canonical (redundant) versions of a content cluster.',
    impact: 'Higher values aggressively hide duplicates. Lower values let them surface if they are strong matches.',
    default: '20.0',
    example: 'Set to 20 to push duplicates far down the list. Lowering toward 5 makes suppression softer.',
    range: '0 to 50',
  },
  // Slate Diversity
  'slateDiversity.enabled': {
    definition: 'Turns on FR-015 MMR (Maximal Marginal Relevance) diversity reranking for the final per-host link slate.',
    impact: 'When enabled, the 3 suggestions for each host thread are chosen to cover different topics. When disabled, the top 3 by score are used regardless of similarity.',
    default: 'On',
    example: 'Enable to prevent three nearly-identical destination links appearing on the same thread.',
    range: 'On / Off',
  },
  'slateDiversity.diversity_lambda': {
    definition: 'MMR lambda - controls the balance between relevance and diversity in the final slate.',
    impact: 'Higher values (closer to 1.0) keep the most relevant suggestions. Lower values force more variety even if the alternatives score lower.',
    default: '0.65',
    example: 'Lower to 0.5 for stronger diversity. Raise to 0.9 to preserve near-original ranking with a light diversity nudge.',
    range: '0.0 to 1.0',
  },
  'slateDiversity.score_window': {
    definition: 'How far below the top candidate score a destination can be and still be considered for diversity reranking.',
    impact: 'Prevents low-quality items from jumping to the top purely for variety. Only candidates within this gap of the best score are eligible.',
    default: '0.30',
    example: 'Lower to 0.10 to only consider very close competitors. Raise to 0.50 to allow more distant alternatives.',
    range: '0.05 to 1.0',
  },
  'slateDiversity.similarity_cap': {
    definition: 'Cosine similarity threshold above which two selected destinations are flagged as near-redundant in diagnostics.',
    impact: 'Purely diagnostic - does not block selection. Helps you understand when the diversity reranker is doing meaningful work.',
    default: '0.90',
    example: 'Lower to 0.80 to flag moderately similar pairs. Keep at 0.90 to only flag near-clones.',
    range: '0.70 to 0.99',
  },
  // Information Gain
  'informationGain.enabled': {
    definition: 'Turns on information gain scoring, which rewards destinations that add new content the source page does not already cover.',
    impact: 'Enabled computes gain silently alongside other signals. Disabled skips all gain computation and stores a neutral score.',
    default: 'Enabled',
    example: 'Keep enabled so diagnostics run even at weight 0.',
    range: 'Enabled / Disabled',
  },
  'informationGain.ranking_weight': {
    definition: 'How much the information gain score influences the final ranking.',
    impact: 'Higher values reward destinations that add genuinely new vocabulary.',
    default: '0.03',
    example: '0.03 acts as a light tie-breaker.',
    range: '0 to 0.10',
  },
  'informationGain.min_source_chars': {
    definition: 'The minimum character count the source page body must have.',
    impact: 'Pages shorter than this threshold receive a neutral score.',
    default: '200',
    example: 'Keep at 200.',
    range: '50 to 1000',
  },
  // Entity Salience
  'entitySalience.enabled': {
    definition: 'Turns on entity salience matching.',
    impact: 'Enabled computes salience silently.',
    default: 'Enabled',
    example: 'Keep enabled so diagnostics run.',
    range: 'Enabled / Disabled',
  },
  'entitySalience.ranking_weight': {
    definition: 'How much the entity salience match score influences the final ranking.',
    impact: 'Higher values reward destinations that prominently feature the source page\'s most important terms.',
    default: '0.04',
    example: '0.04 gives a gentle boost.',
    range: '0 to 0.10',
  },
  'entitySalience.max_salient_terms': {
    definition: 'The maximum number of salient source-page terms extracted.',
    impact: 'More terms give a broader signal but may dilute precision.',
    default: '10',
    example: 'Lowering to 5 focuses on only the strongest terms.',
    range: '3 to 25',
  },
};

export const SETTING_TOOLTIPS: Record<string, SettingTooltip> = {
  ...SETTING_TOOLTIPS_CORE,
  ...SETTING_TOOLTIPS_EXTENDED,
};
