export const UI_TO_PRESET_KEY: Record<string, string> = {
  'weightedAuthority.ranking_weight': 'weighted_authority.ranking_weight',
  'weightedAuthority.position_bias': 'weighted_authority.position_bias',
  'weightedAuthority.empty_anchor_factor': 'weighted_authority.empty_anchor_factor',
  'weightedAuthority.bare_url_factor': 'weighted_authority.bare_url_factor',
  'weightedAuthority.weak_context_factor': 'weighted_authority.weak_context_factor',
  'weightedAuthority.isolated_context_factor': 'weighted_authority.isolated_context_factor',
  'linkFreshness.ranking_weight': 'link_freshness.ranking_weight',
  'linkFreshness.recent_window_days': 'link_freshness.recent_window_days',
  'linkFreshness.newest_peer_percent': 'link_freshness.newest_peer_percent',
  'linkFreshness.min_peer_count': 'link_freshness.min_peer_count',
  'linkFreshness.w_recent': 'link_freshness.w_recent',
  'linkFreshness.w_growth': 'link_freshness.w_growth',
  'linkFreshness.w_cohort': 'link_freshness.w_cohort',
  'linkFreshness.w_loss': 'link_freshness.w_loss',
  'phraseMatching.ranking_weight': 'phrase_matching.ranking_weight',
  'phraseMatching.enable_anchor_expansion': 'phrase_matching.enable_anchor_expansion',
  'phraseMatching.enable_partial_matching': 'phrase_matching.enable_partial_matching',
  'phraseMatching.context_window_tokens': 'phrase_matching.context_window_tokens',
  'learnedAnchor.ranking_weight': 'learned_anchor.ranking_weight',
  'learnedAnchor.minimum_anchor_sources': 'learned_anchor.minimum_anchor_sources',
  'learnedAnchor.minimum_family_support_share': 'learned_anchor.minimum_family_support_share',
  'learnedAnchor.enable_noise_filter': 'learned_anchor.enable_noise_filter',
  'rareTermPropagation.enabled': 'rare_term_propagation.enabled',
  'rareTermPropagation.ranking_weight': 'rare_term_propagation.ranking_weight',
  'rareTermPropagation.max_document_frequency': 'rare_term_propagation.max_document_frequency',
  'rareTermPropagation.minimum_supporting_related_pages': 'rare_term_propagation.minimum_supporting_related_pages',
  'fieldAwareRelevance.ranking_weight': 'field_aware_relevance.ranking_weight',
  'fieldAwareRelevance.title_field_weight': 'field_aware_relevance.title_field_weight',
  'fieldAwareRelevance.heading_field_weight': 'field_aware_relevance.heading_field_weight',
  'fieldAwareRelevance.intro_field_weight': 'field_aware_relevance.intro_field_weight',
  'fieldAwareRelevance.body_field_weight': 'field_aware_relevance.body_field_weight',
  'fieldAwareRelevance.scope_field_weight': 'field_aware_relevance.scope_field_weight',
  'fieldAwareRelevance.learned_anchor_field_weight': 'field_aware_relevance.learned_anchor_field_weight',
  'ga4Gsc.ranking_weight': 'ga4_gsc.ranking_weight',
  'clickDistance.ranking_weight': 'click_distance.ranking_weight',
  'clickDistance.k_cd': 'click_distance.k_cd',
  'clickDistance.b_cd': 'click_distance.b_cd',
  'clickDistance.b_ud': 'click_distance.b_ud',
  'silo.mode': 'silo.mode',
  'silo.same_silo_boost': 'silo.same_silo_boost',
  'silo.cross_silo_penalty': 'silo.cross_silo_penalty',
  'feedbackRerank.enabled': 'explore_exploit.enabled',
  'feedbackRerank.ranking_weight': 'explore_exploit.ranking_weight',
  'feedbackRerank.exploration_rate': 'explore_exploit.exploration_rate',
  'clustering.enabled': 'clustering.enabled',
  'clustering.similarity_threshold': 'clustering.similarity_threshold',
  'clustering.suppression_penalty': 'clustering.suppression_penalty',
  'slateDiversity.enabled': 'slate_diversity.enabled',
  'slateDiversity.diversity_lambda': 'slate_diversity.diversity_lambda',
  'slateDiversity.score_window': 'slate_diversity.score_window',
  'slateDiversity.similarity_cap': 'slate_diversity.similarity_cap',
  'informationGain.enabled': 'information_gain.enabled',
  'informationGain.ranking_weight': 'information_gain.ranking_weight',
  'informationGain.min_source_chars': 'information_gain.min_source_chars',
  'entitySalience.enabled': 'entity_salience.enabled',
  'entitySalience.ranking_weight': 'entity_salience.ranking_weight',
  'entitySalience.max_salient_terms': 'entity_salience.max_salient_terms',
  'entitySalience.max_site_document_frequency': 'entity_salience.max_site_document_frequency',
  'entitySalience.min_source_term_frequency': 'entity_salience.min_source_term_frequency',
  'multimediaSignal.enabled': 'multimedia_signal_enabled',
  'multimediaSignal.ranking_weight': 'w_multimedia',
  'multimediaSignal.fallback_value': 'multimedia_fallback_value',
  'originalityProvenance.enabled': 'originality_provenance.enabled',
  'originalityProvenance.ranking_weight': 'originality_provenance.ranking_weight',
  'originalityProvenance.resemblance_threshold': 'originality_provenance.resemblance_threshold',
  'originalityProvenance.containment_threshold': 'originality_provenance.containment_threshold',
  'factDensity.enabled': 'fact_density.enabled',
  'factDensity.ranking_weight': 'fact_density.ranking_weight',
  'factDensity.min_word_count': 'fact_density.min_word_count',
  'factDensity.density_cap_per_100_words': 'fact_density.density_cap_per_100_words',
  'factDensity.filler_penalty_weight': 'fact_density.filler_penalty_weight',
  'semanticDrift.enabled': 'semantic_drift.enabled',
  'semanticDrift.ranking_weight': 'semantic_drift.ranking_weight',
  'semanticDrift.tokens_per_sequence': 'semantic_drift.tokens_per_sequence',
  'semanticDrift.block_size_in_sequences': 'semantic_drift.block_size_in_sequences',
  'semanticDrift.anchor_similarity_threshold': 'semantic_drift.anchor_similarity_threshold',
  'semanticDrift.min_word_count': 'semantic_drift.min_word_count',
  'internalSearch.enabled': 'internal_search.enabled',
  'internalSearch.ranking_weight': 'internal_search.ranking_weight',
  'internalSearch.recent_days': 'internal_search.recent_days',
  'internalSearch.baseline_days': 'internal_search.baseline_days',
  'internalSearch.max_active_queries': 'internal_search.max_active_queries',
  'internalSearch.min_recent_count': 'internal_search.min_recent_count',
  'anchorDiversity.enabled': 'anchor_diversity.enabled',
  'anchorDiversity.ranking_weight': 'anchor_diversity.ranking_weight',
  'anchorDiversity.min_history_count': 'anchor_diversity.min_history_count',
  'anchorDiversity.max_exact_match_share': 'anchor_diversity.max_exact_match_share',
  'anchorDiversity.max_exact_match_count': 'anchor_diversity.max_exact_match_count',
  'anchorDiversity.hard_cap_enabled': 'anchor_diversity.hard_cap_enabled',
  'keywordStuffing.enabled': 'keyword_stuffing.enabled',
  'keywordStuffing.ranking_weight': 'keyword_stuffing.ranking_weight',
  'keywordStuffing.alpha': 'keyword_stuffing.alpha',
  'keywordStuffing.tau': 'keyword_stuffing.tau',
  'keywordStuffing.dirichlet_mu': 'keyword_stuffing.dirichlet_mu',
  'keywordStuffing.top_k_stuff_terms': 'keyword_stuffing.top_k_stuff_terms',
  'linkFarm.enabled': 'link_farm.enabled',
  'linkFarm.ranking_weight': 'link_farm.ranking_weight',
  'linkFarm.min_scc_size': 'link_farm.min_scc_size',
  'linkFarm.density_threshold': 'link_farm.density_threshold',
  'linkFarm.lambda': 'link_farm.lambda',
  'fanOut.enabled': 'fan_out.enabled',
  'fanOut.max_sub_queries': 'fan_out.max_sub_queries',
  'fanOut.min_segment_words': 'fan_out.min_segment_words',
  'fanOut.rrf_k': 'fan_out.rrf_k',
  'navigationPath.enabled': 'navigation_path.enabled',
  'navigationPath.ranking_weight': 'navigation_path.ranking_weight',
  'navigationPath.lookback_days': 'navigation_path.lookback_days',
  'navigationPath.min_sessions': 'navigation_path.min_sessions',
  'navigationPath.min_transition_count': 'navigation_path.min_transition_count',
  'navigationPath.w_direct': 'navigation_path.w_direct',
  'navigationPath.w_shortcut': 'navigation_path.w_shortcut',
  'topicalCluster.enabled': 'topical_cluster.enabled',
  'topicalCluster.ranking_weight': 'topical_cluster.ranking_weight',
  'topicalCluster.min_cluster_size': 'topical_cluster.min_cluster_size',
  'topicalCluster.min_site_pages': 'topical_cluster.min_site_pages',
  'topicalCluster.max_staleness_days': 'topical_cluster.max_staleness_days',
  'topicalCluster.fallback_value': 'topical_cluster.fallback_value',
  'intentFunnel.enabled': 'intent_funnel.enabled',
  'intentFunnel.ranking_weight': 'intent_funnel.ranking_weight',
  'intentFunnel.optimal_offset': 'intent_funnel.optimal_offset',
  'intentFunnel.sigma': 'intent_funnel.sigma',
  'intentFunnel.min_confidence': 'intent_funnel.min_confidence',
  'intentFunnel.navigational_confidence_threshold': 'intent_funnel.navigational_confidence_threshold',
  'seasonality.enabled': 'seasonality.enabled',
  'seasonality.ranking_weight': 'seasonality.ranking_weight',
  'seasonality.min_history_months': 'seasonality.min_history_months',
  'seasonality.min_seasonal_strength': 'seasonality.min_seasonal_strength',
  'seasonality.anticipation_window_months': 'seasonality.anticipation_window_months',
  'seasonality.w_current': 'seasonality.w_current',
  'seasonality.w_anticipation': 'seasonality.w_anticipation',
  'seasonality.index_cap': 'seasonality.index_cap',
  'darb.enabled': 'darb.enabled',
  'darb.ranking_weight': 'darb.ranking_weight',
  'darb.out_degree_saturation': 'darb.out_degree_saturation',
  'darb.min_host_value': 'darb.min_host_value',
  'kmig.enabled': 'kmig.enabled',
  'kmig.ranking_weight': 'kmig.ranking_weight',
  'kmig.attenuation': 'kmig.attenuation',
  'kmig.max_hops': 'kmig.max_hops',
  'tapb.enabled': 'tapb.enabled',
  'tapb.ranking_weight': 'tapb.ranking_weight',
  'tapb.apply_to_articulation_node_only': 'tapb.apply_to_articulation_node_only',
  'kcib.enabled': 'kcib.enabled',
  'kcib.ranking_weight': 'kcib.ranking_weight',
  'kcib.min_kcore_spread': 'kcib.min_kcore_spread',
  'berp.enabled': 'berp.enabled',
  'berp.ranking_weight': 'berp.ranking_weight',
  'berp.min_component_size': 'berp.min_component_size',
  'hgte.enabled': 'hgte.enabled',
  'hgte.ranking_weight': 'hgte.ranking_weight',
  'hgte.min_host_out_degree': 'hgte.min_host_out_degree',
  'rsqva.enabled': 'rsqva.enabled',
  'rsqva.ranking_weight': 'rsqva.ranking_weight',
  'rsqva.min_queries_per_page': 'rsqva.min_queries_per_page',
  'rsqva.min_query_clicks': 'rsqva.min_query_clicks',
  'rsqva.max_vocab_size': 'rsqva.max_vocab_size',
};

export interface AlertThreshold {
  warnBelow?: number;
  warnAbove?: number;
  dangerBelow?: number;
  dangerAbove?: number;
}

export const ALERT_THRESHOLDS: Record<string, AlertThreshold> = {
  'weightedAuthority.ranking_weight': { warnAbove: 0.18, dangerAbove: 0.22 },
  'weightedAuthority.position_bias': { warnBelow: 0.1, warnAbove: 0.9, dangerBelow: 0.05, dangerAbove: 0.96 },
  'weightedAuthority.empty_anchor_factor': { warnBelow: 0.2, warnAbove: 0.95, dangerBelow: 0.12, dangerAbove: 0.99 },
  'weightedAuthority.bare_url_factor': { warnBelow: 0.15, warnAbove: 0.9, dangerBelow: 0.1, dangerAbove: 0.96 },
  'weightedAuthority.weak_context_factor': { warnBelow: 0.2, warnAbove: 0.95, dangerBelow: 0.12, dangerAbove: 0.99 },
  'weightedAuthority.isolated_context_factor': { warnBelow: 0.15, warnAbove: 0.9, dangerBelow: 0.1, dangerAbove: 0.96 },
  'linkFreshness.ranking_weight': { warnAbove: 0.1, dangerAbove: 0.13 },
  'linkFreshness.recent_window_days': { warnBelow: 14, warnAbove: 60, dangerBelow: 10, dangerAbove: 80 },
  'linkFreshness.newest_peer_percent': { warnAbove: 0.45, dangerAbove: 0.49 },
  'linkFreshness.min_peer_count': { warnAbove: 15, dangerAbove: 18 },
  'linkFreshness.w_recent': { warnAbove: 0.65, dangerAbove: 0.85 },
  'linkFreshness.w_growth': { warnAbove: 0.65, dangerAbove: 0.85 },
  'linkFreshness.w_cohort': { warnAbove: 0.45, dangerAbove: 0.65 },
  'linkFreshness.w_loss': { warnAbove: 0.25, dangerAbove: 0.4 },
  'phraseMatching.ranking_weight': { warnAbove: 0.08, dangerAbove: 0.095 },
  'phraseMatching.context_window_tokens': { warnBelow: 5, warnAbove: 11, dangerBelow: 4, dangerAbove: 12 },
  'learnedAnchor.ranking_weight': { warnAbove: 0.08, dangerAbove: 0.095 },
  'learnedAnchor.minimum_anchor_sources': { warnAbove: 8, dangerAbove: 10 },
  'learnedAnchor.minimum_family_support_share': { warnAbove: 0.4, dangerAbove: 0.48 },
  'rareTermPropagation.ranking_weight': { warnAbove: 0.08, dangerAbove: 0.095 },
  'rareTermPropagation.max_document_frequency': { warnAbove: 7, dangerAbove: 9 },
  'rareTermPropagation.minimum_supporting_related_pages': { warnAbove: 3, dangerAbove: 4 },
  'fieldAwareRelevance.ranking_weight': { warnAbove: 0.12, dangerAbove: 0.145 },
  'fieldAwareRelevance.title_field_weight': { warnAbove: 0.65, dangerAbove: 0.85 },
  'fieldAwareRelevance.heading_field_weight': { warnAbove: 0.4, dangerAbove: 0.6 },
  'fieldAwareRelevance.intro_field_weight': { warnAbove: 0.5, dangerAbove: 0.7 },
  'fieldAwareRelevance.body_field_weight': { warnAbove: 0.65, dangerAbove: 0.85 },
  'fieldAwareRelevance.scope_field_weight': { warnAbove: 0.4, dangerAbove: 0.6 },
  'fieldAwareRelevance.learned_anchor_field_weight': { warnAbove: 0.4, dangerAbove: 0.6 },
  'ga4Gsc.ranking_weight': { warnAbove: 0.12, dangerAbove: 0.2 },
  'clickDistance.ranking_weight': { warnAbove: 0.15, dangerAbove: 0.18 },
  'clickDistance.k_cd': { warnBelow: 2.0, warnAbove: 5.0, dangerBelow: 1.0, dangerAbove: 5.8 },
  'clickDistance.b_cd': { warnBelow: 0.4, warnAbove: 0.9, dangerBelow: 0.2, dangerAbove: 0.97 },
  'clickDistance.b_ud': { warnAbove: 0.5, dangerAbove: 0.75 },
  'feedbackRerank.ranking_weight': { warnAbove: 0.15, dangerAbove: 0.3 },
  'feedbackRerank.exploration_rate': { warnBelow: 0.7, warnAbove: 2.5, dangerBelow: 0.4, dangerAbove: 4.0 },
  'silo.same_silo_boost': { warnAbove: 0.4, dangerAbove: 0.8 },
  'silo.cross_silo_penalty': { warnAbove: 0.4, dangerAbove: 0.8 },
  'clustering.similarity_threshold': { warnAbove: 0.1, dangerAbove: 0.135 },
  'clustering.suppression_penalty': { warnBelow: 5, warnAbove: 30, dangerBelow: 2, dangerAbove: 40 },
  'slateDiversity.diversity_lambda': { warnBelow: 0.4, dangerBelow: 0.2 },
  'slateDiversity.score_window': { warnAbove: 0.6, dangerAbove: 0.85 },
  'slateDiversity.similarity_cap': { warnBelow: 0.75, dangerBelow: 0.71 },
  'informationGain.ranking_weight': { warnAbove: 0.08, dangerAbove: 0.10 },
  'informationGain.min_source_chars': { warnBelow: 80, dangerBelow: 50 },
  'entitySalience.ranking_weight': { warnAbove: 0.08, dangerAbove: 0.10 },
  'entitySalience.max_salient_terms': { warnAbove: 20, dangerAbove: 24 },
  'entitySalience.max_site_document_frequency': { warnAbove: 60, dangerAbove: 80 },
  'multimediaSignal.ranking_weight': { warnAbove: 0.15, dangerAbove: 0.20 },
  'multimediaSignal.fallback_value': { warnBelow: 0.4, warnAbove: 0.6, dangerBelow: 0.25, dangerAbove: 0.75 },
  'originalityProvenance.ranking_weight': { warnAbove: 0.08, dangerAbove: 0.10 },
  'originalityProvenance.resemblance_threshold': { warnBelow: 0.40, warnAbove: 0.75, dangerBelow: 0.25, dangerAbove: 0.90 },
  'originalityProvenance.containment_threshold': { warnBelow: 0.65, dangerAbove: 0.92 },
  'factDensity.ranking_weight': { warnAbove: 0.08, dangerAbove: 0.10 },
  'factDensity.min_word_count': { warnBelow: 80, warnAbove: 250, dangerBelow: 50, dangerAbove: 350 },
  'factDensity.density_cap_per_100_words': { warnBelow: 4, warnAbove: 12, dangerBelow: 2, dangerAbove: 18 },
  'factDensity.filler_penalty_weight': { warnAbove: 0.65, dangerAbove: 0.85 },
  'semanticDrift.ranking_weight': { warnAbove: 0.06, dangerAbove: 0.10 },
  'semanticDrift.tokens_per_sequence': { warnBelow: 12, warnAbove: 40, dangerBelow: 8, dangerAbove: 60 },
  'semanticDrift.block_size_in_sequences': { warnBelow: 4, warnAbove: 10, dangerBelow: 2, dangerAbove: 14 },
  'semanticDrift.anchor_similarity_threshold': { warnBelow: 0.10, warnAbove: 0.30, dangerBelow: 0.05, dangerAbove: 0.40 },
  'semanticDrift.min_word_count': { warnBelow: 120, warnAbove: 320, dangerBelow: 80, dangerAbove: 500 },
  'internalSearch.ranking_weight': { warnAbove: 0.05, dangerAbove: 0.08 },
  'internalSearch.recent_days': { warnBelow: 2, warnAbove: 7, dangerBelow: 1, dangerAbove: 14 },
  'internalSearch.baseline_days': { warnBelow: 14, warnAbove: 60, dangerBelow: 7, dangerAbove: 90 },
  'internalSearch.max_active_queries': { warnAbove: 400, dangerAbove: 800 },
  'internalSearch.min_recent_count': { warnAbove: 8, dangerAbove: 12 },
  'anchorDiversity.ranking_weight': { warnAbove: 0.10, dangerAbove: 0.15 },
  'anchorDiversity.max_exact_match_share': { warnBelow: 0.25, warnAbove: 0.75, dangerBelow: 0.20, dangerAbove: 0.90 },
  'anchorDiversity.max_exact_match_count': { warnAbove: 7, dangerAbove: 10 },
  'keywordStuffing.ranking_weight': { warnAbove: 0.10, dangerAbove: 0.15 },
  'keywordStuffing.alpha': { warnAbove: 10, dangerAbove: 15 },
  'keywordStuffing.tau': { warnBelow: 0.15, warnAbove: 0.80, dangerBelow: 0.10, dangerAbove: 1.20 },
  'keywordStuffing.dirichlet_mu': { warnBelow: 500, warnAbove: 8000, dangerBelow: 250, dangerAbove: 12000 },
  'keywordStuffing.top_k_stuff_terms': { warnAbove: 10, dangerAbove: 15 },
  'linkFarm.ranking_weight': { warnAbove: 0.10, dangerAbove: 0.15 },
  'linkFarm.min_scc_size': { warnBelow: 3, warnAbove: 20, dangerAbove: 40 },
  'linkFarm.density_threshold': { warnBelow: 0.35, warnAbove: 0.85, dangerBelow: 0.20, dangerAbove: 0.95 },
  'linkFarm.lambda': { warnAbove: 1.5, dangerAbove: 2.5 },
  'fanOut.max_sub_queries': { warnAbove: 4, dangerAbove: 5 },
  'fanOut.min_segment_words': { warnBelow: 25, warnAbove: 150, dangerBelow: 20, dangerAbove: 200 },
  'fanOut.rrf_k': { warnBelow: 15, warnAbove: 100, dangerBelow: 10, dangerAbove: 120 },
  'navigationPath.ranking_weight': { warnAbove: 0.08, dangerAbove: 0.12 },
  'navigationPath.lookback_days': { warnBelow: 14, warnAbove: 180, dangerBelow: 7, dangerAbove: 365 },
  'navigationPath.min_sessions': { warnBelow: 10, warnAbove: 200, dangerBelow: 5, dangerAbove: 500 },
  'navigationPath.min_transition_count': { warnAbove: 20, dangerAbove: 40 },
  'topicalCluster.ranking_weight': { warnAbove: 0.08, dangerAbove: 0.12 },
  'topicalCluster.min_cluster_size': { warnBelow: 3, warnAbove: 25, dangerBelow: 2, dangerAbove: 50 },
  'topicalCluster.max_staleness_days': { warnBelow: 3, warnAbove: 60, dangerBelow: 1, dangerAbove: 90 },
  'intentFunnel.ranking_weight': { warnAbove: 0.06, dangerAbove: 0.10 },
  'intentFunnel.sigma': { warnBelow: 0.5, warnAbove: 2.5, dangerBelow: 0.3, dangerAbove: 3.0 },
  'intentFunnel.min_confidence': { warnAbove: 0.7, dangerAbove: 0.85 },
  'seasonality.ranking_weight': { warnAbove: 0.06, dangerAbove: 0.10 },
  'seasonality.min_history_months': { warnBelow: 8, dangerBelow: 6 },
  'seasonality.min_seasonal_strength': { warnAbove: 0.6, dangerAbove: 0.8 },
  'seasonality.index_cap': { warnBelow: 2.0, warnAbove: 6.0, dangerBelow: 1.5, dangerAbove: 10.0 },
};
