import { SettingTooltip } from './setting-tooltips';

export const SETTING_TOOLTIPS_EXTENDED: Record<string, SettingTooltip> = {
  'wordpress.base_url': {
    definition: 'The main front-door address of your WordPress site.',
    impact: 'The app uses this address when it talks to WordPress. If it is wrong, sync will fail or pull from the wrong place.',
    default: 'Your live site home page',
    example: 'Use https://example.com, not https://example.com/wp-admin.',
    range: 'A full site URL starting with http:// or https://',
  },
  'wordpress.username': {
    definition: 'The WordPress username tied to the application password.',
    impact: 'Needed when the site requires login for the API. Leave blank if you only sync public content.',
    default: 'Blank unless your site needs login',
    example: 'Use the real WordPress account name, not your display nickname.',
    range: 'Any valid WordPress username',
  },
  'wordpress.app_password': {
    definition: 'A special WordPress app password, not your normal login password.',
    impact: 'Lets this app sync content safely without storing your main site password.',
    default: 'Blank unless private content needs access',
    example: 'Create it in WordPress, then paste it here once. Leave this box empty later to keep the saved one.',
    range: 'A valid WordPress application password',
  },
  'wordpress.sync_enabled': {
    definition: 'Turns the automatic WordPress sync schedule on or off.',
    impact: 'When on, the app runs a background sync at the hour and minute below.',
    default: 'Off',
    example: 'Turn it on if you want fresh posts pulled in every day without clicking Run sync now.',
    range: 'Enabled / Disabled',
  },
  'wordpress.sync_hour': {
    definition: 'The UTC hour for the automatic WordPress sync.',
    impact: 'Sets the hour part of the schedule. Use UTC, not your local clock.',
    default: '3',
    example: '3 means the sync starts at 03:00 UTC every day.',
    range: '0 to 23',
  },
  'wordpress.sync_minute': {
    definition: 'The UTC minute for the automatic WordPress sync.',
    impact: 'Sets the minute part of the schedule.',
    default: '0',
    example: '30 means the sync starts at half past the chosen UTC hour.',
    range: '0 to 59',
  },
  'googleOAuth.client_id': {
    definition: 'The OAuth client ID from Google Cloud for your web application.',
    impact: 'This lets the app open Google sign-in so one login can authorize both GA4 and Search Console.',
    default: 'Blank until you create a Google OAuth app',
    example: 'Create a Web application credential in Google Cloud, then paste the client ID exactly as shown.',
    range: 'A valid Google OAuth client ID',
  },
  'googleOAuth.client_secret': {
    definition: 'The matching OAuth client secret for the Google app above.',
    impact: 'Required alongside the client ID to complete Google sign-in and token exchange.',
    default: 'Blank until you create the Google OAuth app',
    example: 'Copy the secret from Google Cloud Console > APIs & Services > Credentials for the same web app as the client ID.',
    range: 'A valid Google OAuth client secret',
  },
  'ga4Telemetry.behavior_enabled': {
    definition: 'Turns GA4 browser event sending on or off.',
    impact: 'When enabled, the frontend can send impression, click, and engagement events to your GA4 property.',
    default: 'Off',
    example: 'Turn this on only after the Measurement ID and API secret are saved and tested.',
    range: 'Enabled / Disabled',
  },
  'ga4Telemetry.property_id': {
    definition: 'The numeric GA4 property ID used for read access and reporting sync.',
    impact: 'Needed to pull daily traffic totals back from the GA4 Data API.',
    default: 'Blank until your GA4 property is ready',
    example: 'Use the numeric Property ID from GA4 Admin, not the Measurement ID that starts with G-.',
    range: 'A numeric GA4 property ID',
  },
  'ga4Telemetry.measurement_id': {
    definition: 'The GA4 Measurement ID used by browser events.',
    impact: 'This tells event pings which GA4 web data stream should receive the telemetry.',
    default: 'Blank until a GA4 web stream exists',
    example: 'Copy the Measurement ID from the GA4 web stream. It usually looks like G-ABC123XYZ.',
    range: 'A GA4 Measurement ID starting with G-',
  },
  'ga4Telemetry.api_secret': {
    definition: 'The Measurement Protocol API secret for the same GA4 web stream.',
    impact: 'Required for securely sending browser events to GA4 from this app.',
    default: 'Blank until you create one in GA4',
    example: 'In GA4 Admin, open your web stream, create an API secret under Measurement Protocol, then paste it here once.',
    range: 'A valid GA4 API secret',
  },
  'ga4Telemetry.sync_enabled': {
    definition: 'Turns GA4 read-sync on or off.',
    impact: 'When enabled, the backend pulls daily GA4 totals back into the app as a first-party behavior signal.',
    default: 'Off',
    example: 'Leave this on if you want GA4 page metrics imported regularly, even when browser events are already being sent.',
    range: 'Enabled / Disabled',
  },
  'ga4Telemetry.read_project_id': {
    definition: 'The Google Cloud project ID for the fallback GA4 service account.',
    impact: 'Used only when you choose service-account read access instead of relying on Google OAuth.',
    default: 'Blank unless you use the fallback setup',
    example: 'Copy the project_id value from the service-account JSON key file.',
    range: 'A valid Google Cloud project ID',
  },
  'ga4Telemetry.read_client_email': {
    definition: 'The client email from the fallback GA4 service-account JSON key.',
    impact: 'The app uses this identity to call the GA4 Data API when OAuth is not being used.',
    default: 'Blank unless you use the fallback setup',
    example: 'Share GA4 property access with this service-account email before testing read access.',
    range: 'A valid service-account email address',
  },
  'ga4Telemetry.read_private_key': {
    definition: 'The private key from the fallback GA4 service-account JSON key.',
    impact: 'Allows the backend to authenticate as the fallback service account for GA4 read access.',
    default: 'Blank unless you use the fallback setup',
    example: 'Paste the full private_key value including the BEGIN and END markers.',
    range: 'A valid PEM private key',
  },
  'ga4Telemetry.sync_lookback_days': {
    definition: 'How many recent days of GA4 data are reread on each sync.',
    impact: 'A small overlap helps catch late processing and keeps imported totals stable.',
    default: '7',
    example: 'Use 7 to keep imports fresh without rereading too much data every day.',
    range: '1 to 30 days',
  },
  'ga4Telemetry.geo_granularity': {
    definition: 'Controls how much geographic detail is stored from GA4 imports.',
    impact: 'More detail gives richer analysis, while less detail reduces stored location information.',
    default: 'Country only',
    example: 'Choose Country only for a balanced default. Use Do not store geography if location data is unnecessary.',
    range: 'None / Country / Country and region',
  },
  'ga4Telemetry.event_schema': {
    definition: 'The internal event schema version expected by this app.',
    impact: 'Helps keep browser event names and imported analytics logic aligned across releases.',
    default: 'fr016_v1',
    example: 'Leave the shipped value unless the app release notes tell you to move to a newer schema.',
    range: 'A supported schema identifier',
  },
  'ga4Telemetry.retention_days': {
    definition: 'How long imported GA4 telemetry should be kept in this app.',
    impact: 'Higher values preserve more history for trend analysis but store more data locally.',
    default: '400',
    example: 'Keep the default unless you need shorter retention for storage or policy reasons.',
    range: '1 to 800 days',
  },
  'ga4Telemetry.impression_visible_ratio': {
    definition: 'The portion of a suggestion card that must be visible before it counts as an impression.',
    impact: 'Higher values avoid counting glancing views, while lower values count impressions earlier.',
    default: '0.5',
    example: '0.5 means roughly half the card should be on screen before the event is sent.',
    range: '0.25 to 1.0',
  },
  'ga4Telemetry.impression_min_ms': {
    definition: 'The minimum on-screen time before an impression event is recorded.',
    impact: 'Prevents very brief scroll-pasts from being treated as meaningful impressions.',
    default: '1000',
    example: '1000 means a card must stay visible for at least one second before it counts.',
    range: '250 to 5000 milliseconds',
  },
  'ga4Telemetry.engaged_min_seconds': {
    definition: 'The minimum active time before a session is treated as engaged for this feature.',
    impact: 'Higher values make engagement stricter. Lower values count shorter visits as meaningful.',
    default: '10',
    example: '10 seconds is a sensible starting point for settings and review workflows.',
    range: '5 to 60 seconds',
  },
  'matomoTelemetry.url': {
    definition: 'The base URL of your Matomo installation.',
    impact: 'The app uses this endpoint to validate access and sync traffic data.',
    default: 'Blank until Matomo is available',
    example: 'Use the root Matomo URL like https://analytics.example.com, not a reporting page URL.',
    range: 'A full URL starting with http:// or https://',
  },
  'matomoTelemetry.site_id_xenforo': {
    definition: 'The Matomo site ID that tracks your XenForo pages.',
    impact: 'Lets the app import forum traffic into the correct telemetry bucket.',
    default: 'Blank until known',
    example: 'Find the numeric site ID in Matomo Admin for the XenForo tracked website.',
    range: 'A Matomo site ID',
  },
  'matomoTelemetry.site_id_wordpress': {
    definition: 'The Matomo site ID that tracks your WordPress site, if it is tracked separately.',
    impact: 'Lets the app import WordPress traffic without mixing it into the XenForo site ID.',
    default: 'Optional',
    example: 'Leave this blank if WordPress traffic is already included under the XenForo site ID or you do not track WordPress in Matomo.',
    range: 'Blank or a Matomo site ID',
  },
  'matomoTelemetry.token_auth': {
    definition: 'The Matomo API token used for authenticated requests.',
    impact: 'Required for connection tests and telemetry imports from Matomo.',
    default: 'Blank until you create one in Matomo',
    example: 'Create or copy a token_auth value from your Matomo user settings, then paste it here once.',
    range: 'A valid Matomo API token',
  },
  'matomoTelemetry.enabled': {
    definition: 'Turns Matomo telemetry collection on or off for this integration.',
    impact: 'When enabled, Matomo becomes an active first-party analytics source for the app.',
    default: 'Off',
    example: 'Enable this after the URL, site IDs, and token have all been saved and tested.',
    range: 'Enabled / Disabled',
  },
  'matomoTelemetry.sync_enabled': {
    definition: 'Turns scheduled Matomo imports on or off.',
    impact: 'When enabled, the app regularly rereads recent Matomo data instead of relying only on manual tests.',
    default: 'Off',
    example: 'Keep this on if Matomo is one of your main traffic sources for ranking and diagnostics.',
    range: 'Enabled / Disabled',
  },
  'matomoTelemetry.sync_lookback_days': {
    definition: 'How many recent days of Matomo data are reread on each sync.',
    impact: 'A short overlap helps refresh delayed updates without creating a very large import window each run.',
    default: '7',
    example: 'Use 7 for a safe default. Increase it if your Matomo data tends to settle slowly.',
    range: '1 to 30 days',
  },
  'siloGroup.name': {
    definition: 'The human-friendly name for this silo group.',
    impact: 'This is the label people see when assigning scopes and reading silo settings.',
    default: 'A short clear label',
    example: 'Good examples: Guides, Troubleshooting, Plugins.',
    range: 'Plain text',
  },
  'siloGroup.slug': {
    definition: 'The short machine name for this silo group.',
    impact: 'Used behind the scenes in saved data and API calls.',
    default: 'A lowercase short code',
    example: 'guides or troubleshooting are good slugs.',
    range: 'Short lowercase text, usually words joined with dashes',
  },
  'siloGroup.description': {
    definition: 'A simple note about what belongs in this group.',
    impact: 'Helps you and future users remember the purpose of the group.',
    default: 'Blank',
    example: 'Use this for pages that teach people how to fix common setup problems.',
    range: 'Short plain-English text',
  },
  'siloGroup.display_order': {
    definition: 'Controls the order the group appears in the settings page.',
    impact: 'Lower numbers show first. This does not change ranking by itself.',
    default: '0',
    example: '0 shows above 10.',
    range: 'Any whole number',
  },
  'scopeAssignment.silo_group': {
    definition: 'Picks which silo bucket a scope belongs to.',
    impact: 'Silo ranking only works when scopes are assigned to groups. Unassigned scopes are ignored by silo rules.',
    default: 'Unassigned',
    example: 'Put all WordPress guides into Guides, and all product docs into Products.',
    range: 'Any existing silo group or Unassigned',
  },
  'tabs.ranking_weights': {
    definition: 'Fine-tune the mathematical weights used to rank link suggestions.',
    impact: 'Changes here directly affect which links the ranker picks as the best matches.',
    default: 'Research-backed defaults',
    example: 'Increase the PageRank weight to favor high-authority pages.',
    range: 'Numerical weights',
  },
  'tabs.silo_architecture': {
    definition: 'Manage topical content silos and scope mapping.',
    impact: 'Controls how content is grouped to prevent irrelevant cross-topic link suggestions.',
    default: 'Silo mapping logic',
    example: 'Assign "Post Type: Guide" to the "Guides" silo.',
    range: 'Group assignments',
  },
  'tabs.wordpress_sync': {
    definition: 'Configure and test the app integrations for WordPress, Google OAuth, GA4, Matomo, and Google Search Console.',
    impact: 'This tab controls how content sync and first-party analytics flow into the platform, so mistakes here affect imports, telemetry, and attribution.',
    default: 'Connection and sync setup',
    example: 'Connect Google once for GA4 and GSC, save WordPress credentials for content sync, and add Matomo only if you use it.',
    range: 'URLs, credentials, toggles, and sync windows',
  },
  'tabs.library_history': {
    definition: 'Save weight presets and view your adjustment history.',
    impact: 'Allows you to experiment with different weights and quickly rollback if needed.',
    default: 'Snapshot library',
    example: 'Save your "Black Friday" weights as a preset.',
    range: 'Presets and logs',
  },
  'informationGain.enabled': {
    definition: 'Turns on information gain scoring, which rewards destinations that add new content the source page does not already cover.',
    impact: 'Enabled computes gain silently alongside other signals. Disabled skips all gain computation and stores a neutral score.',
    default: 'Enabled',
    example: 'Keep enabled so diagnostics run even at weight 0. You can inspect sample novel tokens before raising the weight.',
    range: 'Enabled / Disabled',
  },
  'informationGain.ranking_weight': {
    definition: 'How much the information gain score influences the final ranking.',
    impact: 'Higher values reward destinations that add genuinely new vocabulary the source page does not already contain. This is the complementary signal to semantic similarity — one rewards topic match, this rewards topic novelty.',
    default: '0.03',
    example: '0.03 acts as a light tie-breaker. Raise to 0.05 once diagnostics confirm the signal looks sensible on your content.',
    range: '0 to 0.10',
  },
  'informationGain.min_source_chars': {
    definition: 'The minimum character count the source page body must have before a gain score is computed.',
    impact: 'Pages shorter than this threshold receive a neutral score. Prevents misleading gain scores from very thin source pages with only a few tokens.',
    default: '200',
    example: 'Keep at 200. Lowering below 100 risks gain scores on source pages that are too short to compare meaningfully.',
    range: '50 to 1000',
  },
  'entitySalience.enabled': {
    definition: 'Turns on entity salience matching, which rewards destinations that are built around the same core topics that define the source page.',
    impact: 'Enabled computes salience silently alongside other signals. Disabled skips all salience computation and stores a neutral score.',
    default: 'Enabled',
    example: 'Keep enabled so diagnostics run even at weight 0. Inspect top_salient_terms before raising the weight.',
    range: 'Enabled / Disabled',
  },
  'entitySalience.ranking_weight': {
    definition: 'How much the entity salience match score influences the final ranking.',
    impact: 'Higher values reward destinations that prominently feature the source page\'s most important and distinctive terms — not just topic-adjacent pages that mention the terms in passing.',
    default: '0.04',
    example: '0.04 gives a gentle boost to on-topic destinations. Raise to 0.06 once diagnostics confirm salient terms look meaningful.',
    range: '0 to 0.10',
  },
  'entitySalience.max_salient_terms': {
    definition: 'The maximum number of salient source-page terms extracted for comparison against the destination.',
    impact: 'More terms give a broader signal but may dilute precision. Fewer terms focus only on the most distinctive source topics.',
    default: '10',
    example: 'Lowering to 5 focuses on only the strongest salient terms. Raising to 20 broadens the comparison but includes weaker signals.',
    range: '3 to 25',
  },
  'entitySalience.max_site_document_frequency': {
    definition: 'A term must appear in no more than this many pages site-wide to qualify as salient for the source page.',
    impact: 'Lower values restrict salience to very distinctive terms. Higher values allow moderately common terms to qualify.',
    default: '20',
    example: 'Lowering to 5 extracts only very rare, highly distinctive terms. Raising to 50 includes terms that appear on many pages and may be too generic.',
    range: '5 to 100',
  },
  'entitySalience.min_source_term_frequency': {
    definition: 'A term must appear at least this many times within the source page itself to be considered salient.',
    impact: 'Higher values require terms to be repeatedly emphasised in the source. Lower values pick up any term that survives the site-frequency filter.',
    default: '2',
    example: 'Raising to 3 requires terms to be mentioned at least three times. Lowering to 1 picks up any term that survives the site-frequency filter.',
    range: '1 to 5',
  },
  'multimediaSignal.enabled': {
    definition: 'Turns on multimedia richness scoring, which rewards destinations with better video, image, and alt-text coverage.',
    impact: 'Enabled computes the multimedia signal from stored HTML-extraction metadata. Disabled skips that signal and falls back to the neutral value.',
    default: 'Enabled',
    example: 'Keep enabled so visually rich destinations can benefit once FR-040 is implemented. Disable only if multimedia extraction is unavailable or too noisy.',
    range: 'Enabled / Disabled',
  },
  'multimediaSignal.ranking_weight': {
    definition: 'How much the multimedia richness signal influences the value-model score.',
    impact: 'Higher values make pages with helpful videos, descriptive images, and strong alt-text coverage more attractive as destinations.',
    default: '0.10',
    example: '0.10 gives multimedia a meaningful supporting role. Raising far above this can over-reward pretty pages that are not the best semantic match.',
    range: '0 to 0.20',
  },
  'multimediaSignal.fallback_value': {
    definition: 'The neutral score used when multimedia metadata is missing for a destination.',
    impact: 'Higher values make missing metadata almost harmless. Lower values effectively punish pages that have not been re-synced yet.',
    default: '0.5',
    example: 'Keep at 0.5 so pages without extracted metadata remain neutral until the next sync.',
    range: '0 to 1',
  },
  'originalityProvenance.enabled': {
    definition: 'Turns on originality provenance scoring, which prefers the earliest and most source-like page inside a family of near-duplicate pages.',
    impact: 'Enabled computes provenance diagnostics and origin preference. Disabled skips provenance analysis and stores a neutral score.',
    default: 'Enabled',
    example: 'Keep enabled so provenance diagnostics are available even while the ranking weight remains conservative.',
    range: 'Enabled / Disabled',
  },
  'originalityProvenance.ranking_weight': {
    definition: 'How much originality provenance influences the final ranking.',
    impact: 'Higher values make historically primary pages win more often against reposts, mirrors, or lightly rewritten copies.',
    default: '0.03',
    example: '0.03 is a gentle tie-breaker. Raise carefully only after verifying that provenance families and timestamps look trustworthy.',
    range: '0 to 0.10',
  },
  'originalityProvenance.resemblance_threshold': {
    definition: 'The minimum shingle-overlap resemblance required before two pages are treated as belonging to the same provenance family.',
    impact: 'Lower values group more pages together. Higher values require pages to be much closer lexical matches before provenance logic activates.',
    default: '0.55',
    example: 'Keep near 0.55 for broad near-copy detection. Raising toward 0.75 makes the signal much stricter and more clone-focused.',
    range: '0.30 to 0.90',
  },
  'originalityProvenance.containment_threshold': {
    definition: 'The minimum containment score required before one page is treated as substantially contained within another provenance family member.',
    impact: 'Higher values make partial-copy detection stricter. Lower values catch more derivative pages but risk over-grouping.',
    default: '0.80',
    example: 'Keep near 0.80 so derivative pages must substantially include another page before provenance support activates.',
    range: '0.50 to 0.95',
  },
  'factDensity.enabled': {
    definition: 'Turns on fact density scoring, which rewards destinations that contain more concrete facts relative to their length.',
    impact: 'Enabled computes a text-density quality signal. Disabled skips density analysis and stores a neutral score.',
    default: 'Enabled',
    example: 'Keep enabled so the signal can run in shadow mode while you inspect whether it behaves well on forum and article content.',
    range: 'Enabled / Disabled',
  },
  'factDensity.ranking_weight': {
    definition: 'How much fact density influences the final ranking.',
    impact: 'Higher values reward pages that pack more concrete, verifiable information into fewer words and reduce the impact of fluffy pages.',
    default: '0.04',
    example: '0.04 gives density a useful quality voice without letting it overpower topical relevance.',
    range: '0 to 0.10',
  },
  'factDensity.min_word_count': {
    definition: 'The minimum destination word count required before a fact-density score is computed.',
    impact: 'Pages shorter than this stay neutral. Higher values reduce noisy scores on thin pages; lower values score more of the corpus.',
    default: '120',
    example: 'Keep around 120 so tiny blurbs and stub pages do not get misleading density scores.',
    range: '50 to 400',
  },
  'factDensity.density_cap_per_100_words': {
    definition: 'The maximum effective fact count per 100 words before the score saturates.',
    impact: 'Lower values make dense pages hit the top score faster. Higher values spread out the score across a wider range of factual writing styles.',
    default: '8.0',
    example: '8.0 treats very information-dense how-to or product pages as strong performers without making normal prose impossible to score well.',
    range: '2 to 20',
  },
  'factDensity.filler_penalty_weight': {
    definition: 'How strongly filler-heavy sentences reduce the final fact-density score.',
    impact: 'Higher values punish vague or padded writing more aggressively. Lower values let density dominate even when some filler is present.',
    default: '0.35',
    example: '0.35 trims obvious filler without turning a few soft sentences into a major penalty.',
    range: '0 to 1',
  },
  'semanticDrift.enabled': {
    definition: 'Turns on semantic drift analysis, which penalizes destinations that start on-topic but drift into unrelated material later.',
    impact: 'Enabled computes drift diagnostics and a bounded penalty score. Disabled skips drift analysis and stores a neutral value.',
    default: 'Enabled',
    example: 'Keep enabled so you can inspect drift diagnostics before letting the penalty affect ranking.',
    range: 'Enabled / Disabled',
  },
  'semanticDrift.ranking_weight': {
    definition: 'How strongly semantic drift subtracts from the final ranking.',
    impact: 'Higher values punish pages that lose topical focus as they progress. Lower values keep drift as a light quality guardrail.',
    default: '0.03',
    example: '0.03 keeps drift lighter than the fact-density boost, which is safer because penalties are felt as regressions faster than boosts.',
    range: '0 to 0.10',
  },
  'semanticDrift.tokens_per_sequence': {
    definition: 'The token count used for each low-level sequence before larger drift-analysis blocks are formed.',
    impact: 'Smaller values make the signal more sensitive to local topic shifts. Larger values smooth out noise but may miss short drift events.',
    default: '20',
    example: '20 is a balanced starting point. Lowering too far makes chatter and quoted fragments look like drift.',
    range: '10 to 60',
  },
  'semanticDrift.block_size_in_sequences': {
    definition: 'How many token sequences are combined into each comparison block for drift analysis.',
    impact: 'Higher values create smoother, more stable topic blocks. Lower values make the signal react faster but increase noise.',
    default: '6',
    example: '6 provides enough context for stable segmentation on long forum and article pages without making blocks too large.',
    range: '3 to 12',
  },
  'semanticDrift.anchor_similarity_threshold': {
    definition: 'The minimum similarity a later segment must retain to the opening anchor segment before it is marked as drifted.',
    impact: 'Higher values make the penalty stricter. Lower values tolerate broader topic expansion before drift is recorded.',
    default: '0.18',
    example: '0.18 is lenient enough for related subsections but still catches pages that wander into a different subject entirely.',
    range: '0.05 to 0.40',
  },
  'semanticDrift.min_word_count': {
    definition: 'The minimum destination word count required before semantic drift is analyzed.',
    impact: 'Short pages stay neutral. Higher values reduce false positives on brief content; lower values attempt drift scoring on more pages.',
    default: '180',
    example: 'Keep around 180 so short threads, notices, and stubs do not get forced through topic-segmentation logic.',
    range: '80 to 500',
  },
  'internalSearch.enabled': {
    definition: 'Turns on internal-search intensity scoring, which rewards destinations matching topics users are actively searching for inside the site.',
    impact: 'Enabled computes a burst-aware demand signal from aggregate internal-search queries. Disabled skips that analysis and stores a neutral score.',
    default: 'Enabled',
    example: 'Keep enabled so the signal can run in shadow mode while you validate the quality of query matching.',
    range: 'Enabled / Disabled',
  },
  'internalSearch.ranking_weight': {
    definition: 'How much internal-search intensity influences the final ranking.',
    impact: 'Higher values favor destinations tied to currently high-demand internal search topics. Lower values keep search demand as a subtle freshness signal.',
    default: '0.02',
    example: '0.02 is intentionally light because search-demand spikes can be noisy until query matching is proven on real content.',
    range: '0 to 0.08',
  },
  'internalSearch.recent_days': {
    definition: 'The number of most-recent days used to measure current internal-search demand.',
    impact: 'Smaller windows react faster to short-lived spikes. Larger windows smooth demand and make the signal slower but steadier.',
    default: '3',
    example: '3 days catches short bursts of user interest without making the signal too jumpy hour-to-hour.',
    range: '1 to 14',
  },
  'internalSearch.baseline_days': {
    definition: 'The longer baseline window used to judge whether recent internal-search demand is unusually high.',
    impact: 'Larger baselines make burst detection stricter and more stable. Smaller baselines react faster but can misread normal fluctuations as spikes.',
    default: '28',
    example: '28 days is a good monthly baseline for detecting genuine lifts above normal search demand.',
    range: '7 to 90',
  },
  'internalSearch.max_active_queries': {
    definition: 'The maximum number of high-intensity internal-search queries kept in the active scoring set.',
    impact: 'Higher values broaden coverage but increase matching noise and compute cost. Lower values focus only on the strongest current topics.',
    default: '200',
    example: '200 keeps the active set broad enough for medium-size sites without letting long-tail noise dominate.',
    range: '20 to 1000',
  },
  'internalSearch.min_recent_count': {
    definition: 'The minimum recent search count a query must have before it is considered active for scoring.',
    impact: 'Higher values filter out one-off queries. Lower values make the signal more sensitive but noisier.',
    default: '3',
    example: '3 is a practical floor that filters accidental one-offs while still allowing emerging topics to appear.',
    range: '1 to 20',
  },
  'anchorDiversity.enabled': {
    definition: 'Turns on FR-045, which demotes repeated exact-match anchors pointing at the same destination.',
    impact: 'Enabled reduces over-optimized anchor repetition. Disabled leaves that risk to the older spam guards only.',
    default: 'Enabled',
    example: 'Keep enabled for normal production use so anchor reuse stays natural.',
    range: 'Enabled / Disabled',
  },
  'anchorDiversity.ranking_weight': {
    definition: 'How strongly FR-045 penalises repeated exact-match anchor reuse.',
    impact: 'Higher values demote repetitive exact-match anchors more aggressively. Lower values keep the penalty gentle.',
    default: '0.03',
    example: '0.03 is conservative. Raising to 0.06 makes the system much less tolerant of exact-match reuse.',
    range: '0 to 0.25',
  },
  'anchorDiversity.min_history_count': {
    definition: 'Minimum active suggestion history required before FR-045 starts scoring anchor reuse.',
    impact: 'Higher values keep low-data destinations neutral for longer. Lower values start judging reuse sooner.',
    default: '3',
    example: 'Set to 5 if you want sparse destinations to stay neutral until more history exists.',
    range: '1 to 50',
  },
  'anchorDiversity.max_exact_match_share': {
    definition: 'Maximum safe share of active suggestions using the same exact anchor for one destination.',
    impact: 'Lower values trigger penalties earlier. Higher values tolerate more exact-match reuse.',
    default: '0.40',
    example: 'Lowering to 0.25 makes the ranker diversify anchors sooner.',
    range: '0.05 to 1.0',
  },
  'anchorDiversity.max_exact_match_count': {
    definition: 'Maximum safe count of active exact-match suggestions before FR-045 penalises the candidate.',
    impact: 'Lower values curb repeated anchors earlier. Higher values allow more reuse before penalties apply.',
    default: '3',
    example: 'Three is a balanced starting point for manual-review workflows.',
    range: '1 to 50',
  },
  'anchorDiversity.hard_cap_enabled': {
    definition: 'Allows FR-045 to hard-block extreme exact-match reuse instead of only demoting it.',
    impact: 'Enabled is stricter and may suppress some relevant candidates. Disabled stays soft-penalty-first.',
    default: 'Disabled',
    example: 'Leave off unless you want the system to reject extreme anchor repetition outright.',
    range: 'Enabled / Disabled',
  },
  'fanOut.enabled': {
    definition: 'Whether multi-query fan-out is used for Stage 1 candidate retrieval.',
    impact: 'Decomposes multi-topic destinations into segments and runs separate searches, finding candidates single-vector search would miss.',
    default: 'true',
    example: 'Disable if your content is short and single-topic.',
    range: 'on / off',
  },
  'fanOut.max_sub_queries': {
    definition: 'Maximum number of segments per destination to decompose into separate queries.',
    impact: 'Higher values capture more sub-topics but increase retrieval cost.',
    default: '3',
    example: '3 covers title + intro + body. Raise to 5 for very long, multi-section articles.',
    range: '1 to 5',
  },
  'fanOut.min_segment_words': {
    definition: 'Minimum words for a body segment to qualify as a sub-query.',
    impact: 'Prevents tiny fragments from generating noisy retrieval results.',
    default: '50',
    example: 'Lower to 30 if your pages have many short but distinct sections.',
    range: '20 to 200',
  },
  'fanOut.rrf_k': {
    definition: 'RRF smoothing constant (Cormack et al. 2009 standard) for merging sub-query results.',
    impact: 'Higher values give more weight to lower-ranked results when merging.',
    default: '60',
    example: '60 is the standard default. Lower to 30 to favour top-ranked results more.',
    range: '10 to 120',
  },
  'navigationPath.enabled': {
    definition: 'Whether Markov transition data from GA4 page-view sequences is used for scoring.',
    impact: 'Pages users already navigate toward get a ranking boost.',
    default: 'true',
    example: 'Disable if you have no GA4 session data.',
    range: 'on / off',
  },
  'navigationPath.ranking_weight': {
    definition: 'How much navigation-path prediction contributes to the final score.',
    impact: 'Higher values favour destinations users are already trying to reach.',
    default: '0.04',
    example: 'Raise to 0.06 after confirming transition counts are stable across pipeline runs.',
    range: '0 to 0.15',
  },
  'navigationPath.lookback_days': {
    definition: 'Historical window of GA4 sessions used to build transition matrices.',
    impact: 'Longer windows are more stable but slower to adapt to changed navigation patterns.',
    default: '90',
    example: '30 for a fast-changing site, 90 for stable content.',
    range: '7 to 365',
  },
  'navigationPath.min_sessions': {
    definition: 'Minimum sessions before computing transition probabilities for a page.',
    impact: 'Higher values require stronger evidence but may exclude low-traffic pages.',
    default: '50',
    example: 'Lower to 20 on smaller sites with fewer sessions.',
    range: '5 to 500',
  },
  'navigationPath.min_transition_count': {
    definition: 'Minimum observed page-to-page transitions before scoring a link.',
    impact: 'Filters noise from rare or accidental navigation paths.',
    default: '5',
    example: 'Raise to 10 on high-traffic sites for stronger signal quality.',
    range: '1 to 50',
  },
  'navigationPath.w_direct': {
    definition: 'Weight for direct (one-hop) page-to-page transitions.',
    impact: 'Higher values prefer links that match immediate next-page navigation.',
    default: '0.6',
    example: 'Keep higher than w_shortcut since direct transitions are more reliable.',
    range: '0 to 1',
  },
  'navigationPath.w_shortcut': {
    definition: 'Weight for multi-hop shortcut navigation patterns.',
    impact: 'Higher values reward links that skip intermediate pages users commonly traverse.',
    default: '0.4',
    example: 'Raise if your site has deep navigation hierarchies.',
    range: '0 to 1',
  },
  'topicalCluster.enabled': {
    definition: 'Whether HDBSCAN topic clustering is used to boost destinations in dense topic areas.',
    impact: 'Destinations in large, well-covered topic clusters score higher.',
    default: 'true',
    example: 'Disable on very small sites where clustering is not meaningful.',
    range: 'on / off',
  },
  'topicalCluster.ranking_weight': {
    definition: 'How much topical cluster density contributes to the final score.',
    impact: 'Higher values favour destinations where the site has demonstrated topical depth.',
    default: '0.04',
    example: 'Raise to 0.06 after verifying HDBSCAN produces stable, meaningful clusters.',
    range: '0 to 0.15',
  },
  'topicalCluster.min_cluster_size': {
    definition: 'Minimum pages required to form a recognized topic cluster.',
    impact: 'Prevents tiny noise clusters from inflating authority scores.',
    default: '5',
    example: 'Raise to 10 on large sites with 1000+ pages.',
    range: '2 to 50',
  },
  'topicalCluster.min_site_pages': {
    definition: 'Minimum total site pages needed for clustering to activate.',
    impact: 'Prevents clustering on sites too small for meaningful topic grouping.',
    default: '20',
    example: 'The signal stays neutral until your site crosses this threshold.',
    range: '5 to 200',
  },
  'topicalCluster.max_staleness_days': {
    definition: 'Days before cluster assignments are considered stale and need recomputation.',
    impact: 'Shorter values keep clusters fresh but increase compute cost.',
    default: '14',
    example: '7 for fast-growing sites, 30 for stable content libraries.',
    range: '1 to 90',
  },
  'topicalCluster.fallback_value': {
    definition: 'Score assigned when clustering data is unavailable for a destination.',
    impact: 'New or unclustered pages receive this neutral value.',
    default: '0.5',
    example: '0.5 is neutral — neither boosts nor penalises.',
    range: '0 to 1',
  },
  'intentFunnel.enabled': {
    definition: 'Whether GSC query-intent classification is used to boost funnel-aligned links.',
    impact: 'Links that move users one stage forward through the buyer journey score higher.',
    default: 'true',
    example: 'Disable if your site is purely informational with no commercial funnel.',
    range: 'on / off',
  },
  'intentFunnel.ranking_weight': {
    definition: 'How much funnel alignment contributes to the final score.',
    impact: 'Higher values strongly prefer links that guide users toward conversion.',
    default: '0.03',
    example: 'Raise to 0.05 after validating that intent classification is stable.',
    range: '0 to 0.15',
  },
  'intentFunnel.optimal_offset': {
    definition: 'Ideal stage distance between source and destination (1 = one stage forward).',
    impact: 'Links matching this offset get the maximum funnel alignment bonus.',
    default: '1',
    example: 'Keep at 1 for standard one-step-forward funnel progression.',
    range: '1 to 3',
  },
  'intentFunnel.sigma': {
    definition: 'Gaussian width controlling penalty for non-optimal funnel distances.',
    impact: 'Smaller values penalise distant stage jumps more harshly.',
    default: '1.2',
    example: 'Lower to 0.8 if you want strict one-stage-forward enforcement.',
    range: '0.3 to 3.0',
  },
  'intentFunnel.min_confidence': {
    definition: 'Minimum classification confidence for intent scoring to apply.',
    impact: 'Pages with low-confidence classification fall back to neutral scoring.',
    default: '0.25',
    example: 'Raise to 0.5 if you see too many misclassified pages affecting ranking.',
    range: '0 to 1',
  },
  'intentFunnel.navigational_confidence_threshold': {
    definition: 'Confidence threshold for opting navigational pages out of funnel scoring.',
    impact: 'Navigational queries (brand searches, homepage) are excluded above this confidence.',
    default: '0.6',
    example: 'Lower to 0.4 if navigational queries are rare on your site.',
    range: '0 to 1',
  },
  'seasonality.enabled': {
    definition: 'Whether seasonal traffic patterns are used to boost time-relevant destinations.',
    impact: 'Destinations whose annual peak is approaching or active score higher.',
    default: 'true',
    example: 'Disable on sites with no seasonal content patterns.',
    range: 'on / off',
  },
  'seasonality.ranking_weight': {
    definition: 'How much seasonal demand matching contributes to the final score.',
    impact: 'Higher values strongly prefer destinations aligned with current seasonal demand.',
    default: '0.03',
    example: 'Raise to 0.05 after confirming seasonal_strength separates seasonal from perennial pages.',
    range: '0 to 0.15',
  },
  'seasonality.min_history_months': {
    definition: 'Minimum months of GA4/GSC history needed to fit a seasonal model.',
    impact: 'Ensures enough data points for reliable annual pattern detection.',
    default: '12',
    example: '12 months gives a full annual cycle. 18 is safer for noisy data.',
    range: '6 to 36',
  },
  'seasonality.min_seasonal_strength': {
    definition: 'Minimum seasonal variance ratio to classify a page as seasonal.',
    impact: 'Pages below this threshold are treated as perennial (no seasonal boost).',
    default: '0.3',
    example: 'Lower to 0.2 if you want more pages to qualify for seasonal scoring.',
    range: '0.1 to 0.8',
  },
  'seasonality.anticipation_window_months': {
    definition: 'Months before a page\'s seasonal peak to start applying an anticipation bonus.',
    impact: 'Lets you link to seasonal content before demand peaks, not just during.',
    default: '3',
    example: '3 months means holiday content starts getting boosted in September.',
    range: '1 to 6',
  },
  'seasonality.w_current': {
    definition: 'Weight for the current month\'s seasonal index value.',
    impact: 'Higher values make the score track the current seasonal cycle closely.',
    default: '0.7',
    example: 'Keep higher than w_anticipation to anchor scoring in observed demand.',
    range: '0 to 1',
  },
  'seasonality.w_anticipation': {
    definition: 'Weight for the approaching-peak anticipation bonus.',
    impact: 'Higher values boost pages earlier before their seasonal peak.',
    default: '0.3',
    example: 'Raise to 0.5 if you want aggressive early linking to seasonal content.',
    range: '0 to 1',
  },
  'seasonality.index_cap': {
    definition: 'Cap on the seasonal index to prevent extreme spikes from dominating.',
    impact: 'Clamps the seasonal multiplier so no single month can overwhelm other signals.',
    default: '3.0',
    example: 'Lower to 2.0 if your site has very spiky seasonal patterns.',
    range: '1.5 to 10.0',
  },
  'darb.enabled': {
    definition: 'FR-099 DARB: turns on the "dangling hoarder" boost for high-value hosts that have few outbound links.',
    impact: 'Enabled adds a small boost to candidates from hosts that are strong pages but barely link out. Disabled turns the feature off.',
    default: 'On',
    example: 'Leave on — the boost is tiny but fixes the classic "dead-end street" SEO problem in the Reddit post.',
    range: 'On / Off',
  },
  'darb.ranking_weight': {
    definition: 'How strongly the DARB bonus contributes to the final score.',
    impact: 'Higher values push harder to route juice out of hoarder hosts. Zero disables the boost without turning off the signal.',
    default: '0.04',
    example: '0.04 is a gentle nudge. Raise to 0.08 if your site has many high-traffic posts with no outbound links.',
    range: '0 to 0.15',
  },
  'darb.out_degree_saturation': {
    definition: 'Minimum outbound links above which a host is no longer considered "dangling".',
    impact: 'Lower values mean only very sparse hosts qualify; higher values widen the boost to hosts with a few existing links.',
    default: '5',
    example: 'Raising to 8 makes the boost fire on more hosts. Broder et al. 2000 median out-degree is 8.',
    range: '1 to 20',
  },
  'darb.min_host_value': {
    definition: 'Minimum host content_value_score (GSC+GA4+PageRank composite) required to trigger the boost.',
    impact: 'Higher values restrict the boost to high-quality hosts only. 0.5 is neutral.',
    default: '0.5',
    example: 'Raise to 0.7 if you want only your very best pages to benefit from the boost.',
    range: '0 to 1',
  },
  'kmig.enabled': {
    definition: 'FR-100 KMIG: penalises candidates already reachable within 1-2 hops via existing links.',
    impact: 'Enabled discourages duplicate-line edges. Disabled ignores graph reachability redundancy.',
    default: 'On',
    example: 'Keep on — prevents the ranker from suggesting redundant edges that add no new information.',
    range: 'On / Off',
  },
  'kmig.ranking_weight': {
    definition: 'How strongly the Katz marginal-information-gain signal contributes.',
    impact: 'Higher values punish "we already have a path there" more aggressively.',
    default: '0.05',
    example: '0.05 is the Salton-Buckley magnitude band. Raise to 0.10 on densely-linked sites.',
    range: '0 to 0.15',
  },
  'kmig.attenuation': {
    definition: 'Katz attenuation β for the 2-hop reachability sum.',
    impact: 'Lower β emphasises direct edges; higher β weights 2-hop paths more.',
    default: '0.5',
    example: 'Pigueiral 2017 validates 0.5 for truncated Katz. Only tune if you fully understand Katz centrality.',
    range: '0.1 to 0.9',
  },
  'kmig.max_hops': {
    definition: 'Max path length used in the truncated Katz sum. Higher values blow RAM; we truncate at 2.',
    impact: 'Raising above 2 makes the signal much slower with minimal score impact.',
    default: '2',
    example: 'Leave at 2. Raising to 3 roughly 15x the per-pipeline RAM cost for a 50k-node graph.',
    range: '1 to 3',
  },
  'tapb.enabled': {
    definition: 'FR-101 TAPB: boosts candidates whose host is a structural cut vertex (articulation point).',
    impact: 'Enabled rewards hosts that bridge otherwise-disconnected graph regions. Disabled ignores cut-vertex topology.',
    default: 'On',
    example: 'Leave on — articulation-point hosts are rare (~5-8%) so the boost rarely fires but is valuable when it does.',
    range: 'On / Off',
  },
  'tapb.ranking_weight': {
    definition: 'How much the cut-vertex host boost contributes.',
    impact: 'Higher values strongly reward bridge-style hosts.',
    default: '0.03',
    example: '0.03 matches link_farm magnitude band for rare-event structural signals.',
    range: '0 to 0.10',
  },
  'tapb.apply_to_articulation_node_only': {
    definition: 'When on, only exact articulation points trigger the boost; off enables a graded boost on near-articulation nodes.',
    impact: 'On keeps the signal conservative. Off (future option) would widen the boost.',
    default: 'On',
    example: 'Keep on for v1. The graded variant is a future extension.',
    range: 'On / Off',
  },
  'kcib.enabled': {
    definition: 'FR-102 KCIB: rewards links from high-kcore hosts to low-kcore destinations, pulling peripheral pages into the core.',
    impact: 'Enabled actively integrates peripheral content. Disabled leaves the graph topology alone.',
    default: 'On',
    example: 'Keep on — especially useful for sites with deep long-tail content that rarely gets linked.',
    range: 'On / Off',
  },
  'kcib.ranking_weight': {
    definition: 'How strongly the k-core integration boost contributes.',
    impact: 'Higher values more aggressively pull peripheral pages into the core.',
    default: '0.03',
    example: '0.03 matches the link_farm rarity magnitude band.',
    range: '0 to 0.10',
  },
  'kcib.min_kcore_spread': {
    definition: 'Minimum host.kcore - dest.kcore gap needed to fire the boost.',
    impact: 'Lower values let smaller core-gaps trigger; higher values restrict the boost to clearly hub-to-periphery links.',
    default: '1',
    example: '1 is the smallest meaningful step. Raise to 3 to only reward big integration jumps.',
    range: '1 to 10',
  },
  'berp.enabled': {
    definition: 'FR-103 BERP: penalises candidates where host->dest would become a new bridge edge (fragile single-path connector).',
    impact: 'Enabled discourages creating structural single points of failure. Disabled ignores bridge-edge topology.',
    default: 'On',
    example: 'Leave on — multi-path resilience is generally healthier than narrow bridges.',
    range: 'On / Off',
  },
  'berp.ranking_weight': {
    definition: 'How strongly the would-be-bridge penalty subtracts from the score.',
    impact: 'Higher values punish would-be bridges harder.',
    default: '0.04',
    example: '0.04 matches the keyword_stuffing penalty magnitude.',
    range: '0 to 0.15',
  },
  'berp.min_component_size': {
    definition: 'Minimum biconnected-component size before the penalty fires. Smaller components are treated as noise.',
    impact: 'Higher values keep the penalty restricted to meaningfully-large components.',
    default: '5',
    example: 'Seidman 1983 small-component discussion. Raise to 10 on very small sites.',
    range: '2 to 20',
  },
  'hgte.enabled': {
    definition: 'FR-104 HGTE: rewards candidates that increase the Shannon entropy of the host\'s outbound silo distribution.',
    impact: 'Enabled diversifies host portfolios. Disabled ignores portfolio topic-distribution health.',
    default: 'On',
    example: 'Keep on to prevent hosts from becoming topically monotone over time.',
    range: 'On / Off',
  },
  'hgte.ranking_weight': {
    definition: 'How strongly the entropy-delta boost contributes.',
    impact: 'Higher values strongly reward diversifying links.',
    default: '0.04',
    example: '0.04 matches the rare_term_propagation magnitude band.',
    range: '0 to 0.10',
  },
  'hgte.min_host_out_degree': {
    definition: 'Minimum number of outbound links the host must have before entropy is computed at all (too few links = noisy entropy).',
    impact: 'Higher values mean only well-linked hosts trigger the signal.',
    default: '3',
    example: 'Shannon 1948 asymptotic reliability discussion. 3 is the minimum meaningful.',
    range: '2 to 10',
  },
  'rsqva.enabled': {
    definition: 'FR-105 RSQVA: TF-IDF cosine between host\'s and destination\'s GSC query vocabularies. High overlap = same search intent.',
    impact: 'Enabled rewards user-intent-aligned pairs even when body text differs. Disabled ignores GSC query vocabularies.',
    default: 'On',
    example: 'Keep on — this catches topically-related pairs that embeddings miss.',
    range: 'On / Off',
  },
  'rsqva.ranking_weight': {
    definition: 'How strongly GSC query-vocabulary alignment contributes.',
    impact: 'Higher values treat GSC query overlap as a stronger relevance signal.',
    default: '0.05',
    example: '0.05 matches the ga4_gsc magnitude band.',
    range: '0 to 0.15',
  },
  'rsqva.min_queries_per_page': {
    definition: 'Minimum GSC queries a page must have to participate in the alignment signal.',
    impact: 'Higher values exclude more low-traffic pages; lower values let noisy vocabularies participate.',
    default: '5',
    example: 'Salton-Buckley 1988 §3.2 reliability floor. Below 5 the TF-IDF vector is noise.',
    range: '3 to 20',
  },
  'rsqva.min_query_clicks': {
    definition: 'Minimum clicks a query must have to count in the TF-IDF aggregation.',
    impact: 'Higher values exclude impression-only queries; 1 keeps all converting queries.',
    default: '1',
    example: 'Keep at 1. Järvelin-Kekäläinen 2002 click-weighted CG framework motivates click-gating.',
    range: '1 to 10',
  },
  'rsqva.max_vocab_size': {
    definition: 'Hard cap on the number of distinct query terms tracked per page.',
    impact: 'Larger caps handle broader vocabularies; hashing collisions remain bounded.',
    default: '10000',
    example: 'Leave at 10000. Smaller sites won\'t hit the cap; very large sites benefit from the upper bound.',
    range: '1000 to 50000',
  },
};
