"""Small deterministic helpers for generated Bazel files."""

from __future__ import annotations

from pathlib import Path

HEADER = "# Generated by scripts/gen_bazel_*.py; edit the generator instead.\n"


def render_exports_files(paths: list[str]) -> str:
    """Render an exports_files block with stable ordering."""
    unique = sorted({path.replace("\\", "/") for path in paths if path.strip()})
    if not unique:
        return HEADER
    lines = [HEADER, "exports_files(["]
    lines.extend(f'    "{path}",' for path in unique)
    lines.append("])")
    return "\n".join(lines) + "\n"


def write_if_changed(path: Path, content: str) -> bool:
    """Write content only when bytes changed, returning true on update."""
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8", newline="\n")
    return True
