# Generated by Django 5.2.13 on 2026-05-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTrailEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', help_text='SHA1-16 of (category, normalised title, linked_autoissue_id). Exact-match dedup.', max_length=16)),
                ('canonical_fingerprint', models.CharField(blank=True, db_index=True, default='', help_text='SHA1-16 of normalised title alone. Cross-content dedup key for fast SQL filtering.', max_length=16)),
                ('category', models.CharField(choices=[('autoissue_deferral', 'AutoIssue deferral'), ('cve_upgrade', 'CVE upgrade'), ('coverage_gap', 'Coverage gap'), ('infrastructure', 'Infrastructure'), ('ruff_sweep', 'Ruff sweep'), ('mutation_survivor', 'Mutation survivor'), ('debt_reduction', 'Debt reduction'), ('feature_decision', 'Feature decision'), ('tooling_gap', 'Tooling gap'), ('documentation', 'Documentation'), ('dependency_upgrade', 'Dependency upgrade'), ('refactor', 'Refactor'), ('performance', 'Performance'), ('security', 'Security'), ('accessibility', 'Accessibility'), ('other', 'Other')], db_index=True, max_length=24)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=12)),
                ('title', models.CharField(max_length=512)),
                ('abstract', models.TextField(help_text='High-detail explanation of why this work was deferred. Hard-capped at 600 words.', max_length=4500)),
                ('next_actions', models.JSONField(blank=True, default=list)),
                ('affected_files', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('picked', 'Picked'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('wontfix', 'Wontfix'), ('duplicate', 'Duplicate')], db_index=True, default='open', max_length=16)),
                ('deferred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deferred_by', models.CharField(max_length=64)),
                ('deferred_in_handoff', models.CharField(blank=True, default='', max_length=24)),
                ('deferral_reason_key', models.CharField(blank=True, default='', max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=64)),
                ('resolution_lessons', models.TextField(blank=True, default='')),
                ('resolution_commit_sha', models.CharField(blank=True, default='', max_length=40)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('linked_autoissue_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('linked_registry_id', models.CharField(blank=True, default='', max_length=24)),
                ('linked_commit_sha', models.CharField(blank=True, default='', max_length=40)),
                ('priority_score', models.FloatField(db_index=True, default=0.0)),
                ('estimated_hours', models.FloatField(default=0.0)),
                ('complexity_bucket', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=4)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('resource_needs', models.JSONField(blank=True, default=list)),
                ('risk_on_inaction', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.5)),
                ('resolution_criteria', models.TextField(blank=True, default='')),
                ('related_entry_ids', models.JSONField(blank=True, default=list)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal')], default='internal', max_length=12)),
                ('suppression_reason', models.TextField(blank=True, default='')),
                ('suppression_approver', models.CharField(blank=True, default='', max_length=64)),
                ('history', models.JSONField(blank=True, default=list)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'severity', 'category'], name='paper_trail_status_f1a0df_idx'), models.Index(fields=['canonical_fingerprint'], name='paper_trail_canonic_91bfe6_idx'), models.Index(fields=['deferred_at'], name='paper_trail_deferre_462464_idx'), models.Index(fields=['linked_autoissue_id'], name='paper_trail_linked__f10a8f_idx'), models.Index(fields=['priority_score'], name='paper_trail_priorit_6b0631_idx'), models.Index(fields=['last_seen'], name='paper_trail_last_se_11ec14_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'picked', 'in_progress'))), fields=('category', 'fingerprint'), name='uniq_papertrail_active_category_fingerprint')],
            },
        ),
    ]
