# Generated by Django 5.2.13 on 2026-05-15 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trail', '0002_alter_papertrailentry_abstract'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='papertrailentry',
            name='uniq_papertrail_active_category_fingerprint',
        ),
        migrations.AddField(
            model_name='papertrailentry',
            name='acceptance_criteria',
            field=models.TextField(blank=True, default='', help_text='Bullet list or short paragraph naming the concrete checks that prove this entry can be marked resolved. Required on all NEW entries (2026-05-16+); existing rows grandfathered.'),
        ),
        migrations.AddField(
            model_name='papertrailentry',
            name='evidence_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('cited', 'Cited (patent / DOI / RFC / URL)')], db_index=True, default='low', help_text="How well-grounded the entry's claims are. `cited` requires a patent / DOI / RFC / stable URL in the abstract.", max_length=10),
        ),
        migrations.AddField(
            model_name='papertrailentry',
            name='integrity_check_result',
            field=models.TextField(blank=True, default='', help_text='Result of the duplicate / stale / conflict search the filing agent performed before creating this entry. Auto-populated by manage.py defer_work.'),
        ),
        migrations.AddField(
            model_name='papertrailentry',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='Newer entry that replaces this one. Set via manage.py link_paper_trail_supersedes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='paper_trail.papertrailentry'),
        ),
        migrations.AlterField(
            model_name='papertrailentry',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('picked', 'Picked'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('deferred', 'Deferred'), ('resolved', 'Resolved'), ('wontfix', 'Wontfix'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('stale', 'Stale'), ('superseded', 'Superseded')], db_index=True, default='open', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='papertrailentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'picked', 'in_progress', 'blocked', 'deferred'))), fields=('category', 'fingerprint'), name='uniq_papertrail_active_category_fingerprint'),
        ),
    ]
