# Generated by Django 5.2.14 on 2026-05-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trail", "0005_add_sticky_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papertrailentry",
            name="abstract",
            field=models.TextField(
                help_text=(
                    "High-detail explanation of the work being tracked. "
                    "Hard-capped at 10,000 words (raised 2026-05-23 from 1,200 "
                    "to accommodate the new 5-phase workflow). NEW entries MUST "
                    "be written in BDD style: contain a `Given ...`, `When ...`, "
                    "and `Then ...` section so the entry has a self-contained "
                    "test-shape the next agent can read as an acceptance spec. "
                    "Existing pre-2026-05-16 abstracts are grandfathered. "
                    "Long-form spec text now lives inline in the abstract or in "
                    "a referenced docs/specs/ file (preferred for shared specs)."
                ),
                max_length=80000,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="papertrailentry",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("picked", "Picked"),
                            ("in_progress", "In progress"),
                            ("blocked", "Blocked"),
                            ("deferred", "Deferred"),
                            ("resolved", "Resolved"),
                            ("wontfix", "Wontfix"),
                            ("rejected", "Rejected"),
                            ("duplicate", "Duplicate"),
                            ("stale", "Stale"),
                            ("superseded", "Superseded"),
                            ("sticky", "Sticky"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
