# Generated by Django 5.2.13 on 2026-05-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_trail", "0006_alter_papertrailentry_abstract_and_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papertrailentry",
            name="abstract",
            field=models.TextField(
                help_text=(
                    "High-detail explanation of why this work was deferred. "
                    "Hard-capped at 1200 words. NEW entries (2026-05-16 onward) "
                    "MUST be written in BDD style: contain a `Given ...`, `When ...`, "
                    "and `Then ...` section so the deferral has a self-contained "
                    "test-shape that the next agent can read as an acceptance spec. "
                    "Existing pre-2026-05-16 abstracts are grandfathered."
                ),
                max_length=9500,
            ),
        ),
    ]
