# Generated by Django 5.2 on 2026-03-25 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_contentmetricsnapshot_content_cms_ci_date_idx_and_more'),
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pipelinediagnostic',
            new_name='suggestions_pipelin_a2cf09_idx',
            old_name='diag_run_reason_idx',
        ),
        migrations.RenameIndex(
            model_name='suggestion',
            new_name='suggestions_status_979f2a_idx',
            old_name='sugg_status_score_idx',
        ),
        migrations.RenameIndex(
            model_name='suggestion',
            new_name='suggestions_destina_ae9e83_idx',
            old_name='sugg_dest_status_idx',
        ),
        migrations.RenameIndex(
            model_name='suggestion',
            new_name='suggestions_host_id_6a5537_idx',
            old_name='sugg_host_status_idx',
        ),
        migrations.RenameIndex(
            model_name='suggestion',
            new_name='suggestions_is_appl_8d6277_idx',
            old_name='sugg_applied_idx',
        ),
        migrations.AlterField(
            model_name='pipelinediagnostic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this diagnostic record was created.'),
        ),
        migrations.AlterField(
            model_name='pipelinediagnostic',
            name='destination',
            field=models.ForeignKey(help_text='The destination content item that was skipped.', on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_diagnostics', to='content.contentitem'),
        ),
        migrations.AlterField(
            model_name='pipelinediagnostic',
            name='detail',
            field=models.JSONField(default=dict, help_text='Extra diagnostic data (e.g. best score found, threshold used).'),
        ),
        migrations.AlterField(
            model_name='pipelinediagnostic',
            name='skip_reason',
            field=models.CharField(choices=[('already_has_pending', 'Already has a pending suggestion'), ('no_semantic_matches', 'No semantic matches found'), ('all_candidates_filtered', 'All candidates filtered out'), ('no_host_sentences', 'No eligible host sentences found'), ('score_too_low', 'Best match score below threshold'), ('no_embedding', 'Destination has no embedding'), ('max_links_reached', 'Host already has max links'), ('anchor_banned', 'All candidate anchors are banned'), ('short_post', 'Post too short to distill'), ('host_reuse_cap', 'Host reuse cap reached'), ('circular_suppressed', 'Circular candidate suppressed'), ('cross_silo_blocked', 'Cross-silo candidate blocked by strict mode'), ('other', 'Other')], db_index=True, help_text='Short code describing why no suggestion was created.', max_length=100),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID — used by the frontend to subscribe to WebSocket progress.', max_length=255),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='config_snapshot',
            field=models.JSONField(default=dict, help_text='Frozen ML weights and settings at the time this run started.'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='destination_scope',
            field=models.JSONField(default=dict, help_text='Scope config for destination content (which threads are linked to).'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='destinations_processed',
            field=models.IntegerField(default=0, help_text='Number of destination items fully processed.'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='destinations_skipped',
            field=models.IntegerField(default=0, help_text='Number of destination items skipped (no good match found).'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='duration_seconds',
            field=models.FloatField(blank=True, help_text='Total wall-clock seconds the run took to complete.', null=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='host_scope',
            field=models.JSONField(default=dict, help_text='Scope config for host content (which threads can have links inserted).'),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='rerun_mode',
            field=models.CharField(choices=[('skip_pending', "Skip Pending — don't replace existing pending suggestions"), ('supersede_pending', 'Supersede Pending — replace with new suggestions'), ('full_regenerate', 'Full Regenerate — replace all, including approved')], default='skip_pending', help_text='Controls how this run handles destinations that already have suggestions.', max_length=30),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='run_state',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', help_text='Current execution state of this pipeline run.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='suggestions_created',
            field=models.IntegerField(default=0, help_text='Number of new suggestions generated in this run.'),
        ),
        migrations.AlterField(
            model_name='scopepreset',
            name='enabled_ids',
            field=models.JSONField(default=list, help_text='List of ScopeItem PKs included or excluded, depending on scope_mode.'),
        ),
        migrations.AlterField(
            model_name='scopepreset',
            name='name',
            field=models.CharField(help_text="Friendly name for this preset, e.g. 'All Guitar Forums'.", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='anchor_confidence',
            field=models.CharField(choices=[('strong', 'Strong (exact phrase match)'), ('weak', 'Weak (partial / fallback)'), ('none', 'None (no anchor found)')], default='none', help_text='Confidence of the anchor extraction.', max_length=20),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='anchor_edited',
            field=models.CharField(blank=True, help_text='Reviewer-edited anchor (overrides anchor_phrase when set).', max_length=500),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='anchor_end',
            field=models.IntegerField(blank=True, help_text='Character end offset of anchor_phrase within host_sentence_text.', null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='anchor_phrase',
            field=models.CharField(blank=True, help_text='The phrase in the host sentence that becomes the clickable link text.', max_length=500),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='anchor_start',
            field=models.IntegerField(blank=True, help_text='Character offset of anchor_phrase within host_sentence_text.', null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='applied_at',
            field=models.DateTimeField(blank=True, help_text='When the suggestion was marked as applied.', null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='destination',
            field=models.ForeignKey(help_text='The content item that will receive an incoming link.', on_delete=django.db.models.deletion.CASCADE, related_name='destination_suggestions', to='content.contentitem'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='destination_title',
            field=models.CharField(blank=True, help_text='Denormalized destination title for fast display without JOINs.', max_length=500),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='host',
            field=models.ForeignKey(help_text='The content item whose post will contain the new link.', on_delete=django.db.models.deletion.CASCADE, related_name='host_suggestions', to='content.contentitem'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='host_sentence',
            field=models.ForeignKey(help_text='The specific sentence where the link will be inserted.', on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='content.sentence'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='host_sentence_text',
            field=models.TextField(blank=True, help_text='Denormalized sentence text for fast display without JOINs.'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='is_applied',
            field=models.BooleanField(default=False, help_text='True when the reviewer has manually applied this link on the live forum.'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='pipeline_run',
            field=models.ForeignKey(blank=True, help_text='The pipeline run that generated this suggestion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='suggestions.pipelinerun'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('', '— No reason —'), ('irrelevant', 'Irrelevant / off-topic'), ('low_quality', 'Low quality match'), ('already_linked', 'Already linked'), ('bad_anchor', 'Bad anchor text'), ('wrong_context', 'Wrong context'), ('duplicate', 'Duplicate suggestion'), ('other', 'Other')], help_text='Why this suggestion was rejected.', max_length=100),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='repeated_anchor',
            field=models.BooleanField(default=False, help_text='True if this anchor is already used in another active suggestion for this destination.'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When a reviewer approved or rejected this suggestion.', null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='reviewer_notes',
            field=models.TextField(blank=True, help_text='Free-text notes from the reviewer.'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='score_final',
            field=models.FloatField(db_index=True, default=0.0, help_text='Weighted composite of all score components. Used to rank suggestions.'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='score_keyword',
            field=models.FloatField(default=0.0, help_text='Keyword overlap score between destination distilled text and host sentence.'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='score_node_affinity',
            field=models.FloatField(default=0.0, help_text='Bonus when destination and host are in related forum nodes.'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='score_pagerank',
            field=models.FloatField(default=0.0, help_text='PageRank authority of the destination (higher = more valuable).'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='score_weighted_pagerank',
            field=models.FloatField(default=0.0, help_text='Weighted authority of the destination (higher = more editorially prominent).'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='score_quality',
            field=models.FloatField(default=0.0, help_text='Quality score based on host thread engagement metrics.'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='score_semantic',
            field=models.FloatField(default=0.0, help_text='Cosine similarity between destination embedding and host sentence embedding.'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='score_velocity',
            field=models.FloatField(default=0.0, help_text='Velocity/recency bonus for trending destinations.'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='stale_reason',
            field=models.CharField(blank=True, help_text="Why this suggestion became stale (e.g. 'host post edited').", max_length=200),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('verified', 'Verified'), ('stale', 'Stale'), ('superseded', 'Superseded')], db_index=True, default='pending', help_text='Current review/lifecycle status of this suggestion.', max_length=20),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='superseded_at',
            field=models.DateTimeField(blank=True, help_text='When this suggestion was superseded.', null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='Points to the newer suggestion that replaced this one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='suggestions.suggestion'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the link was automatically verified as live via XenForo API.', null=True),
        ),
    ]
