# Generated by Django 5.2 on 2026-03-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "suggestions",
            "0002_rename_diag_run_reason_idx_suggestions_pipelin_a2cf09_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="suggestion",
            old_name="score_weighted_pagerank",
            new_name="score_march_2026_pagerank",
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="score_march_2026_pagerank",
            field=models.FloatField(
                default=0.0,
                help_text="March 2026 PageRank of the destination (higher = more editorially prominent).",
                verbose_name="March 2026 PageRank",
            ),
        ),
    ]
