# Generated by Django 5.2 on 2026-03-25 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "suggestions",
            "0003_rename_score_weighted_pagerank_to_score_march_2026_pagerank",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestion",
            name="score_pagerank",
        ),
    ]
