# Generated by Django 5.2 on 2026-03-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0005_suggestion_score_link_freshness"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="phrase_match_diagnostics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Explainable FR-008 phrase-match details for review and debugging.",
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="score_phrase_relevance",
            field=models.FloatField(
                default=0.5,
                help_text="FR-008 phrase relevance score for this destination/host sentence pair. 0.5 means neutral.",
            ),
        ),
    ]
