# Generated by Django 5.2 on 2026-03-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0006_suggestion_phrase_matching_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="learned_anchor_diagnostics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Explainable FR-009 learned-anchor diagnostics for review and debugging.",
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="score_learned_anchor_corroboration",
            field=models.FloatField(
                default=0.5,
                help_text="FR-009 learned-anchor corroboration score for this destination/host sentence pair. 0.5 means neutral.",
            ),
        ),
    ]
