# Generated by Django 5.2 on 2026-03-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0012_fr013_feedback_reranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="cluster_diagnostics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Explainable FR-014 near-duplicate clustering details for review and debugging.",
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="score_cluster_suppression",
            field=models.FloatField(
                default=0.0,
                help_text="FR-014 near-duplicate clustering suppression score. Negative values indicate suppression.",
            ),
        ),
    ]
