# Generated by Django 5.2 on 2026-04-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0019_upsert_recommended_future_signal_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightadjustmenthistory',
            name='source',
            field=models.CharField(choices=[('r_auto', 'Monthly R auto-tune'), ('cs_auto_tune', 'C# L-BFGS auto-tune (FR-018)'), ('manual', 'Manual save'), ('preset_applied', 'Preset applied')], db_index=True, help_text='What triggered this weight change.', max_length=20),
        ),
        migrations.CreateModel(
            name='RankingChallenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('run_id', models.CharField(help_text='Opaque identifier from the C# tune run (e.g. a GUID).', max_length=200, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending evaluation'), ('promoted', 'Promoted to champion'), ('rolled_back', 'Rolled back after regression'), ('rejected', 'Rejected — did not beat champion')], db_index=True, default='pending', help_text='Lifecycle state of this challenger.', max_length=20)),
                ('candidate_weights', models.JSONField(default=dict, help_text='Flat key→value map of the four tunable weights proposed by the optimizer: w_semantic, w_keyword, w_node, w_quality.')),
                ('baseline_weights', models.JSONField(default=dict, help_text='Snapshot of the four active weights at the moment C# submitted this challenger.')),
                ('predicted_quality_score', models.FloatField(blank=True, help_text='Predicted link-quality score from the C# optimizer for the candidate weights.', null=True)),
                ('champion_quality_score', models.FloatField(blank=True, help_text='Predicted link-quality score for the current champion weights (for comparison).', null=True)),
                ('history', models.OneToOneField(blank=True, help_text='The WeightAdjustmentHistory row written when this challenger was promoted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenger', to='suggestions.weightadjustmenthistory')),
            ],
            options={
                'verbose_name': 'Ranking Challenger',
                'verbose_name_plural': 'Ranking Challengers',
                'ordering': ['-created_at'],
            },
        ),
    ]
