# Generated by Django 5.2 on 2026-04-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0021_suggestion_candidate_origin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="graph_walk_diagnostics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Explainable random walk details (steps, seeds, visit counts) for graph candidates.",
            ),
        ),
    ]
