# Generated by Django 5.2 on 2026-04-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0022_suggestion_graph_walk_diagnostics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinediagnostic",
            name="skip_reason",
            field=models.CharField(
                choices=[
                    ("already_has_pending", "Already has a pending suggestion"),
                    ("no_semantic_matches", "No semantic matches found"),
                    ("all_candidates_filtered", "All candidates filtered out"),
                    ("no_host_sentences", "No eligible host sentences found"),
                    ("score_too_low", "Best match score below threshold"),
                    ("no_embedding", "Destination has no embedding"),
                    ("max_links_reached", "Host already has max links"),
                    ("anchor_banned", "All candidate anchors are banned"),
                    ("anchor_too_long", "Anchor text exceeds maximum word count"),
                    ("short_post", "Post too short to distill"),
                    ("host_reuse_cap", "Host reuse cap reached"),
                    ("circular_suppressed", "Circular candidate suppressed"),
                    (
                        "cross_silo_blocked",
                        "Cross-silo candidate blocked by strict mode",
                    ),
                    ("paragraph_cluster", "Host paragraph already has a suggestion"),
                    ("other", "Other"),
                ],
                db_index=True,
                help_text="Short code describing why no suggestion was created.",
                max_length=100,
            ),
        ),
    ]
