# Generated by Django 5.2 on 2026-04-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0028_alter_weightadjustmenthistory_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="is_quarantined",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if this run has been quarantined after repeated failures (>3 consecutive).",
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="phase_log",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Ordered list of pipeline phase entries: [{"phase": "fetch_content", "started_at": "...", "completed_at": "...", "item_count": 0, "status": "completed"}]',
            ),
        ),
    ]
