# Generated by Django 5.2.13 on 2026-04-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0030_metatournamentresult_holdoutquery"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="anchor_diversity_diagnostics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Explainable FR-045 anchor-diversity details for review and debugging.",
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="keyword_stuffing_diagnostics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Explainable FR-198 keyword-stuffing details for review and debugging.",
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="link_farm_diagnostics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Explainable FR-197 reciprocal-ring details for review and debugging.",
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="score_anchor_diversity",
            field=models.FloatField(
                default=0.5,
                help_text="FR-045 anchor-diversity anti-spam score. 0.5 = neutral, lower values mean the anchor is too repetitive for the destination.",
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="score_keyword_stuffing",
            field=models.FloatField(
                default=0.5,
                help_text="FR-198 keyword-stuffing anti-spam score. 0.5 = neutral, lower values mean the destination text looks more stuffed.",
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="score_link_farm",
            field=models.FloatField(
                default=0.5,
                help_text="FR-197 link-farm anti-spam score. 0.5 = neutral, lower values mean the destination sits in a suspicious reciprocal ring.",
            ),
        ),
        migrations.AlterField(
            model_name="pipelinediagnostic",
            name="skip_reason",
            field=models.CharField(
                choices=[
                    ("already_has_pending", "Already has a pending suggestion"),
                    ("no_semantic_matches", "No semantic matches found"),
                    ("all_candidates_filtered", "All candidates filtered out"),
                    ("no_host_sentences", "No eligible host sentences found"),
                    ("score_too_low", "Best match score below threshold"),
                    ("no_embedding", "Destination has no embedding"),
                    ("max_links_reached", "Host already has max links"),
                    ("anchor_banned", "All candidate anchors are banned"),
                    ("anchor_too_long", "Anchor text exceeds maximum word count"),
                    ("short_post", "Post too short to distill"),
                    ("host_reuse_cap", "Host reuse cap reached"),
                    ("circular_suppressed", "Circular candidate suppressed"),
                    (
                        "cross_silo_blocked",
                        "Cross-silo candidate blocked by strict mode",
                    ),
                    ("paragraph_cluster", "Host paragraph already has a suggestion"),
                    (
                        "anchor_diversity_blocked",
                        "Anchor diversity guard blocked the candidate",
                    ),
                    ("other", "Other"),
                ],
                db_index=True,
                help_text="Short code describing why no suggestion was created.",
                max_length=100,
            ),
        ),
    ]
