# Generated by Django 5.2.13 on 2026-04-18 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_contentitem_embedding_model_version_and_more'),
        ('suggestions', '0032_upsert_runtime_antispam_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_rejected_at', models.DateTimeField(auto_now_add=True, help_text='When this (host, destination) pair was first rejected.')),
                ('last_rejected_at', models.DateTimeField(db_index=True, help_text='When this pair was most recently rejected. Drives the suppression window during candidate generation.')),
                ('rejection_count', models.PositiveIntegerField(default=1, help_text='How many times this exact (host, destination) pair has been rejected.')),
                ('destination', models.ForeignKey(help_text='The suggested link target that was rejected.', on_delete=django.db.models.deletion.CASCADE, related_name='rejected_pair_destinations', to='content.contentitem')),
                ('host', models.ForeignKey(help_text='The page where a link was suggested and then rejected.', on_delete=django.db.models.deletion.CASCADE, related_name='rejected_pair_hosts', to='content.contentitem')),
            ],
            options={
                'verbose_name': 'Rejected Pair',
                'verbose_name_plural': 'Rejected Pairs',
                'indexes': [models.Index(fields=['-last_rejected_at'], name='suggestions_last_re_28d662_idx')],
                'constraints': [models.UniqueConstraint(fields=('host', 'destination'), name='unique_rejected_host_destination')],
            },
        ),
    ]
