# Generated by Django 5.2.13 on 2026-04-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0041_suggestion_conformal_bounds"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestionImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        help_text="0-based rank of the suggestion in the review queue at impression time. Same row showing up at different positions gets one Impression row per position."
                    ),
                ),
                (
                    "impressed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the suggestion entered the operator's viewport.",
                    ),
                ),
                (
                    "clicked",
                    models.BooleanField(
                        default=False,
                        help_text="True when the operator interacted (approved / rejected / clicked through). False = impression-only (operator scrolled past). Updated post-hoc when the click event fires.",
                    ),
                ),
                (
                    "dwell_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Optional — how long the suggestion stayed in viewport before scroll-out or click. NULL = not measured by the frontend hook.",
                        null=True,
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        help_text="The suggestion that was impressed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressions",
                        to="suggestions.suggestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suggestion Impression",
                "verbose_name_plural": "Suggestion Impressions",
                "ordering": ["-impressed_at"],
                "indexes": [
                    models.Index(
                        fields=["-impressed_at", "position"],
                        name="suggestions_impress_158af4_idx",
                    ),
                    models.Index(
                        fields=["suggestion", "-impressed_at"],
                        name="suggestions_suggest_9d1d5f_idx",
                    ),
                ],
            },
        ),
    ]
