# Generated by Django 5.2 on 2026-04-30 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0054_upsert_meta_expansion_slots"),
    ]

    operations = []
