# Generated by Django 5.2.13 on 2026-04-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0055_add_char_ngram_vector_to_contentitem'),
    ]

    operations = [
    ]
