# Generated by Django 5.2.14 on 2026-06-15 08:31

from django.db import migrations

NEW_VALUES = {
    # FR-260 Time-as-Operator Spectral Decay
    "tosd.enabled": "true",
    "tosd.ranking_weight": "0.06",
    "tosd.filter_strength": "0.8",
    # FR-261 Directed Sequential Transition Probability
    "dstp.enabled": "true",
    "dstp.ranking_weight": "0.08",
    "dstp.smoothing_alpha": "5.0",
    # FR-262 In-Community Popularity Contrast
    "icpc.enabled": "true",
    "icpc.ranking_weight": "0.04",
    "icpc.min_community_size": "10",
    # FR-263 Stochastic Block Model Affinity
    "sbma.enabled": "true",
    "sbma.ranking_weight": "0.05",
    "sbma.num_blocks": "20",
    # FR-264 Riemannian Geodesic Semantic Distance
    "rgsd.enabled": "true",
    "rgsd.ranking_weight": "0.10",
    "rgsd.curvature_penalty": "1.5",
    # FR-265 Cross-Silo Bridging Reward
    "csbr.enabled": "true",
    "csbr.ranking_weight": "0.05",
    "csbr.min_overlap_threshold": "0.7",
}

def upsert_advanced_graph_signals_defaults(apps, schema_editor):
    WeightPreset = apps.get_model("suggestions", "WeightPreset")

    preset, _ = WeightPreset.objects.get_or_create(
        name="Recommended",
        defaults={
            "is_system": True,
            "weights": dict(NEW_VALUES),
        },
    )

    weights = dict(preset.weights or {})
    weights.update(NEW_VALUES)
    preset.is_system = True
    preset.weights = weights
    preset.save(update_fields=["is_system", "weights", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0070_seed_tantivy_bm25_default_on'),
    ]

    operations = [
        migrations.RunPython(
            upsert_advanced_graph_signals_defaults, reverse_code=migrations.RunPython.noop
        ),
    ]
