# Generated by Django 5.2.14 on 2026-06-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0071_seed_advanced_graph_signals_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='csbr_diagnostics',
            field=models.JSONField(blank=True, default=dict, help_text='Explainable FR-265 Cross-Silo Bridging Reward diagnostics.'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='dstp_diagnostics',
            field=models.JSONField(blank=True, default=dict, help_text='Explainable FR-261 Directed Sequential Transition Probability diagnostics.'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='icpc_diagnostics',
            field=models.JSONField(blank=True, default=dict, help_text='Explainable FR-262 In-Community Popularity Contrast diagnostics.'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='rgsd_diagnostics',
            field=models.JSONField(blank=True, default=dict, help_text='Explainable FR-264 Riemannian Geodesic Semantic Distance diagnostics.'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='sbma_diagnostics',
            field=models.JSONField(blank=True, default=dict, help_text='Explainable FR-263 Stochastic Block Model Affinity diagnostics.'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='score_csbr',
            field=models.FloatField(default=0.0, help_text='FR-265 Cross-Silo Bridging Reward. Rewards connecting overlapping personas across silos. 0.0 = neutral.'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='score_dstp',
            field=models.FloatField(default=0.0, help_text='FR-261 Directed Sequential Transition Probability. Path continuation likelihood. 0.0 = neutral.'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='score_icpc',
            field=models.FloatField(default=0.0, help_text='FR-262 In-Community Popularity Contrast. Rewards local vs global degree disparity. 0.0 = neutral.'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='score_rgsd',
            field=models.FloatField(default=0.0, help_text='FR-264 Riemannian Geodesic Semantic Distance. Semantic space distance penalty. 0.0 = neutral.'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='score_sbma',
            field=models.FloatField(default=0.0, help_text='FR-263 Stochastic Block Model Affinity. Probability of edge given node communities. 0.0 = neutral.'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='score_tosd',
            field=models.FloatField(default=0.0, help_text='FR-260 Time-as-Operator Spectral Decay. Boost based on spectral diffusion distances. 0.0 = neutral.'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='tosd_diagnostics',
            field=models.JSONField(blank=True, default=dict, help_text='Explainable FR-260 Time-as-Operator Spectral Decay diagnostics.'),
        ),
    ]
