# Generated by Django 5.2 on 2026-04-04 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0014_fr014_near_duplicate_clustering"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("surface_form", models.CharField(db_index=True, max_length=255)),
                ("canonical_form", models.CharField(db_index=True, max_length=255)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("keyword", "Keyword"),
                            ("named_entity", "Named Entity"),
                            ("topic_tag", "Topic Tag"),
                        ],
                        default="keyword",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["canonical_form", "entity_type"],
                        name="knowledge_g_canonic_5f6ed2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ArticleEntityEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=0.0)),
                ("extraction_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_edges",
                        to="content.contentitem",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_edges",
                        to="knowledge_graph.entitynode",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["extraction_version"],
                        name="knowledge_g_extract_d00cb3_idx",
                    )
                ],
                "unique_together": {("content_item", "entity")},
            },
        ),
    ]
