# Generated by Django 5.2 on 2026-04-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entitynode',
            unique_together={('canonical_form', 'entity_type')},
        ),
    ]
