# Generated by Django 5.2.13 on 2026-05-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('glitchtip', 'GlitchTip'), ('pyroscope', 'Pyroscope'), ('agent', 'Agent find')], db_index=True, max_length=16)),
                ('external_id', models.CharField(help_text='Source-specific id: GlitchTip issue id OR Pyroscope function fingerprint OR free-form string for agent finds.', max_length=128)),
                ('fingerprint', models.CharField(db_index=True, help_text='Stable hash for dedup across sources. Two rows with the same fingerprint are considered the same root cause.', max_length=64)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('affected_files', models.JSONField(blank=True, default=list, help_text='List of repo-relative file paths the fix is likely to touch. Used by agents to decide if their work overlaps.')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('picked', 'Picked'), ('fixing', 'Fixing'), ('resolved', 'Resolved'), ('deferred', 'Deferred')], db_index=True, default='open', max_length=16)),
                ('priority_score', models.FloatField(default=0.0, help_text='Set by the daily picker (spec: docs/CPP-DAILY-ISSUE-PICKER-SPEC.md). Higher = more important. Used to surface the top 10 each day.')),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, help_text='Agent name (claude, codex, gemini) or human username that closed the issue.', max_length=64)),
                ('fix_commit_sha', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'auto_issues_autoissue',
                'ordering': ['-priority_score', '-last_seen'],
                'indexes': [models.Index(fields=['status', '-priority_score'], name='auto_issues_status_cfefe8_idx'), models.Index(fields=['source', 'status'], name='auto_issues_source_651c18_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_autoissue_source_external_id')],
            },
        ),
    ]
