# Generated by Django 5.2.13 on 2026-05-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoissue',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text="Plain-English note from the resolving agent. Two parts: (1) the trap (what's NOT obvious about this code area), (2) the fix shape (what worked). Read by future agents via `manage.py search_resolved_issues --area <path>`."),
        ),
    ]
