# Generated by Django 5.2.13 on 2026-05-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_issues', '0002_autoissue_lessons_learned'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoissue',
            name='canonical_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Cross-source dedup key. Same value across sources for the same root cause.', max_length=64),
        ),
        migrations.AddField(
            model_name='autoissue',
            name='source_observations',
            field=models.JSONField(blank=True, default=list, help_text='List of {source, external_id, first_seen, last_seen, occurrence_count} entries — one per source that has observed this root cause.'),
        ),
        migrations.AlterField(
            model_name='autoissue',
            name='fingerprint',
            field=models.CharField(db_index=True, help_text='Source-specific fingerprint. Differs across sources (GT, internal, Pyroscope each compute their own).', max_length=64),
        ),
        migrations.AddIndex(
            model_name='autoissue',
            index=models.Index(fields=['canonical_fingerprint', 'status'], name='auto_issues_canonic_bb4935_idx'),
        ),
    ]
