# Generated by Django 5.2.13 on 2026-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_issues', '0006_add_faro_tempo_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoissue',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Source-specific fingerprint. Differs across sources (GT, internal, Pyroscope each compute their own).', max_length=64),
        ),
    ]
