"""Add the four new AutoIssue source choices introduced by Phase 6 of
the test-hardening plan (2026-05-12) and seed each new picker's
tunable AppSettings.

The four new sources are:

- ``mutation``  — surviving mutants from mutmut (Python), Stryker
                  (Angular), or Mull (C++). One row per surviving
                  ``(tool, mutator, file:line)``.
- ``fuzz``      — libFuzzer crashes, OOMs, and leaks; also
                  ``kind=fuzz-coverage-gap`` rows emitted for every C++
                  public API without a corresponding fuzz target.
- ``contract``  — Pact provider-verification drift. One row per failed
                  ``(consumer, interaction)``.
- ``gh_ci``     — failed GitHub Actions workflow runs surfaced via
                  ``gh run list --status failure --limit 10``. One row
                  per ``databaseId``.

DEFAULT-ON: every AppSetting seeded here is ON with a sensible
non-zero starting value via ``get_or_create``. None are external-data-
gated — all four sources are internal CI artefacts.
"""

from django.db import migrations, models


SOURCE_CHOICES = [
    ("glitchtip", "GlitchTip"),
    ("pyroscope", "Pyroscope"),
    ("tempo", "Tempo"),
    ("loki", "Loki"),
    ("faro", "Faro"),
    ("agent", "Agent find"),
    ("mutation", "Mutation testing"),
    ("fuzz", "Fuzz testing"),
    ("contract", "Contract drift"),
    ("gh_ci", "GH Actions CI failure"),
]


# Per-source tunables seeded ON via get_or_create. Each entry is the
# initial scope / threshold the corresponding picker reads at runtime.
PICKER_DEFAULTS = {
    # Mutation pickers
    "mutation.mutmut.report_path": {
        "value": "backend/reports/mutmut.json",
        "value_type": "string",
        "category": "observability",
        "description": (
            "Path the mutation picker reads to find Python (mutmut) "
            "surviving mutants. Generated by the python-mutmut CI job."
        ),
    },
    "mutation.stryker.report_path": {
        "value": "frontend/reports/stryker.json",
        "value_type": "string",
        "category": "observability",
        "description": (
            "Path the mutation picker reads to find TypeScript "
            "(Stryker) surviving mutants. Generated by the "
            "frontend-stryker CI job."
        ),
    },
    "mutation.mull.report_path": {
        "value": "backend/extensions/reports/mull/mutants.json",
        "value_type": "string",
        "category": "observability",
        "description": (
            "Path the mutation picker reads to find C++ (Mull) "
            "surviving mutants. Will be populated once the cpp-mull "
            "CI job flips from advisory to blocking."
        ),
    },
    # Fuzz picker
    "fuzz.crashes_dir": {
        "value": "backend/extensions/fuzz",
        "value_type": "string",
        "category": "observability",
        "description": (
            "Directory the fuzz picker scans for crash-*, oom-*, "
            "leak-*, timeout-* reproducer files dropped by libFuzzer."
        ),
    },
    "fuzz.coverage_gap_severity": {
        "value": "low",
        "value_type": "string",
        "category": "observability",
        "description": (
            "Severity for kind=fuzz-coverage-gap rows (one per C++ "
            "public API without a corresponding fuzz target). Low by "
            "default so the queue isn't dominated by the ratchet."
        ),
    },
    # Lint-error picker (reads Super-Linter SARIF)
    "lint_error.sarif_path": {
        "value": "super-linter.log",
        "value_type": "string",
        "category": "observability",
        "description": (
            "Path the lint_error picker reads to find Super-Linter "
            "SARIF findings. Generated by the super-linter CI job."
        ),
    },
    "lint_error.min_severity": {
        "value": "warning",
        "value_type": "string",
        "category": "observability",
        "description": (
            "Minimum SARIF severity that becomes an AutoIssue. "
            "Default 'warning' — drop to 'error' to reduce noise."
        ),
    },
    # Contract-drift picker
    "contract_drift.pact_results_path": {
        "value": "backend/reports/pact-provider-results.json",
        "value_type": "string",
        "category": "observability",
        "description": (
            "Path the contract_drift picker reads to find Pact "
            "provider-verification failures. Generated by the future "
            "pact-provider CI job."
        ),
    },
    # GH-CI failed-runs picker
    "gh_ci.fetch_limit": {
        "value": "10",
        "value_type": "int",
        "category": "observability",
        "description": (
            "Number of latest failed GitHub Actions runs the "
            "ci_failed_runs picker upserts on each scan. Default 10 "
            "matches the [CI FAILED RUNS READ: ...] opening-ritual "
            "marker required by .githooks/check-registry-read.py."
        ),
    },
    "gh_ci.severity": {
        "value": "high",
        "value_type": "string",
        "category": "observability",
        "description": (
            "Default severity for ci_failed_runs picker rows. "
            "Failing CI is high severity — it blocks merges."
        ),
    },
}


def seed_phase_6_settings(apps, schema_editor):
    AppSetting = apps.get_model("core", "AppSetting")
    for key, meta in PICKER_DEFAULTS.items():
        AppSetting.objects.get_or_create(key=key, defaults=meta)


def unseed_phase_6_settings(apps, schema_editor):
    AppSetting = apps.get_model("core", "AppSetting")
    AppSetting.objects.filter(key__in=list(PICKER_DEFAULTS.keys())).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auto_issues", "0007_alter_autoissue_fingerprint"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoissue",
            name="source",
            field=models.CharField(
                choices=SOURCE_CHOICES,
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.RunPython(seed_phase_6_settings, unseed_phase_6_settings),
    ]
