# Generated by Codex on 2026-05-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_issues", "0008_add_test_hardening_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dedupe_key",
                    models.CharField(
                        help_text=(
                            "SHA-256 over check type, command, tool version, source hash, "
                            "file path, and failure fingerprint."
                        ),
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("normal_test", "Normal test"),
                            ("coverage", "Coverage"),
                            ("mutation", "Mutation"),
                            ("static_analysis", "Static analysis"),
                            ("security", "Security"),
                            ("fuzz", "Fuzz"),
                            ("sanitizer", "Sanitizer"),
                            ("tool_readiness", "Tool readiness"),
                            ("missing_report", "Missing report"),
                            ("ci", "CI"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("passed", "Passed"), ("failed", "Failed")],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("tool_name", models.CharField(max_length=64)),
                ("tool_version", models.CharField(blank=True, max_length=128)),
                ("command", models.TextField()),
                ("source_hash", models.CharField(db_index=True, max_length=64)),
                ("file_path", models.CharField(blank=True, db_index=True, max_length=512)),
                (
                    "failure_fingerprint",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("target_percent", models.FloatField(blank=True, null=True)),
                ("actual_percent", models.FloatField(blank=True, null=True)),
                (
                    "summary",
                    models.TextField(
                        help_text=(
                            "Plain-English compact summary. Service rejects values over "
                            "600 words."
                        )
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("raw_report_hash", models.CharField(blank=True, max_length=64)),
                ("raw_report_gzip", models.BinaryField(blank=True, null=True)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Retention marker used by quality evidence cleanup.",
                        null=True,
                    ),
                ),
                (
                    "auto_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_evidence",
                        to="auto_issues.autoissue",
                    ),
                ),
            ],
            options={
                "db_table": "auto_issues_qualityevidence",
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["check_type", "status", "-last_seen"],
                        name="auto_issues_check_t_ccb6db_idx",
                    ),
                    models.Index(
                        fields=["source_hash", "failure_fingerprint"],
                        name="auto_issues_source__237f70_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "status"],
                        name="auto_issues_expires_dc964c_idx",
                    ),
                ],
            },
        ),
    ]
