# Generated by Codex on 2026-05-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_issues", "0009_quality_evidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityRawSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_report_hash",
                    models.CharField(
                        help_text="SHA-256 over the capped raw snippet bytes.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("raw_report_gzip", models.BinaryField()),
                ("uncompressed_bytes", models.PositiveIntegerField(default=0)),
                ("compressed_bytes", models.PositiveIntegerField(default=0)),
                ("reference_count", models.PositiveIntegerField(default=1)),
                ("first_captured_week_start", models.DateField(db_index=True)),
                ("last_captured_week_start", models.DateField(db_index=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "auto_issues_qualityrawsnippet",
                "ordering": ["-last_captured_week_start", "-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["-last_captured_week_start", "-last_seen"],
                        name="auto_issues_last_ca_32cc3c_idx",
                    ),
                ],
            },
        ),
        migrations.RemoveField(
            model_name="qualityevidence",
            name="raw_report_gzip",
        ),
        migrations.AddField(
            model_name="qualityevidence",
            name="raw_snippet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quality_evidence",
                to="auto_issues.qualityrawsnippet",
            ),
        ),
    ]
