# Generated by Codex on 2026-05-15

from django.db import migrations, models
import django.db.models.deletion


DEFAULT_CATEGORIES = (
    ("security", "Security", "Sensitive data, validation, secrets, and platform safety.", 10),
    ("performance", "Performance", "Slow paths, expensive queries, memory use, and scaling.", 20),
    ("maintainability", "Maintainability", "Small modules, reuse, separation, and simple design.", 30),
    ("readability", "Readability", "Names, comments, formatting, and dead-code cleanup.", 40),
    ("correctness", "Correctness", "Expected behavior, tests, edge cases, and logic clarity.", 50),
    ("error-handling", "Error handling", "Clear failures, useful logs, retries, and fallbacks.", 60),
    ("concurrency", "Concurrency", "Shared resources, async handling, races, and deadlocks.", 70),
    ("contract", "Contract", "API compatibility, signatures, return shapes, and validation.", 80),
    ("architecture", "Architecture", "Coupling, circular imports, globals, and third-party fit.", 90),
    ("resources", "Resources", "Files, sockets, connections, buffers, and cache invalidation.", 100),
    ("tech-debt", "Tech debt", "Tracked TODOs, magic numbers, and future refactor work.", 110),
    ("observability", "Observability", "Metrics, traces, error context, and monitoring hooks.", 120),
    ("tooling", "Tooling", "Broken, missing, or incomplete test and quality tools.", 125),
    (
        "internationalization",
        "Internationalization",
        "Translations, time zones, locales, accessibility, and right-to-left layout.",
        130,
    ),
    ("uncategorized", "Uncategorized", "Issues that still need a more specific category.", 1000),
)

SOURCE_DEFAULTS = {
    "pyroscope": "performance",
    "tempo": "observability",
    "loki": "observability",
    "faro": "observability",
    "glitchtip": "observability",
    "mutation": "correctness",
    "fuzz": "correctness",
    "contract": "contract",
    "gh_ci": "correctness",
    "agent": "tech-debt",
}


def seed_categories(apps, schema_editor):
    category_model = apps.get_model("auto_issues", "AutoIssueCategory")
    for key, label, description, sort_order in DEFAULT_CATEGORIES:
        category_model.objects.update_or_create(
            key=key,
            defaults={
                "label": label,
                "description": description,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


def backfill_issue_categories(apps, schema_editor):
    category_model = apps.get_model("auto_issues", "AutoIssueCategory")
    issue_model = apps.get_model("auto_issues", "AutoIssue")
    categories = {row.key: row for row in category_model.objects.all()}
    fallback = categories["uncategorized"]
    for issue in issue_model.objects.filter(category__isnull=True).iterator():
        issue.category = categories.get(SOURCE_DEFAULTS.get(issue.source, ""), fallback)
        issue.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ("auto_issues", "0010_quality_raw_snippet"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoIssueCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable machine key, for example security or performance.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(default=True),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="auto_issues.autoissuecategory",
                    ),
                ),
            ],
            options={
                "db_table": "auto_issues_autoissuecategory",
                "ordering": ["sort_order", "label"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="auto_issues_is_acti_9f73c2_idx",
                    ),
                    models.Index(
                        fields=["parent", "sort_order"],
                        name="auto_issues_parent__fff4df_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="autoissue",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="auto_issues.autoissuecategory",
            ),
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
        migrations.RunPython(backfill_issue_categories, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="autoissue",
            index=models.Index(
                fields=["category", "status"],
                name="auto_issues_categor_3172b8_idx",
            ),
        ),
    ]
