# Generated by Django 5.2.13 on 2026-05-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_issues', '0011_autoissue_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoissue',
            name='spam_score',
            field=models.FloatField(blank=True, db_index=True, help_text='Bayesian spam score in [0, 1] from `extensions.autoissue_spam_filter` (Sahami et al. 1998). 0=definitely ham, 1=definitely spam. NULL until first classification. Score-only — never auto-changes status; session-start pickers sort by (priority_score - spam_score) so noisy rows surface last. Rule H, added 2026-05-15.', null=True),
        ),
    ]
