# Generated by Codex on 2026-05-18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_issues", "0012_autoissue_spam_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoissue",
            name="concept_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                db_index=True,
                default=list,
                help_text=(
                    "Approved concept tags used to find lessons across repo paths."
                ),
                size=None,
            ),
        ),
    ]
