# Generated by Django 5.2.14 on 2026-05-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_issues', '0015_seed_rust_defect_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoissue',
            name='source',
            field=models.CharField(choices=[('glitchtip', 'GlitchTip'), ('pyroscope', 'Pyroscope'), ('tempo', 'Tempo'), ('loki', 'Loki'), ('faro', 'Faro'), ('sonarqube', 'SonarQube'), ('vmalert', 'vmalert'), ('rust_defect', 'Rust defect'), ('agent', 'Agent find'), ('mutation', 'Mutation testing'), ('fuzz', 'Fuzz testing'), ('contract', 'Contract drift'), ('gh_ci', 'GH Actions CI failure')], db_index=True, max_length=16),
        ),
    ]
