# Generated by Codex on 2026-05-21.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_issues", "0016_alter_autoissue_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="FindBugsLearnedLesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("classification", models.CharField(choices=[("false_positive", "False positive"), ("false_negative", "False negative")], db_index=True, max_length=20)),
                ("lesson_fingerprint", models.CharField(max_length=64, unique=True)),
                ("compressed_payload", models.BinaryField()),
                ("uncompressed_bytes", models.PositiveIntegerField(default=0)),
                ("compressed_bytes", models.PositiveIntegerField(default=0)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("approved", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("source_issue", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="findbugs_lessons", to="auto_issues.autoissue")),
            ],
            options={
                "db_table": "auto_issues_findbugslearnedlesson",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.AddIndex(
            model_name="findbugslearnedlesson",
            index=models.Index(fields=["classification", "-last_seen"], name="auto_issues_classif_9377e4_idx"),
        ),
        migrations.AddIndex(
            model_name="findbugslearnedlesson",
            index=models.Index(fields=["approved", "-last_seen"], name="auto_issues_approve_4415e1_idx"),
        ),
    ]
