# Generated by Django 5.2.13 on 2026-05-28 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_issues", "0018_add_test_failure_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoissue",
            name="priority_score",
            field=models.FloatField(
                default=0.0,
                help_text=(
                    "Set by the daily picker (spec: docs/CPP-DAILY-ISSUE-PICKER-SPEC.md). "
                    "Higher = more important. Used to surface the top 10 each day."
                ),
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="autoissue",
            name="source",
            field=models.CharField(
                choices=[
                    ("glitchtip", "GlitchTip"),
                    ("pyroscope", "Pyroscope"),
                    ("tempo", "Tempo"),
                    ("loki", "Loki"),
                    ("faro", "Faro"),
                    ("sonarqube", "SonarQube"),
                    ("vmalert", "vmalert"),
                    ("rust_defect", "Rust defect"),
                    ("pprof", "pprof"),
                    ("alloy", "Alloy"),
                    ("perfetto", "Perfetto"),
                    ("gwp_asan", "GWP-ASan"),
                    ("prometheus", "Prometheus"),
                    ("pg_stat", "pg_stat"),
                    ("lighthouse", "Lighthouse"),
                    ("test_failure", "Test failure"),
                    ("agent", "Agent find"),
                    ("mutation", "Mutation testing"),
                    ("fuzz", "Fuzz testing"),
                    ("contract", "Contract drift"),
                    ("gh_ci", "GH Actions CI failure"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="autoissue",
            name="spam_score",
            field=models.FloatField(
                blank=True,
                db_index=True,
                help_text=(
                    "Bayesian spam score in [0, 1] from `extensions.autoissue_spam_filter` "
                    "(Sahami et al. 1998). 0=definitely ham, 1=definitely spam. NULL "
                    "until first classification. Score-only — never auto-changes status; "
                    "session-start pickers sort by (priority_score - spam_score) so noisy "
                    "rows surface last. Rule H, added 2026-05-15."
                ),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
