# Generated by Codex on 2026-05-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_issues", "0019_alter_autoissue_priority_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeQLFindingEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("finding_fingerprint", models.CharField(max_length=64, unique=True)),
                ("language", models.CharField(db_index=True, max_length=32)),
                ("rule_id", models.CharField(max_length=128)),
                ("file_path", models.TextField()),
                ("line", models.PositiveIntegerField(default=1)),
                ("compression", models.CharField(default="lz4", max_length=16)),
                ("compressed_payload", models.BinaryField()),
                ("uncompressed_bytes", models.PositiveIntegerField(default=0)),
                ("compressed_bytes", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "issue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codeql_evidence",
                        to="auto_issues.autoissue",
                    ),
                ),
            ],
            options={
                "db_table": "auto_issues_codeqlfindingevidence",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.AddIndex(
            model_name="codeqlfindingevidence",
            index=models.Index(fields=["language", "rule_id"], name="auto_issues_languag_1d93fd_idx"),
        ),
        migrations.AddIndex(
            model_name="codeqlfindingevidence",
            index=models.Index(fields=["file_path"], name="auto_issues_file_pa_112846_idx"),
        ),
    ]
