# Generated by Codex on 2026-05-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_issues", "0020_codeql_finding_evidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildFailureEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("failure_fingerprint", models.CharField(max_length=64, unique=True)),
                ("builder", models.CharField(db_index=True, max_length=64)),
                ("targets", models.JSONField(blank=True, default=list)),
                ("command", models.JSONField(blank=True, default=list)),
                ("exit_code", models.PositiveIntegerField(default=1)),
                ("compression", models.CharField(default="lz4", max_length=16)),
                ("compressed_payload", models.BinaryField()),
                ("uncompressed_bytes", models.PositiveIntegerField(default=0)),
                ("compressed_bytes", models.PositiveIntegerField(default=0)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "issue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="build_failure_evidence",
                        to="auto_issues.autoissue",
                    ),
                ),
            ],
            options={
                "db_table": "auto_issues_buildfailureevidence",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.AddIndex(
            model_name="buildfailureevidence",
            index=models.Index(fields=["builder", "-last_seen"], name="auto_issues_builder_d80c43_idx"),
        ),
        migrations.AddIndex(
            model_name="buildfailureevidence",
            index=models.Index(fields=["exit_code", "-last_seen"], name="auto_issues_exit_co_a9152f_idx"),
        ),
    ]
