# Generated by Codex on 2026-06-12

from django.db import migrations, models


def forwards(apps, _schema_editor):
    AutoIssue = apps.get_model("auto_issues", "AutoIssue")
    AutoIssue.objects.filter(source="compiler").update(source="rust_compiler")


def backwards(apps, _schema_editor):
    AutoIssue = apps.get_model("auto_issues", "AutoIssue")
    AutoIssue.objects.filter(source="rust_compiler").update(source="compiler")


class Migration(migrations.Migration):

    dependencies = [
        ("auto_issues", "0025_alter_autoissue_source"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="autoissue",
            name="source",
            field=models.CharField(
                choices=[
                    ("glitchtip", "GlitchTip"),
                    ("pyroscope", "Pyroscope"),
                    ("tempo", "Tempo"),
                    ("loki", "Loki"),
                    ("faro", "Faro"),
                    ("vmalert", "vmalert"),
                    ("rust_defect", "Rust defect"),
                    ("pprof", "pprof"),
                    ("alloy", "Alloy"),
                    ("perfetto", "Perfetto"),
                    ("gwp_asan", "GWP-ASan"),
                    ("prometheus", "Prometheus"),
                    ("pg_stat", "pg_stat"),
                    ("lighthouse", "Lighthouse"),
                    ("test_failure", "Test failure"),
                    ("pytest_failure", "Pytest failure"),
                    ("rust_test_fail", "Rust test failure"),
                    ("agent", "Agent find"),
                    ("mutation", "Mutation testing"),
                    ("fuzz", "Fuzz testing"),
                    ("contract", "Contract drift"),
                    ("gh_ci", "GH Actions CI failure"),
                    ("rust_compiler", "Rust compiler warning"),
                    ("megalinter", "MegaLinter"),
                    ("precommit_warn", "Pre-commit soft gate warning"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
