# Generated by Django 5.2.14 on 2026-06-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_issues', '0026_rust_compiler_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FindBugsLearnedLesson',
        ),
    ]
