listen_addresses = '*'
port = 5432
shared_buffers = 1GB
effective_cache_size = 3GB
work_mem = 16MB
maintenance_work_mem = 256MB
max_connections = 50
max_parallel_workers_per_gather = 2
wal_compression = on
