# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import api_pb2 as api__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClusterdStub(object):
    """Clusterd is the only published service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Cluster = channel.unary_unary(
                '/xf.clusterd.v1.Clusterd/Cluster',
                request_serializer=api__pb2.ClusterRequest.SerializeToString,
                response_deserializer=api__pb2.ClusterResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/xf.clusterd.v1.Clusterd/Health',
                request_serializer=api__pb2.HealthRequest.SerializeToString,
                response_deserializer=api__pb2.HealthResponse.FromString,
                _registered_method=True)


class ClusterdServicer(object):
    """Clusterd is the only published service.
    """

    def Cluster(self, request, context):
        """Cluster groups the supplied items into root-cause clusters. Items whose
        blended similarity meets the request threshold land in the same cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health is the standard liveness probe dialed by clusterd-healthcheck.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterdServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Cluster': grpc.unary_unary_rpc_method_handler(
                    servicer.Cluster,
                    request_deserializer=api__pb2.ClusterRequest.FromString,
                    response_serializer=api__pb2.ClusterResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=api__pb2.HealthRequest.FromString,
                    response_serializer=api__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xf.clusterd.v1.Clusterd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xf.clusterd.v1.Clusterd', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Clusterd(object):
    """Clusterd is the only published service.
    """

    @staticmethod
    def Cluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xf.clusterd.v1.Clusterd/Cluster',
            api__pb2.ClusterRequest.SerializeToString,
            api__pb2.ClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xf.clusterd.v1.Clusterd/Health',
            api__pb2.HealthRequest.SerializeToString,
            api__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
