# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import shared_pb2 as shared__pb2
from . import snapshotd_pb2 as snapshotd__pb2


class SnapshotdStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSnapshot = channel.unary_unary(
                '/xf.sidecars.v1.Snapshotd/CreateSnapshot',
                request_serializer=snapshotd__pb2.CreateSnapshotRequest.SerializeToString,
                response_deserializer=snapshotd__pb2.Snapshot.FromString,
                )
        self.GetSnapshot = channel.unary_unary(
                '/xf.sidecars.v1.Snapshotd/GetSnapshot',
                request_serializer=snapshotd__pb2.GetSnapshotRequest.SerializeToString,
                response_deserializer=snapshotd__pb2.Snapshot.FromString,
                )
        self.ListByIssue = channel.unary_unary(
                '/xf.sidecars.v1.Snapshotd/ListByIssue',
                request_serializer=snapshotd__pb2.ListByIssueRequest.SerializeToString,
                response_deserializer=snapshotd__pb2.SnapshotList.FromString,
                )
        self.Compare = channel.unary_unary(
                '/xf.sidecars.v1.Snapshotd/Compare',
                request_serializer=snapshotd__pb2.CompareRequest.SerializeToString,
                response_deserializer=snapshotd__pb2.ComparisonReport.FromString,
                )
        self.Search = channel.unary_stream(
                '/xf.sidecars.v1.Snapshotd/Search',
                request_serializer=snapshotd__pb2.SearchRequest.SerializeToString,
                response_deserializer=snapshotd__pb2.Snapshot.FromString,
                )
        self.Pin = channel.unary_unary(
                '/xf.sidecars.v1.Snapshotd/Pin',
                request_serializer=snapshotd__pb2.PinRequest.SerializeToString,
                response_deserializer=snapshotd__pb2.Snapshot.FromString,
                )
        self.Unpin = channel.unary_unary(
                '/xf.sidecars.v1.Snapshotd/Unpin',
                request_serializer=snapshotd__pb2.UnpinRequest.SerializeToString,
                response_deserializer=snapshotd__pb2.Snapshot.FromString,
                )
        self.ReadRows = channel.unary_stream(
                '/xf.sidecars.v1.Snapshotd/ReadRows',
                request_serializer=snapshotd__pb2.ReadRowsRequest.SerializeToString,
                response_deserializer=snapshotd__pb2.SnapshotRow.FromString,
                )
        self.DiffBeforeAfter = channel.unary_unary(
                '/xf.sidecars.v1.Snapshotd/DiffBeforeAfter',
                request_serializer=snapshotd__pb2.DiffBeforeAfterRequest.SerializeToString,
                response_deserializer=snapshotd__pb2.ComparisonReport.FromString,
                )
        self.Health = channel.unary_unary(
                '/xf.sidecars.v1.Snapshotd/Health',
                request_serializer=shared__pb2.Empty.SerializeToString,
                response_deserializer=shared__pb2.HealthReply.FromString,
                )


class SnapshotdServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListByIssue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unpin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiffBeforeAfter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SnapshotdServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSnapshot,
                    request_deserializer=snapshotd__pb2.CreateSnapshotRequest.FromString,
                    response_serializer=snapshotd__pb2.Snapshot.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=snapshotd__pb2.GetSnapshotRequest.FromString,
                    response_serializer=snapshotd__pb2.Snapshot.SerializeToString,
            ),
            'ListByIssue': grpc.unary_unary_rpc_method_handler(
                    servicer.ListByIssue,
                    request_deserializer=snapshotd__pb2.ListByIssueRequest.FromString,
                    response_serializer=snapshotd__pb2.SnapshotList.SerializeToString,
            ),
            'Compare': grpc.unary_unary_rpc_method_handler(
                    servicer.Compare,
                    request_deserializer=snapshotd__pb2.CompareRequest.FromString,
                    response_serializer=snapshotd__pb2.ComparisonReport.SerializeToString,
            ),
            'Search': grpc.unary_stream_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=snapshotd__pb2.SearchRequest.FromString,
                    response_serializer=snapshotd__pb2.Snapshot.SerializeToString,
            ),
            'Pin': grpc.unary_unary_rpc_method_handler(
                    servicer.Pin,
                    request_deserializer=snapshotd__pb2.PinRequest.FromString,
                    response_serializer=snapshotd__pb2.Snapshot.SerializeToString,
            ),
            'Unpin': grpc.unary_unary_rpc_method_handler(
                    servicer.Unpin,
                    request_deserializer=snapshotd__pb2.UnpinRequest.FromString,
                    response_serializer=snapshotd__pb2.Snapshot.SerializeToString,
            ),
            'ReadRows': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadRows,
                    request_deserializer=snapshotd__pb2.ReadRowsRequest.FromString,
                    response_serializer=snapshotd__pb2.SnapshotRow.SerializeToString,
            ),
            'DiffBeforeAfter': grpc.unary_unary_rpc_method_handler(
                    servicer.DiffBeforeAfter,
                    request_deserializer=snapshotd__pb2.DiffBeforeAfterRequest.FromString,
                    response_serializer=snapshotd__pb2.ComparisonReport.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=shared__pb2.Empty.FromString,
                    response_serializer=shared__pb2.HealthReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xf.sidecars.v1.Snapshotd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Snapshotd(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Snapshotd/CreateSnapshot',
            snapshotd__pb2.CreateSnapshotRequest.SerializeToString,
            snapshotd__pb2.Snapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Snapshotd/GetSnapshot',
            snapshotd__pb2.GetSnapshotRequest.SerializeToString,
            snapshotd__pb2.Snapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListByIssue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Snapshotd/ListByIssue',
            snapshotd__pb2.ListByIssueRequest.SerializeToString,
            snapshotd__pb2.SnapshotList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Compare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Snapshotd/Compare',
            snapshotd__pb2.CompareRequest.SerializeToString,
            snapshotd__pb2.ComparisonReport.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/xf.sidecars.v1.Snapshotd/Search',
            snapshotd__pb2.SearchRequest.SerializeToString,
            snapshotd__pb2.Snapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Pin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Snapshotd/Pin',
            snapshotd__pb2.PinRequest.SerializeToString,
            snapshotd__pb2.Snapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Unpin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Snapshotd/Unpin',
            snapshotd__pb2.UnpinRequest.SerializeToString,
            snapshotd__pb2.Snapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/xf.sidecars.v1.Snapshotd/ReadRows',
            snapshotd__pb2.ReadRowsRequest.SerializeToString,
            snapshotd__pb2.SnapshotRow.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DiffBeforeAfter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Snapshotd/DiffBeforeAfter',
            snapshotd__pb2.DiffBeforeAfterRequest.SerializeToString,
            snapshotd__pb2.ComparisonReport.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Snapshotd/Health',
            shared__pb2.Empty.SerializeToString,
            shared__pb2.HealthReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
