# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import shared_pb2 as shared__pb2
from . import topicd_pb2 as topicd__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in topicd_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TopicdStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Produce = channel.unary_unary(
                '/xf.sidecars.v1.Topicd/Produce',
                request_serializer=topicd__pb2.TopicdProduceRequest.SerializeToString,
                response_deserializer=shared__pb2.Ack.FromString,
                _registered_method=True)
        self.Consume = channel.unary_stream(
                '/xf.sidecars.v1.Topicd/Consume',
                request_serializer=topicd__pb2.TopicdConsumeRequest.SerializeToString,
                response_deserializer=topicd__pb2.TopicdEvent.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/xf.sidecars.v1.Topicd/Commit',
                request_serializer=topicd__pb2.TopicdCommitRequest.SerializeToString,
                response_deserializer=shared__pb2.Ack.FromString,
                _registered_method=True)
        self.ListTopics = channel.unary_unary(
                '/xf.sidecars.v1.Topicd/ListTopics',
                request_serializer=shared__pb2.Empty.SerializeToString,
                response_deserializer=topicd__pb2.TopicdTopicList.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/xf.sidecars.v1.Topicd/Health',
                request_serializer=shared__pb2.Empty.SerializeToString,
                response_deserializer=shared__pb2.HealthReply.FromString,
                _registered_method=True)


class TopicdServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Produce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTopics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TopicdServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Produce': grpc.unary_unary_rpc_method_handler(
                    servicer.Produce,
                    request_deserializer=topicd__pb2.TopicdProduceRequest.FromString,
                    response_serializer=shared__pb2.Ack.SerializeToString,
            ),
            'Consume': grpc.unary_stream_rpc_method_handler(
                    servicer.Consume,
                    request_deserializer=topicd__pb2.TopicdConsumeRequest.FromString,
                    response_serializer=topicd__pb2.TopicdEvent.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=topicd__pb2.TopicdCommitRequest.FromString,
                    response_serializer=shared__pb2.Ack.SerializeToString,
            ),
            'ListTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTopics,
                    request_deserializer=shared__pb2.Empty.FromString,
                    response_serializer=topicd__pb2.TopicdTopicList.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=shared__pb2.Empty.FromString,
                    response_serializer=shared__pb2.HealthReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xf.sidecars.v1.Topicd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xf.sidecars.v1.Topicd', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Topicd(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Produce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xf.sidecars.v1.Topicd/Produce',
            topicd__pb2.TopicdProduceRequest.SerializeToString,
            shared__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xf.sidecars.v1.Topicd/Consume',
            topicd__pb2.TopicdConsumeRequest.SerializeToString,
            topicd__pb2.TopicdEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xf.sidecars.v1.Topicd/Commit',
            topicd__pb2.TopicdCommitRequest.SerializeToString,
            shared__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xf.sidecars.v1.Topicd/ListTopics',
            shared__pb2.Empty.SerializeToString,
            topicd__pb2.TopicdTopicList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xf.sidecars.v1.Topicd/Health',
            shared__pb2.Empty.SerializeToString,
            shared__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
