# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: topicd.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'topicd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import shared_pb2 as shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctopicd.proto\x12\x0exf.sidecars.v1\x1a\x0cshared.proto\"\x15\n\x13TopicdCommitRequest\"\x16\n\x14TopicdConsumeRequest\"\r\n\x0bTopicdEvent\"\x16\n\x14TopicdProduceRequest\"\x11\n\x0fTopicdTopicList2\xe6\x02\n\x06Topicd\x12\x44\n\x07Produce\x12$.xf.sidecars.v1.TopicdProduceRequest\x1a\x13.xf.sidecars.v1.Ack\x12N\n\x07\x43onsume\x12$.xf.sidecars.v1.TopicdConsumeRequest\x1a\x1b.xf.sidecars.v1.TopicdEvent0\x01\x12\x42\n\x06\x43ommit\x12#.xf.sidecars.v1.TopicdCommitRequest\x1a\x13.xf.sidecars.v1.Ack\x12\x44\n\nListTopics\x12\x15.xf.sidecars.v1.Empty\x1a\x1f.xf.sidecars.v1.TopicdTopicList\x12<\n\x06Health\x12\x15.xf.sidecars.v1.Empty\x1a\x1b.xf.sidecars.v1.HealthReplyB<Z:xf-internal-linker-v2/services/sidecars/api/gen;sidecarsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'topicd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:xf-internal-linker-v2/services/sidecars/api/gen;sidecarsv1'
  _globals['_TOPICDCOMMITREQUEST']._serialized_start=46
  _globals['_TOPICDCOMMITREQUEST']._serialized_end=67
  _globals['_TOPICDCONSUMEREQUEST']._serialized_start=69
  _globals['_TOPICDCONSUMEREQUEST']._serialized_end=91
  _globals['_TOPICDEVENT']._serialized_start=93
  _globals['_TOPICDEVENT']._serialized_end=106
  _globals['_TOPICDPRODUCEREQUEST']._serialized_start=108
  _globals['_TOPICDPRODUCEREQUEST']._serialized_end=130
  _globals['_TOPICDTOPICLIST']._serialized_start=132
  _globals['_TOPICDTOPICLIST']._serialized_end=149
  _globals['_TOPICD']._serialized_start=152
  _globals['_TOPICD']._serialized_end=510
# @@protoc_insertion_point(module_scope)
