# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import attrouted_pb2 as attrouted__pb2
from . import shared_pb2 as shared__pb2


class AttroutedStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Route = channel.unary_unary(
                '/xf.sidecars.v1.Attrouted/Route',
                request_serializer=attrouted__pb2.RouteRequest.SerializeToString,
                response_deserializer=attrouted__pb2.RouteDecision.FromString,
                )
        self.RegisterRule = channel.unary_unary(
                '/xf.sidecars.v1.Attrouted/RegisterRule',
                request_serializer=attrouted__pb2.RouteRule.SerializeToString,
                response_deserializer=attrouted__pb2.RouteRule.FromString,
                )
        self.ListRules = channel.unary_unary(
                '/xf.sidecars.v1.Attrouted/ListRules',
                request_serializer=shared__pb2.Empty.SerializeToString,
                response_deserializer=attrouted__pb2.RouteRuleList.FromString,
                )
        self.RemoveRule = channel.unary_unary(
                '/xf.sidecars.v1.Attrouted/RemoveRule',
                request_serializer=attrouted__pb2.RemoveRuleRequest.SerializeToString,
                response_deserializer=shared__pb2.Ack.FromString,
                )
        self.Replay = channel.unary_unary(
                '/xf.sidecars.v1.Attrouted/Replay',
                request_serializer=attrouted__pb2.ReplayRequest.SerializeToString,
                response_deserializer=attrouted__pb2.ReplayReport.FromString,
                )
        self.Health = channel.unary_unary(
                '/xf.sidecars.v1.Attrouted/Health',
                request_serializer=shared__pb2.Empty.SerializeToString,
                response_deserializer=shared__pb2.HealthReply.FromString,
                )


class AttroutedServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Route(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttroutedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Route': grpc.unary_unary_rpc_method_handler(
                    servicer.Route,
                    request_deserializer=attrouted__pb2.RouteRequest.FromString,
                    response_serializer=attrouted__pb2.RouteDecision.SerializeToString,
            ),
            'RegisterRule': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterRule,
                    request_deserializer=attrouted__pb2.RouteRule.FromString,
                    response_serializer=attrouted__pb2.RouteRule.SerializeToString,
            ),
            'ListRules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRules,
                    request_deserializer=shared__pb2.Empty.FromString,
                    response_serializer=attrouted__pb2.RouteRuleList.SerializeToString,
            ),
            'RemoveRule': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveRule,
                    request_deserializer=attrouted__pb2.RemoveRuleRequest.FromString,
                    response_serializer=shared__pb2.Ack.SerializeToString,
            ),
            'Replay': grpc.unary_unary_rpc_method_handler(
                    servicer.Replay,
                    request_deserializer=attrouted__pb2.ReplayRequest.FromString,
                    response_serializer=attrouted__pb2.ReplayReport.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=shared__pb2.Empty.FromString,
                    response_serializer=shared__pb2.HealthReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xf.sidecars.v1.Attrouted', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Attrouted(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Route(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Attrouted/Route',
            attrouted__pb2.RouteRequest.SerializeToString,
            attrouted__pb2.RouteDecision.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Attrouted/RegisterRule',
            attrouted__pb2.RouteRule.SerializeToString,
            attrouted__pb2.RouteRule.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Attrouted/ListRules',
            shared__pb2.Empty.SerializeToString,
            attrouted__pb2.RouteRuleList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Attrouted/RemoveRule',
            attrouted__pb2.RemoveRuleRequest.SerializeToString,
            shared__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Replay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Attrouted/Replay',
            attrouted__pb2.ReplayRequest.SerializeToString,
            attrouted__pb2.ReplayReport.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xf.sidecars.v1.Attrouted/Health',
            shared__pb2.Empty.SerializeToString,
            shared__pb2.HealthReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
